// Generated by Claude Code (claude-opus-5) for jjmil on 2026-07-28.

using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Draws every <see cref="IStatusBadgeSource"/> on this object as a row of icons
/// under it — Fire's remaining stacks, a Charge bank against its requirement, a
/// Cannon's fuse. Works the same on balls, which carry the same statuses.
///
/// The row is deliberately <em>not</em> a child of the object.
/// <see cref="BoardComponent.FixedUpdate"/> pulses <c>localScale</c> while a
/// component is selected and flippers rotate under input; a parented row would
/// inherit both. Instead it lives at the scene root and is driven to position each
/// frame, which also lets it billboard cleanly — this game's camera drifts
/// (<c>CameraAliveMotion</c>) and pans between points, so a fixed rotation would
/// not stay readable.
/// </summary>
[DisallowMultipleComponent]
public sealed class StatusBadgeDisplay : MonoBehaviour
{
    [Tooltip("Point the row hangs beneath. Defaults to this object's origin, which "
        + "is wrong for components whose visual sits on a child — assign the visual "
        + "there instead.")]
    [SerializeField] private Transform anchor;

    [Tooltip("Added to the library's shared offset, for components that need the "
        + "row nudged clear of their own geometry.")]
    [SerializeField] private Vector3 extraOffset;

    // Cached so the per-frame Sort does not allocate a comparer wrapper for every
    // badge-bearing object on the board.
    private static readonly Comparison<StatusBadgeInfo> bySortOrder =
        (a, b) => a.SortOrder.CompareTo(b.SortOrder);

    private readonly List<IStatusBadgeSource> _sources = new List<IStatusBadgeSource>();
    private readonly List<StatusBadgeInfo> _active = new List<StatusBadgeInfo>();

    private StatusBadgeRow _row;
    private Camera _camera;
    private bool _suppressed;

    private Transform Anchor => anchor != null ? anchor : transform;

    /// <summary>
    /// Attaches a display to <paramref name="host"/> unless it is shop
    /// merchandise. Called from the status utilities, so anything that gains a
    /// status gains its readout without every caller remembering to.
    ///
    /// Note this is a weaker filter than <see cref="StatusTargeting"/>: Flippers
    /// are not valid status *targets*, but Moore's Launcher is a flipper that banks
    /// Charge legitimately and the player needs to see it.
    /// </summary>
    public static StatusBadgeDisplay EnsureOn(GameObject host)
    {
        if (host == null || host.GetComponent<ShopOffer3DEntry>() != null)
        {
            return null;
        }

        StatusBadgeDisplay display = host.GetComponent<StatusBadgeDisplay>();
        if (display == null)
        {
            display = host.AddComponent<StatusBadgeDisplay>();
        }

        return display;
    }

    private void OnDisable()
    {
        HideRow();
    }

    private void OnDestroy()
    {
        if (_row != null)
        {
            Destroy(_row.gameObject);
            _row = null;
        }
    }

    private void LateUpdate()
    {
        // Re-checked every frame rather than only at EnsureOn because the shop adds
        // ShopOffer3DEntry *after* instantiating the offer prefab
        // (ShopOfferShelfController.CreateOfferDisplay), and Unity runs Awake on
        // components even when they are disabled. A Cannon on the shelf would
        // otherwise advertise its fuse as if it were in play.
        if (GetComponent<ShopOffer3DEntry>() != null)
        {
            HideRow();
            return;
        }

        CollectActiveBadges();

        if (_active.Count == 0)
        {
            HideRow();
            return;
        }

        if (!EnsureRow())
        {
            return;
        }

        PositionRow();
        FillRow();
    }

    /// <summary>
    /// Re-reads every source. <c>GetComponents</c> into a reused list does not
    /// allocate, and it has to run every frame regardless: <see cref="FireStatus"/>
    /// is added at runtime the moment something is lit, so a set cached at Awake
    /// would never see it.
    /// </summary>
    private void CollectActiveBadges()
    {
        _active.Clear();
        GetComponents(_sources);

        foreach (IStatusBadgeSource source in _sources)
        {
            if (source.TryGetStatusBadge(out StatusBadgeInfo info))
            {
                _active.Add(info);
            }
        }

        _active.Sort(bySortOrder);
    }

    private bool EnsureRow()
    {
        if (_row != null)
        {
            if (!_row.gameObject.activeSelf)
            {
                _row.gameObject.SetActive(true);
            }

            return true;
        }

        if (_suppressed)
        {
            return false;
        }

        StatusBadgeLibrary library = StatusBadgeLibrary.Instance;
        if (library == null || library.RowPrefab == null || library.BadgePrefab == null)
        {
            // Nothing to draw with. Warn once per object rather than every frame.
            // The badge prefab is checked here too: without it the row is created and
            // stays empty, which looks like the feature silently not working.
            _suppressed = true;
            Debug.LogWarning(
                $"{name} has a status to show but StatusBadgeLibrary or its row / "
                + "badge prefab is missing. See STATUS_BADGES_SETUP.md.", this);
            return false;
        }

        _row = Instantiate(library.RowPrefab);
        _row.transform.localScale = Vector3.one * library.RowScale;
        return true;
    }

    private void HideRow()
    {
        if (_row != null && _row.gameObject.activeSelf)
        {
            _row.gameObject.SetActive(false);
        }
    }

    private void PositionRow()
    {
        StatusBadgeLibrary library = StatusBadgeLibrary.Instance;
        if (library == null)
        {
            return;
        }

        if (_camera == null)
        {
            _camera = Camera.main;
        }

        Vector3 offset = library.Offset + extraOffset;
        Vector3 position = Anchor.position;

        if (_camera != null)
        {
            Transform view = _camera.transform;

            // Camera-space placement keeps the row reading as "below" the object on
            // screen whatever angle the board is tilted at.
            position += library.OffsetInCameraSpace
                ? view.right * offset.x + view.up * offset.y + view.forward * offset.z
                : offset;

            _row.transform.rotation = view.rotation;
        }
        else
        {
            position += offset;
        }

        _row.transform.position = position;
    }

    private void FillRow()
    {
        StatusBadgeLibrary library = StatusBadgeLibrary.Instance;
        IReadOnlyList<StatusBadge> badges =
            _row.Prepare(_active.Count, library != null ? library.BadgePrefab : null);

        int count = Mathf.Min(_active.Count, badges.Count);
        for (int i = 0; i < count; i++)
        {
            StatusBadge badge = badges[i];
            if (badge != null)
            {
                badge.Apply(_active[i]);
            }
        }
    }
}
