// Generated by Claude Code (claude-opus-5) for jjmil on 2026-07-28.

using TMPro;
using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// One icon-and-number pair inside a <see cref="StatusBadgeRow"/>. Setters skip
/// redundant writes: badges are refreshed every frame but their values change
/// rarely, and assigning TMP text unconditionally would dirty the canvas on every
/// component on the board every frame.
/// </summary>
public sealed class StatusBadge : MonoBehaviour
{
    [SerializeField] private Image icon;
    [SerializeField] private TMP_Text label;

    private Sprite _currentSprite;
    private string _currentLabel;
    private Color _currentTint;
    private bool _tintApplied;

    public void Apply(in StatusBadgeInfo info)
    {
        SetSprite(info.Icon);
        SetTint(info.Tint);
        SetLabel(info.Label);
    }

    private void SetSprite(Sprite sprite)
    {
        if (icon == null || _currentSprite == sprite)
        {
            return;
        }

        _currentSprite = sprite;
        icon.sprite = sprite;
        icon.enabled = sprite != null;
    }

    private void SetTint(Color tint)
    {
        if (icon == null || (_tintApplied && _currentTint == tint))
        {
            return;
        }

        _tintApplied = true;
        _currentTint = tint;
        icon.color = tint;
    }

    private void SetLabel(string text)
    {
        if (label == null || _currentLabel == text)
        {
            return;
        }

        _currentLabel = text;
        label.text = text;
        label.enabled = !string.IsNullOrEmpty(text);
    }
}
