// Generated by Claude Code (claude-opus-5) for jjmil on 2026-07-28.

using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// The world-space container holding one object's badges side by side. Pools its
/// children rather than destroying them: Fire comes and goes several times a
/// second on a busy board, and rebuilding UI at that rate allocates hard.
/// </summary>
public sealed class StatusBadgeRow : MonoBehaviour
{
    [Tooltip("Parent for the badges. Leave empty to use this object, which is "
        + "correct when the layout group sits on the root.")]
    [SerializeField] private Transform badgeParent;

    private readonly List<StatusBadge> _badges = new List<StatusBadge>();

    private Transform BadgeParent => badgeParent != null ? badgeParent : transform;

    /// <summary>
    /// Grows the pool to <paramref name="count"/> live badges and hides the rest.
    /// Returns the live ones in order for the caller to fill.
    /// </summary>
    public IReadOnlyList<StatusBadge> Prepare(int count, StatusBadge badgePrefab)
    {
        while (_badges.Count < count && badgePrefab != null)
        {
            _badges.Add(Instantiate(badgePrefab, BadgeParent));
        }

        for (int i = 0; i < _badges.Count; i++)
        {
            StatusBadge badge = _badges[i];
            if (badge == null)
            {
                continue;
            }

            bool live = i < count;
            if (badge.gameObject.activeSelf != live)
            {
                badge.gameObject.SetActive(live);
            }
        }

        return _badges;
    }
}
