// Generated by Claude Code (claude-opus-5) for jjmil on 2026-07-28.

using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// The Detonate keyword: an explosion that activates every component in its radius.
/// The detonator is not destroyed — items that consume themselves do that on their
/// own — so a repeating source like the Bomb ball can keep going off.
///
/// Activating components rather than only scoring them is what lets one blast set
/// off another, which needs guarding. The visited set is the real safety mechanism:
/// it caps a whole cascade at "every component at most once", so breadth cannot
/// explode the way a depth limit alone would allow. The depth limit stays as a
/// backstop.
/// </summary>
public static class Detonation
{
    public const float smallRadius = 3f;
    public const float mediumRadius = 6f;
    public const float largeRadius = 12f;

    private const int maxChainDepth = 3;

    /// <summary>
    /// Detonates at <paramref name="origin"/>. <paramref name="visited"/> and
    /// <paramref name="depth"/> are threaded by chained blasts and should be left
    /// at their defaults by callers starting a new explosion.
    /// </summary>
    public static int Detonate(
        Vector3 origin,
        float radius,
        float scoreMultiplier = 1f,
        int depth = 0,
        HashSet<int> visited = null)
    {
        if (depth > maxChainDepth)
        {
            return 0;
        }

        visited ??= new HashSet<int>();

        List<BoardComponent> targets = CollectTargets(origin, radius, visited);
        if (targets.Count == 0)
        {
            return 0;
        }

        ScoreManager scoreManager = ServiceLocator.Get<ScoreManager>();
        if (scoreManager != null)
        {
            scoreManager.WithScoreMultiplier(
                scoreMultiplier, () => ActivateAll(targets));
        }
        else
        {
            ActivateAll(targets);
        }

        return targets.Count;
    }

    /// <summary>
    /// Chained detonation from inside an existing blast. Components already caught
    /// by this cascade are skipped, so a cluster of explosives resolves once.
    /// </summary>
    public static int DetonateChained(
        Vector3 origin,
        float radius,
        float scoreMultiplier,
        int depth,
        HashSet<int> visited)
    {
        return Detonate(origin, radius, scoreMultiplier, depth + 1, visited);
    }

    private static List<BoardComponent> CollectTargets(
        Vector3 origin, float radius, HashSet<int> visited)
    {
        List<BoardComponent> targets = new List<BoardComponent>();

        foreach (Collider overlap in Physics.OverlapSphere(origin, radius))
        {
            foreach (BoardComponent component in Ball.GetBoardComponentsForScoring(overlap))
            {
                if (!StatusTargeting.CanBeTargeted(component))
                {
                    continue;
                }

                if (!visited.Add(component.GetInstanceID()))
                {
                    continue;
                }

                targets.Add(component);
            }
        }

        return targets;
    }

    private static void ActivateAll(List<BoardComponent> targets)
    {
        foreach (BoardComponent component in targets)
        {
            if (component != null)
            {
                component.ActivateAsIfHit();
            }
        }
    }
}
