// Generated by Claude Code (claude-opus-5) for jjmil on 2026-07-28.

using UnityEngine;

/// <summary>
/// The Kinetic keyword: scoring that scales with the square of the ball's speed.
/// Board speeds run roughly 0.5 to 20 m/s, so 8 m/s is treated as an ordinary hit
/// at 1x, a slow roll bottoms out at 0.25x and a hard slam reaches the 8x cap.
///
/// Kinetic on a component scales by the speed of the ball that hit it; Kinetic on a
/// ball scales everything that ball hits.
/// </summary>
public static class KineticScoring
{
    private const float referenceSpeed = 8f;
    private const float exponent = 2f;
    private const float minMultiplier = 0.25f;
    private const float maxMultiplier = 8f;

    public static float Multiplier(float speed)
    {
        if (speed <= 0f)
        {
            return minMultiplier;
        }

        float raw = Mathf.Pow(speed / referenceSpeed, exponent);
        return Mathf.Clamp(raw, minMultiplier, maxMultiplier);
    }

    /// <summary>
    /// Multiplier for the ball involved in a collision. Falls back to 1x when the
    /// contact had no rigidbody, so non-ball contacts are never penalised.
    /// </summary>
    public static float MultiplierFor(Collision collision)
    {
        if (collision == null || collision.rigidbody == null)
        {
            return 1f;
        }

        return Multiplier(collision.rigidbody.linearVelocity.magnitude);
    }

    public static float MultiplierFor(Rigidbody body)
    {
        return body == null ? 1f : Multiplier(body.linearVelocity.magnitude);
    }
}
