// Generated by Cursor AI for jjmil on 2026-03-24.

/// <summary>
/// Letter ranking for a challenge mode run,
/// from D- (lowest) to S+ (highest).
/// </summary>
public enum RunRank
{
    DMinus = 0,
    D = 1,
    DPlus = 2,
    CMinus = 3,
    C = 4,
    CPlus = 5,
    BMinus = 6,
    B = 7,
    BPlus = 8,
    AMinus = 9,
    A = 10,
    APlus = 11,
    SMinus = 12,
    S = 13,
    SPlus = 14
}

/// <summary>
/// Utility methods for the run ranking system.
/// Converts scores to ranks, provides display
/// labels, star counts, and special-rank checks.
/// </summary>
public static class RunRankUtility
{
    private static readonly string[] rankLabels =
    {
        "D-", "D", "D+",
        "C-", "C", "C+",
        "B-", "B", "B+",
        "A-", "A", "A+",
        "S-", "S", "S+"
    };

    public static string GetLabel(RunRank rank)
    {
        int index = (int)rank;

        if (index < 0 || index >= rankLabels.Length)
        {
            return "?";
        }

        return rankLabels[index];
    }

    /// <summary>
    /// 1 star: D-, D, D+, C-, C, C+
    /// 2 stars: B-, B, B+, A-
    /// 3 stars: A, A+, S-, S, S+
    /// </summary>
    public static int GetStarCount(RunRank rank)
    {
        int index = (int)rank;

        if (index <= (int)RunRank.CPlus)
        {
            return 1;
        }

        if (index <= (int)RunRank.AMinus)
        {
            return 2;
        }

        return 3;
    }

    /// <summary>
    /// S and S+ receive a special highlighted
    /// star animation on the game over screen.
    /// </summary>
    public static bool IsSpecialRank(RunRank rank)
    {
        return rank == RunRank.S
            || rank == RunRank.SPlus;
    }

    /// <summary>
    /// Calculates the run rank from a score using
    /// the tier thresholds defined on the challenge.
    /// </summary>
    public static RunRank Calculate(
        long score,
        long cThreshold,
        long bThreshold,
        long aThreshold,
        long sThreshold,
        long sPlusThreshold)
    {
        if (score < cThreshold)
        {
            return SubdivideThirds(
                score, 0L, cThreshold,
                RunRank.DMinus);
        }

        if (score < bThreshold)
        {
            return SubdivideThirds(
                score, cThreshold, bThreshold,
                RunRank.CMinus);
        }

        if (score < aThreshold)
        {
            return SubdivideThirds(
                score, bThreshold, aThreshold,
                RunRank.BMinus);
        }

        if (score < sThreshold)
        {
            return SubdivideThirds(
                score, aThreshold, sThreshold,
                RunRank.AMinus);
        }

        long mid = sThreshold
            + (sPlusThreshold - sThreshold) / 2;

        if (score < mid)
        {
            return RunRank.SMinus;
        }

        if (score < sPlusThreshold)
        {
            return RunRank.S;
        }

        return RunRank.SPlus;
    }

    private static RunRank SubdivideThirds(
        long score,
        long lower,
        long upper,
        RunRank baseRank)
    {
        long range = upper - lower;

        if (range <= 0)
        {
            return baseRank;
        }

        long third = range / 3;
        long offset = score - lower;

        if (offset < third)
        {
            return baseRank;
        }

        if (offset < third * 2)
        {
            return (RunRank)((int)baseRank + 1);
        }

        return (RunRank)((int)baseRank + 2);
    }
}
