// Generated by Cursor AI (claude-4.6-opus) for jjmil on 2026-03-27.
// Updated with Cursor (Composer) on 2026-04-08: catalog element filter, visit
// offer count range, combined price multiplier on each offer.

using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Merges ball and board-component catalogs into a single pool, then randomly
/// selects offers per shop visit, weighted by item rarity (rarer items show
/// up less often). Every shop visit can offer any item type.
/// </summary>
public sealed class ShopOfferGenerator
{
    private readonly IList<BallDefinition> _allBalls;
    private readonly IList<BoardComponentDefinition> _allComponents;

    public ShopOfferGenerator(
        IList<BallDefinition> allBalls,
        IList<BoardComponentDefinition> allComponents)
    {
        _allBalls = allBalls ?? new List<BallDefinition>();
        _allComponents = allComponents ?? new List<BoardComponentDefinition>();
    }

    /// <summary>
    /// Builds a fresh list of random offers drawn from the full unlocked
    /// catalog. Items are weighted by rarity, so rarer items appear less often.
    /// Balls use their <see cref="BallRarity"/>; components (which have no
    /// rarity) are treated as <see cref="BallRarity.Common"/>.
    /// </summary>
    public List<ShopOffer> GenerateOffers(
        int minOfferCount,
        int maxOfferCount,
        float combinedPriceMultiplier)
    {
        int lo = Mathf.Min(minOfferCount, maxOfferCount);
        int hi = Mathf.Max(minOfferCount, maxOfferCount);
        lo = Mathf.Max(1, lo);
        hi = Mathf.Max(lo, hi);

        List<ShopOffer> pool = BuildUnlockedPool(combinedPriceMultiplier);

        if (pool.Count == 0)
        {
            return new List<ShopOffer>();
        }

        int target = Mathf.Clamp(
            Random.Range(lo, hi + 1),
            1,
            pool.Count);

        return WeightedSampleWithoutReplacement(pool, target);
    }

    /// <summary>
    /// Picks <paramref name="count"/> distinct offers from
    /// <paramref name="pool"/>, each remaining item's chance proportional to its
    /// rarity weight. Mutates <paramref name="pool"/> (entries are removed as
    /// they are chosen).
    /// </summary>
    private static List<ShopOffer> WeightedSampleWithoutReplacement(
        List<ShopOffer> pool,
        int count)
    {
        var chosen = new List<ShopOffer>(count);
        var weights = new List<float>(pool.Count);

        for (int i = 0; i < pool.Count; i++)
        {
            weights.Add(GetRarityWeight(pool[i]));
        }

        for (int n = 0; n < count && pool.Count > 0; n++)
        {
            float total = 0f;
            for (int i = 0; i < weights.Count; i++)
            {
                total += weights[i];
            }

            if (total <= 0f)
            {
                break;
            }

            float r = Random.value * total;
            int pick = weights.Count - 1;
            float acc = 0f;

            for (int i = 0; i < weights.Count; i++)
            {
                acc += weights[i];
                if (r <= acc)
                {
                    pick = i;
                    break;
                }
            }

            chosen.Add(pool[pick]);
            pool.RemoveAt(pick);
            weights.RemoveAt(pick);
        }

        return chosen;
    }

    /// <summary>
    /// Relative shop frequency weight for an offer based on its rarity. Balls
    /// and board components share the same <see cref="BallRarity"/> categories
    /// and weights.
    /// </summary>
    private static float GetRarityWeight(ShopOffer offer)
    {
        if (offer == null)
        {
            return 0f;
        }

        if (offer.Type == ShopOffer.OfferType.Ball)
        {
            return offer.BallDef != null
                ? RarityWeight(offer.BallDef.Rarity)
                : RarityWeight(BallRarity.Common);
        }

        return offer.ComponentDef != null
            ? RarityWeight(offer.ComponentDef.Rarity)
            : RarityWeight(BallRarity.Common);
    }

    private static float RarityWeight(BallRarity rarity)
    {
        switch (rarity)
        {
            case BallRarity.Common: return 100f;
            case BallRarity.Uncommon: return 60f;
            case BallRarity.Rare: return 30f;
            case BallRarity.Epic: return 12f;
            case BallRarity.Legendary: return 4f;
            default: return 1f;
        }
    }

    private List<ShopOffer> BuildUnlockedPool(float combinedPriceMultiplier)
    {
        var pool = new List<ShopOffer>();
        bool hasProgression = ProgressionService.Instance != null;

        for (int i = 0; i < _allBalls.Count; i++)
        {
            BallDefinition def = _allBalls[i];

            if (def == null || !def.IsValid())
            {
                continue;
            }

            if (hasProgression
                && !ProgressionService.Instance.IsBallUnlocked(def.Id))
            {
                continue;
            }

            pool.Add(new ShopOffer(def, combinedPriceMultiplier));
        }

        for (int i = 0; i < _allComponents.Count; i++)
        {
            BoardComponentDefinition def = _allComponents[i];

            if (def == null || !def.IsValid())
            {
                continue;
            }

            if (hasProgression
                && !ProgressionService.Instance.IsComponentUnlocked(def.Id))
            {
                continue;
            }

            pool.Add(new ShopOffer(def, combinedPriceMultiplier));
        }

        return pool;
    }
}

/// <summary>
/// Box–Muller visitor price multiplier, clamped to [0, 2], mean 1.
/// </summary>
public static class ShopPricingMath
{
    private const float visitorMultMin = 0f;
    private const float visitorMultMax = 2f;
    private const float visitorMultMean = 1f;

    /// <summary>
    /// Samples a multiplier in [0, 2] with mean 1 using a normal distribution
    /// (clamped). Larger sigma yields heavier tails toward 0 and 2.
    /// </summary>
    public static float SampleVisitorPriceMultiplier(float sigma)
    {
        float safeSigma = Mathf.Max(0.0001f, sigma);
        float z = SampleStandardNormal();
        float raw = visitorMultMean + safeSigma * z;

        return Mathf.Clamp(raw, visitorMultMin, visitorMultMax);
    }

    private static float SampleStandardNormal()
    {
        float u1 = Random.value;
        float u2 = Random.value;

        if (u1 <= 1e-7f)
        {
            u1 = 1e-7f;
        }

        float mag = Mathf.Sqrt(-2f * Mathf.Log(u1));
        float z0 = mag * Mathf.Cos(2f * Mathf.PI * u2);

        return z0;
    }
}

/// <summary>
/// Builds short alien-style merchant names from syllable lists.
/// </summary>
public static class AlienMerchantNameGenerator
{
    private static readonly string[] prefixes =
    {
        "Zyx", "Vor", "Keth", "Plim", "Quor", "Nex", "Thra", "Xel", "Grym", "Fyn"
    };

    private static readonly string[] cores =
    {
        "orb", "ix", "ara", "uno", "eth", "on", "ae", "ul", "is", "ek"
    };

    private static readonly string[] suffixes =
    {
        "ak", "7", "prime", "void", "flux", "9", "minor", "major", "xi", "null"
    };

    private static readonly string[] titles =
    {
        "Capt.", "Trader", "Envoy", "Broker", "Purveyor", "Vendor"
    };

    /// <summary>
    /// Returns a single randomized merchant label, e.g. "Capt. Zyxorb-ak".
    /// </summary>
    public static string Generate()
    {
        string p = prefixes[Random.Range(0, prefixes.Length)];
        string c = cores[Random.Range(0, cores.Length)];
        string s = suffixes[Random.Range(0, suffixes.Length)];
        string t = titles[Random.Range(0, titles.Length)];

        return t + " " + p + c + "-" + s;
    }
}
