// Generated by Cursor AI (claude-4.6-opus) for jjmil on 2026-03-27.
// Updated with Cursor (Composer) on 2026-04-08: catalog element filter, visit
// offer count range, combined price multiplier on each offer.

using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Merges ball and board-component catalogs into a single pool, then randomly
/// selects offers per shop visit (optionally filtered by element type).
/// </summary>
public sealed class ShopOfferGenerator
{
    private readonly IList<BallDefinition> _allBalls;
    private readonly IList<BoardComponentDefinition> _allComponents;

    public ShopOfferGenerator(
        IList<BallDefinition> allBalls,
        IList<BoardComponentDefinition> allComponents)
    {
        _allBalls = allBalls ?? new List<BallDefinition>();
        _allComponents = allComponents ?? new List<BoardComponentDefinition>();
    }

    /// <summary>
    /// Builds a fresh list of random offers. <paramref name="catalogElement"/>
    /// None = mixed pool; otherwise only matching <see cref="ElementType"/>.
    /// Falls back to mixed if the specialist pool is empty.
    /// </summary>
    public List<ShopOffer> GenerateOffers(
        ElementType catalogElement,
        int minOfferCount,
        int maxOfferCount,
        float combinedPriceMultiplier)
    {
        int lo = Mathf.Min(minOfferCount, maxOfferCount);
        int hi = Mathf.Max(minOfferCount, maxOfferCount);
        lo = Mathf.Max(1, lo);
        hi = Mathf.Max(lo, hi);

        List<ShopOffer> mixedPool = BuildUnlockedPool(combinedPriceMultiplier);

        if (mixedPool.Count == 0)
        {
            return new List<ShopOffer>();
        }

        List<ShopOffer> pool = mixedPool;

        if (catalogElement != ElementType.None)
        {
            List<ShopOffer> specialist = FilterPoolByElement(
                mixedPool, catalogElement);

            if (specialist.Count == 0)
            {
                Debug.LogWarning(
                    "[ShopOfferGenerator] No unlocked items for element " +
                    catalogElement + "; using mixed catalog.");
                pool = mixedPool;
            }
            else
            {
                pool = specialist;
            }
        }

        int target = Mathf.Clamp(
            Random.Range(lo, hi + 1),
            1,
            pool.Count);

        for (int i = 0; i < target; i++)
        {
            int j = Random.Range(i, pool.Count);
            (pool[i], pool[j]) = (pool[j], pool[i]);
        }

        return pool.GetRange(0, target);
    }

    private static List<ShopOffer> FilterPoolByElement(
        List<ShopOffer> source,
        ElementType element)
    {
        var filtered = new List<ShopOffer>();

        for (int i = 0; i < source.Count; i++)
        {
            ShopOffer o = source[i];

            if (o != null && o.ElementType == element)
            {
                filtered.Add(o);
            }
        }

        return filtered;
    }

    private List<ShopOffer> BuildUnlockedPool(float combinedPriceMultiplier)
    {
        var pool = new List<ShopOffer>();
        bool hasProgression = ProgressionService.Instance != null;

        for (int i = 0; i < _allBalls.Count; i++)
        {
            BallDefinition def = _allBalls[i];

            if (def == null || !def.IsValid())
            {
                continue;
            }

            if (hasProgression
                && !ProgressionService.Instance.IsBallUnlocked(def.Id))
            {
                continue;
            }

            pool.Add(new ShopOffer(def, combinedPriceMultiplier));
        }

        for (int i = 0; i < _allComponents.Count; i++)
        {
            BoardComponentDefinition def = _allComponents[i];

            if (def == null || !def.IsValid())
            {
                continue;
            }

            if (hasProgression
                && !ProgressionService.Instance.IsComponentUnlocked(def.Id))
            {
                continue;
            }

            pool.Add(new ShopOffer(def, combinedPriceMultiplier));
        }

        return pool;
    }
}

/// <summary>
/// Box–Muller visitor price multiplier, clamped to [0, 2], mean 1.
/// </summary>
public static class ShopPricingMath
{
    private const float visitorMultMin = 0f;
    private const float visitorMultMax = 2f;
    private const float visitorMultMean = 1f;

    /// <summary>
    /// Samples a multiplier in [0, 2] with mean 1 using a normal distribution
    /// (clamped). Larger sigma yields heavier tails toward 0 and 2.
    /// </summary>
    public static float SampleVisitorPriceMultiplier(float sigma)
    {
        float safeSigma = Mathf.Max(0.0001f, sigma);
        float z = SampleStandardNormal();
        float raw = visitorMultMean + safeSigma * z;

        return Mathf.Clamp(raw, visitorMultMin, visitorMultMax);
    }

    private static float SampleStandardNormal()
    {
        float u1 = Random.value;
        float u2 = Random.value;

        if (u1 <= 1e-7f)
        {
            u1 = 1e-7f;
        }

        float mag = Mathf.Sqrt(-2f * Mathf.Log(u1));
        float z0 = mag * Mathf.Cos(2f * Mathf.PI * u2);

        return z0;
    }
}

/// <summary>
/// Builds short alien-style merchant names from syllable lists.
/// </summary>
public static class AlienMerchantNameGenerator
{
    private static readonly string[] prefixes =
    {
        "Zyx", "Vor", "Keth", "Plim", "Quor", "Nex", "Thra", "Xel", "Grym", "Fyn"
    };

    private static readonly string[] cores =
    {
        "orb", "ix", "ara", "uno", "eth", "on", "ae", "ul", "is", "ek"
    };

    private static readonly string[] suffixes =
    {
        "ak", "7", "prime", "void", "flux", "9", "minor", "major", "xi", "null"
    };

    private static readonly string[] titles =
    {
        "Capt.", "Trader", "Envoy", "Broker", "Purveyor", "Vendor"
    };

    /// <summary>
    /// Returns a single randomized merchant label, e.g. "Capt. Zyxorb-ak".
    /// </summary>
    public static string Generate()
    {
        string p = prefixes[Random.Range(0, prefixes.Length)];
        string c = cores[Random.Range(0, cores.Length)];
        string s = suffixes[Random.Range(0, suffixes.Length)];
        string t = titles[Random.Range(0, titles.Length)];

        return t + " " + p + c + "-" + s;
    }
}
