// Generated by Cursor AI (claude-4.6-opus) for jjmil on 2026-03-27.
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Merges ball and board-component catalogs into a single pool, then randomly
/// selects 3-6 mixed <see cref="ShopOffer"/> items each time the shop opens.
/// </summary>
public sealed class ShopOfferGenerator
{
    private readonly IList<BallDefinition> _allBalls;
    private readonly IList<BoardComponentDefinition> _allComponents;

    private const int MinOffers = 3;
    private const int MaxOffers = 6;

    public ShopOfferGenerator(
        IList<BallDefinition> allBalls,
        IList<BoardComponentDefinition> allComponents)
    {
        _allBalls = allBalls ?? new List<BallDefinition>();
        _allComponents = allComponents ?? new List<BoardComponentDefinition>();
    }

    /// <summary>
    /// Builds a fresh list of random offers, filtered by progression unlocks.
    /// </summary>
    public List<ShopOffer> GenerateOffers()
    {
        List<ShopOffer> pool = BuildUnlockedPool();

        if (pool.Count == 0)
        {
            return new List<ShopOffer>();
        }

        int target = Mathf.Clamp(Random.Range(MinOffers, MaxOffers + 1), 1, pool.Count);

        // Partial Fisher-Yates shuffle to select unique offers.
        for (int i = 0; i < target; i++)
        {
            int j = Random.Range(i, pool.Count);
            (pool[i], pool[j]) = (pool[j], pool[i]);
        }

        return pool.GetRange(0, target);
    }

    private List<ShopOffer> BuildUnlockedPool()
    {
        var pool = new List<ShopOffer>();
        bool hasProgression = ProgressionService.Instance != null;

        for (int i = 0; i < _allBalls.Count; i++)
        {
            BallDefinition def = _allBalls[i];
            if (def == null || !def.IsValid())
            {
                continue;
            }

            if (hasProgression && !ProgressionService.Instance.IsBallUnlocked(def.Id))
            {
                continue;
            }

            pool.Add(new ShopOffer(def));
        }

        for (int i = 0; i < _allComponents.Count; i++)
        {
            BoardComponentDefinition def = _allComponents[i];
            if (def == null || !def.IsValid())
            {
                continue;
            }

            if (hasProgression && !ProgressionService.Instance.IsComponentUnlocked(def.Id))
            {
                continue;
            }

            pool.Add(new ShopOffer(def));
        }

        return pool;
    }
}
