// Generated by Cursor AI (claude-4.6-opus) for jjmil on 2026-03-27.
using UnityEngine;

/// <summary>
/// Lightweight wrapper that holds either a <see cref="BallDefinition"/> or a
/// <see cref="BoardComponentDefinition"/>, exposing unified accessors so the
/// shop UI can treat both item types identically.
/// </summary>
public sealed class ShopOffer
{
    public enum OfferType
    {
        Ball,
        BoardComponent
    }

    public OfferType Type { get; }
    public BallDefinition BallDef { get; }
    public BoardComponentDefinition ComponentDef { get; }

    public string DisplayName => Type == OfferType.Ball
        ? BallDef.GetSafeDisplayName()
        : ComponentDef.GetSafeDisplayName();

    public string Description => Type == OfferType.Ball
        ? BallDef.Description
        : ComponentDef.Description;

    public int Price => Type == OfferType.Ball
        ? BallDef.Price
        : (int)ComponentDef.Price;

    public Sprite Icon => Type == OfferType.Ball
        ? BallDef.Icon
        : ComponentDef.Icon;

    public GameObject Prefab => Type == OfferType.Ball
        ? BallDef.Prefab
        : ComponentDef.Prefab;

    public ElementType ElementType => Type == OfferType.Ball
        ? BallDef.ElementType
        : ComponentDef.ElementType;

    /// <summary>
    /// True when the underlying definition ScriptableObject exists.
    /// A missing prefab is allowed -- a fallback cube will be shown instead.
    /// </summary>
    public bool IsValid => Type == OfferType.Ball
        ? (BallDef != null)
        : (ComponentDef != null);

    public ShopOffer(BallDefinition ball)
    {
        Type = OfferType.Ball;
        BallDef = ball;
        ComponentDef = null;
    }

    public ShopOffer(BoardComponentDefinition component)
    {
        Type = OfferType.BoardComponent;
        BallDef = null;
        ComponentDef = component;
    }
}
