// Generated by Cursor AI (claude-4.6-opus) for jjmil on 2026-03-27.
// Updated with Cursor (Composer) on 2026-04-08: final shelf Price from base ×
// combined player + visitor multipliers.
using UnityEngine;

/// <summary>
/// Lightweight wrapper that holds either a <see cref="BallDefinition"/> or a
/// <see cref="BoardComponentDefinition"/>, exposing unified accessors so the
/// shop UI can treat both item types identically.
/// </summary>
public sealed class ShopOffer
{
    public enum OfferType
    {
        Ball,
        BoardComponent
    }

    public OfferType Type { get; }
    public BallDefinition BallDef { get; }
    public BoardComponentDefinition ComponentDef { get; }

    private readonly int _purchasePrice;

    public string DisplayName => Type == OfferType.Ball
        ? BallDef.GetSafeDisplayName()
        : ComponentDef.GetSafeDisplayName();

    public string Description => Type == OfferType.Ball
        ? BallDef.Description
        : ComponentDef.Description;

    /// <summary>
    /// Definition base price before shop multipliers (ball int, component float).
    /// </summary>
    public float BasePrice => Type == OfferType.Ball
        ? BallDef.Price
        : ComponentDef.Price;

    /// <summary>
    /// Final coins charged for this shelf slot this visit.
    /// </summary>
    public int Price => _purchasePrice;

    public Sprite Icon => Type == OfferType.Ball
        ? BallDef.Icon
        : ComponentDef.Icon;

    public GameObject Prefab => Type == OfferType.Ball
        ? BallDef.Prefab
        : ComponentDef.Prefab;

    public ElementType ElementType => Type == OfferType.Ball
        ? BallDef.ElementType
        : ComponentDef.ElementType;

    /// <summary>
    /// True when the underlying definition ScriptableObject exists.
    /// A missing prefab is allowed -- a fallback cube will be shown instead.
    /// </summary>
    public bool IsValid => Type == OfferType.Ball
        ? (BallDef != null)
        : (ComponentDef != null);

    public ShopOffer(BallDefinition ball, float combinedPriceMultiplier)
    {
        Type = OfferType.Ball;
        BallDef = ball;
        ComponentDef = null;
        _purchasePrice = ComputeFinalPrice(ball.Price, combinedPriceMultiplier);
    }

    public ShopOffer(BoardComponentDefinition component, float combinedPriceMultiplier)
    {
        Type = OfferType.BoardComponent;
        BallDef = null;
        ComponentDef = component;
        _purchasePrice = ComputeFinalPrice(component.Price, combinedPriceMultiplier);
    }

    private static int ComputeFinalPrice(float basePrice, float combinedPriceMultiplier)
    {
        float m = Mathf.Max(0f, combinedPriceMultiplier);

        return Mathf.RoundToInt(Mathf.Max(0f, basePrice * m));
    }
}
