using UnityEngine;

// Generated by Cursor AI (GPT-5.2) for jjmil on 2026-02-16.

/// <summary>
/// Attach this to a ball prefab so the prefab can be mapped back to its BallDefinition.
/// </summary>
public sealed class BallDefinitionLink : MonoBehaviour
{
    [SerializeField] private BallDefinition definition;

    public BallDefinition Definition => definition;

    public bool TryGetDefinition(out BallDefinition outDefinition)
    {
        outDefinition = definition;
        return outDefinition != null;
    }
}

