using UnityEngine;

// Generated by Cursor AI (GPT-5.2) for jjmil on 2026-02-16.

/// <summary>
/// Central source of truth for a ball's shop + UI metadata.
/// </summary>
[CreateAssetMenu(menuName = "Pinball/Ball Definition", fileName = "BallDefinition_")]
public sealed class BallDefinition : ScriptableObject
{
    [Header("Identity")]
    [Tooltip("Stable unique id for this ball (used for references and future persistence).")]
    [SerializeField] private string id = "";

    [Header("Presentation")]
    [SerializeField] private string displayName = "Ball";
    [TextArea]
    [SerializeField] private string description = "";
    [SerializeField] private BallRarity rarity = BallRarity.Common;
    [SerializeField] private Sprite icon;

    [Header("Gameplay")]
    [Tooltip("Prefab that will be spawned/used for this ball.")]
    [SerializeField] private GameObject prefab;
    [Min(0)]
    [SerializeField] private int price = 10;

    public string Id => id;
    public string DisplayName => displayName;
    public string Description => description;
    public BallRarity Rarity => rarity;
    public Sprite Icon => icon;
    public GameObject Prefab => prefab;
    public int Price => price;

    public static BallDefinition CreateRuntime(
        string runtimeId,
        string runtimeDisplayName,
        string runtimeDescription,
        BallRarity runtimeRarity,
        Sprite runtimeIcon,
        GameObject runtimePrefab,
        int runtimePrice)
    {
        var def = CreateInstance<BallDefinition>();
        def.id = runtimeId ?? "";
        def.displayName = string.IsNullOrWhiteSpace(runtimeDisplayName) ? "Ball" : runtimeDisplayName;
        def.description = runtimeDescription ?? "";
        def.rarity = runtimeRarity;
        def.icon = runtimeIcon;
        def.prefab = runtimePrefab;
        def.price = Mathf.Max(0, runtimePrice);
        return def;
    }

    public bool IsValid()
    {
        return prefab != null;
    }

    public string GetSafeDisplayName()
    {
        return string.IsNullOrWhiteSpace(displayName) ? "Ball" : displayName;
    }

    private void OnValidate()
    {
        if (string.IsNullOrWhiteSpace(displayName))
        {
            displayName = "Ball";
        }

        price = Mathf.Max(0, price);
    }
}

