// Generated by Cursor AI (GPT-5.2) for jjmil on 2026-02-16.

/// <summary>
/// Shared rarity categories for balls.
/// </summary>
public enum BallRarity
{
    Common,
    Uncommon,
    Rare,
    Epic,
    Legendary
}

