// Generated by Cursor AI (GPT-5.2) for jjmil on 2026-02-16.
// Updated by Antigravity (claude-4.6-opus) on 2026-04-06:
// added ElementType field.

using NUnit.Framework;
using UnityEngine;
using System.Collections.Generic;
#if UNITY_EDITOR
using UnityEditor;
#endif

/// <summary>
/// Central source of truth for a ball's shop + UI metadata.
/// </summary>
[CreateAssetMenu(menuName = "Pinball/Ball Definition", fileName = "BallDefinition_")]
public class BallDefinition : ScriptableObject
{
    [Header("Identity")]
    [Tooltip("Stable unique id for this ball (used for references and future persistence).")]
    [SerializeField] private string id = "";

    [Header("Presentation")]
    [SerializeField] private string displayName = "Ball";
    [TextArea]
    [SerializeField] private string description = "";
    [SerializeField] private BallRarity rarity = BallRarity.Common;
    [SerializeField] private ElementType elementType = ElementType.None;
    [SerializeField] private ElementType secondaryElementType = ElementType.None;
    [SerializeField] private List<string> tags = new List<string>();
    [SerializeField] private Sprite icon;

    [Header("Gameplay")]
    [Tooltip("Prefab that will be spawned/used for this ball.")]
    [SerializeField] private GameObject prefab;
    [Min(0)]
    [SerializeField] private int price = 10;
#if UNITY_EDITOR
    private static string tooltipPrefabPath = "/Prefabs/UI/Tooltips/Tooltip Panel";
    private static string ballSOPath = "/Resources/BallDefinitions/";
    private static string termSOPath = "/Resources/TermDefinitions/";
#endif

    public string Id => id;
    public string DisplayName => LocalizedContent.Get("ball", name, "name", displayName);
    public string Description => LocalizedContent.Get("ball", name, "desc", description);
    public BallRarity Rarity => rarity;
    public ElementType ElementType => elementType;
    public ElementType SecondaryElementType => secondaryElementType;
    public Sprite Icon => icon;
    public GameObject Prefab => prefab;
    public List<string> Tags => tags;
    public int Price => price;

    public static BallDefinition CreateRuntime(
        string runtimeId,
        string runtimeDisplayName,
        string runtimeDescription,
        BallRarity runtimeRarity,
        ElementType runtimeElementType,
        Sprite runtimeIcon,
        GameObject runtimePrefab,
        int runtimePrice)
    {
        var def = CreateInstance<BallDefinition>();
        def.id = runtimeId ?? "";
        def.displayName =
            string.IsNullOrWhiteSpace(runtimeDisplayName)
                ? "Ball"
                : runtimeDisplayName;
        def.description = runtimeDescription ?? "";
        def.rarity = runtimeRarity;
        def.elementType = runtimeElementType;
        def.icon = runtimeIcon;
        def.prefab = runtimePrefab;
        def.price = Mathf.Max(0, runtimePrice);
        return def;
    }

    public bool IsValid()
    {
        return prefab != null;
    }

    public string GetSafeDisplayName()
    {
        var localized = DisplayName;
        return string.IsNullOrWhiteSpace(localized) ? "Ball" : localized;
    }

    private void OnValidate()
    {
        if (string.IsNullOrWhiteSpace(displayName))
        {
            displayName = "Ball";
        }

        price = Mathf.Max(0, price);
    }

    public void UpdateDesc(string[] data)
    {
        displayName = data[0];
        description = data[1];
        rarity = GetBallRarity(data[2]);
        elementType = GetElementType(data[3]);
        string[] splitTags;
        if (GetElementType(data[4]) != ElementType.None)
        {
            secondaryElementType = GetElementType(data[4]);
            splitTags = data[5].Split(' ');
        } else
        {
            splitTags = data[4].Split(' ');
        }

        for (int i = 0; i < splitTags.Length; i++)
        {
            if (!string.IsNullOrWhiteSpace(splitTags[i]) && !tags.Contains(splitTags[i]))
            {
                tags.Add(splitTags[i]);
            }
        }

#if UNITY_EDITOR
        TooltipUI tooltipPrefab = AssetDatabase.LoadAssetAtPath<TooltipUI>("Assets" + tooltipPrefabPath + ".prefab");
        for (int i = 0; i < tags.Count; i++)
        {
            if (AssetDatabase.AssetPathExists("Assets" + ballSOPath + tags[i] + ".asset"))
            {
                BallDefinition ballDef = AssetDatabase.LoadAssetAtPath<BallDefinition>("Assets" + ballSOPath + tags[i] + ".asset");
                if (tooltipPrefab.necessaryBallDefinitions.Contains(ballDef))
                {
                    continue;
                }
                tooltipPrefab.necessaryBallDefinitions.Add(ballDef);
            } else if (AssetDatabase.AssetPathExists("Assets" + termSOPath + tags[i] + ".asset"))
            {
                TermDefinition termDef = AssetDatabase.LoadAssetAtPath<TermDefinition>("Assets" + termSOPath + tags[i] + ".asset");
                if (tooltipPrefab.necessaryTermDefinitions.Contains(termDef))
                {
                    continue;
                }
                tooltipPrefab.necessaryTermDefinitions.Add(termDef);
            }
        }
        EditorUtility.SetDirty(tooltipPrefab);
        AssetDatabase.SaveAssetIfDirty(tooltipPrefab);
#endif
    }

    public static ElementType GetElementType(
        string type)
    {

        ElementType fallback = type.ToLower() switch
        {
            "standard" => ElementType.Standard,
            "alteration" => ElementType.Alteration,
            "exchange" => ElementType.Exchange,
            "entropy" => ElementType.Entropy,
            "tech" => ElementType.Tech,
            "void" => ElementType.Void,
            _ => ElementType.None
        };

        return fallback;
    }

    public static BallRarity GetBallRarity(
        string type)
    {

        BallRarity fallback = type.ToLower() switch
        {
            "uncommon" => BallRarity.Uncommon,
            "rare" => BallRarity.Rare,
            "epic" => BallRarity.Epic,
            "legendary" => BallRarity.Legendary,
            _ => BallRarity.Common
        };

        return fallback;
    }
}

