using UnityEngine;

// Generated by Cursor AI (GPT-5.2) for jjmil on 2026-02-16.

/// <summary>
/// Shared helper methods for working with BallDefinitions and their prefabs.
/// </summary>
public static class BallDefinitionUtilities
{
    public static Sprite TryGetPrefabSpriteIcon(GameObject prefab)
    {
        if (prefab == null)
        {
            return null;
        }

        SpriteRenderer spriteRenderer = prefab.GetComponentInChildren<SpriteRenderer>(includeInactive: true);
        if (spriteRenderer != null)
        {
            return spriteRenderer.sprite;
        }

        return null;
    }

    public static BallDefinition TryGetDefinitionFromPrefab(GameObject prefab)
    {
        if (prefab == null)
        {
            return null;
        }

        BallDefinitionLink link = prefab.GetComponentInChildren<BallDefinitionLink>(includeInactive: true);
        if (link != null && link.Definition != null)
        {
            return link.Definition;
        }

        return null;
    }
}

