// Generated by Antigravity (claude-4.6-opus) for jjmil on 2026-04-06.

using UnityEngine;

/// <summary>
/// Maps each <see cref="ElementType"/> to its display
/// color and human-readable name. Centralised so
/// tooltips, UI, and VFX all use the same palette.
/// </summary>
public static class ElementTypeColors
{
    public static Color GetColor(ElementType type)
    {
        return type switch
        {
            ElementType.Alteration
                => new Color(0f, 0.749f, 1f),
            ElementType.Entropy
                => new Color(1f, 0.2f, 0.2f),
            ElementType.Exchange
                => new Color(0.224f, 1f, 0.078f),
            ElementType.Tech
                => new Color(1f, 0.4f, 0f),
            ElementType.Void
                => new Color(1f, 0.412f, 0.706f),
            _ => Color.white
        };
    }

    public static string GetDisplayName(
        ElementType type)
    {
        string fallback = type switch
        {
            ElementType.Standard => "Standard",
            ElementType.Alteration => "Alteration",
            ElementType.Entropy => "Entropy",
            ElementType.Exchange => "Exchange",
            ElementType.Tech => "Tech",
            ElementType.Void => "Void",
            _ => "N/A"
        };
        // Localized via Content table key element.&lt;EnumName&gt;.name; English fallback above.
        return LocalizedContent.Get("element", type.ToString(), "name", fallback);
    }

    
}
