// Generated by Antigravity (claude-4.6-opus) for jjmil on 2026-04-06.

using UnityEngine;

/// <summary>
/// Maps each <see cref="ElementType"/> to its display
/// color and human-readable name. Centralised so
/// tooltips, UI, and VFX all use the same palette.
/// </summary>
public static class ElementTypeColors
{
    public static Color GetColor(ElementType type)
    {
        return type switch
        {
            ElementType.Striker
                => new Color(0f, 0.749f, 1f),
            ElementType.Amplifier
                => new Color(1f, 0.2f, 0.2f),
            ElementType.Mint
                => new Color(0.224f, 1f, 0.078f),
            ElementType.Splitter
                => new Color(1f, 0.4f, 0f),
            ElementType.Anomaly
                => new Color(1f, 0.412f, 0.706f),
            ElementType.Catalyst
                => new Color(0.753f, 0.753f, 0.753f),
            _ => Color.white
        };
    }

    public static string GetDisplayName(
        ElementType type)
    {
        return type switch
        {
            ElementType.Striker => "Striker",
            ElementType.Amplifier => "Amplifier",
            ElementType.Mint => "Mint",
            ElementType.Splitter => "Splitter",
            ElementType.Anomaly => "Anomaly",
            ElementType.Catalyst => "Catalyst",
            _ => "N/A"
        };
    }
}
