// Generated by Cursor AI for jjmil on 2026-03-22.
// Modified by Cursor AI for jjmil on 2026-03-24.
using System;
using UnityEngine;

[Serializable]
public sealed class ProgressionTier
{
    [Tooltip(
        "Cumulative lifetime score required to unlock "
        + "this tier (score threshold).")]
    [Min(0)]
    [SerializeField] private double xpThreshold;

    [Tooltip(
        "Ball unlocked when the player reaches "
        + "this tier. Set either this or the component "
        + "reward, not both.")]
    [SerializeField] private BallDefinition rewardBall;

    [Tooltip(
        "Board component unlocked when the player "
        + "reaches this tier. Set either this or the "
        + "ball reward, not both.")]
    [SerializeField]
    private BoardComponentDefinition rewardComponent;

    [Tooltip(
        "Ship unlocked when the player reaches this "
        + "tier. Set this or the ball / component reward, "
        + "not more than one.")]
    [SerializeField]
    private PlayerShipDefinition rewardShip;

    public double XpThreshold => xpThreshold;

    public BallDefinition RewardBall => rewardBall;

    public BoardComponentDefinition RewardComponent =>
        rewardComponent;

    public PlayerShipDefinition RewardShip => rewardShip;

    public string RewardBallId =>
        rewardBall != null ? rewardBall.Id : "";

    public string RewardComponentId =>
        rewardComponent != null ? rewardComponent.Id : "";

    public string RewardShipId =>
        rewardShip != null ? rewardShip.Id : "";

    public bool HasValidReward =>
        HasValidBallReward || HasValidComponentReward
        || HasValidShipReward;

    public bool HasValidBallReward =>
        rewardBall != null && rewardBall.IsValid();

    public bool HasValidComponentReward =>
        rewardComponent != null
        && rewardComponent.IsValid();

    public bool HasValidShipReward =>
        rewardShip != null && rewardShip.IsValid();
}
