// Generated by Cursor AI for jjmil on 2026-03-22.
// Modified by Cursor AI for jjmil on 2026-03-24.
using System.Collections.Generic;
using UnityEngine;

[CreateAssetMenu(
    menuName = "Pinball/Progression Config",
    fileName = "ProgressionConfig")]
public sealed class ProgressionConfig : ScriptableObject
{
    [Header("Starter Balls")]
    [Tooltip(
        "Balls available from the very start of a new "
        + "profile. These always appear in the shop pool.")]
    [SerializeField] private List<BallDefinition> starterBalls =
        new List<BallDefinition>();

    [Header("Starter Components")]
    [Tooltip(
        "Board components available from the very start "
        + "of a new profile.")]
    [SerializeField]
    private List<BoardComponentDefinition> starterComponents =
        new List<BoardComponentDefinition>();

    [Header("Progression Tiers")]
    [Tooltip(
        "Ordered list of tiers. Each tier grants a new "
        + "ball and/or board component when the player's "
        + "lifetime score reaches the threshold.")]
    [SerializeField] private List<ProgressionTier> tiers =
        new List<ProgressionTier>();

    public IReadOnlyList<BallDefinition> StarterBalls =>
        starterBalls;

    public IReadOnlyList<BoardComponentDefinition>
        StarterComponents => starterComponents;

    public IReadOnlyList<ProgressionTier> Tiers => tiers;

    public bool IsStarterBall(string ballId)
    {
        if (string.IsNullOrEmpty(ballId))
        {
            return false;
        }

        for (int i = 0; i < starterBalls.Count; i++)
        {
            if (starterBalls[i] != null
                && starterBalls[i].Id == ballId)
            {
                return true;
            }
        }

        return false;
    }

    public bool IsStarterComponent(string componentId)
    {
        if (string.IsNullOrEmpty(componentId))
        {
            return false;
        }

        for (int i = 0; i < starterComponents.Count; i++)
        {
            if (starterComponents[i] != null
                && starterComponents[i].Id == componentId)
            {
                return true;
            }
        }

        return false;
    }

    public ProgressionTier GetTierForBallId(string ballId)
    {
        if (string.IsNullOrEmpty(ballId))
        {
            return null;
        }

        for (int i = 0; i < tiers.Count; i++)
        {
            if (tiers[i] != null
                && tiers[i].RewardBallId == ballId)
            {
                return tiers[i];
            }
        }

        return null;
    }

    public ProgressionTier GetTierForComponentId(
        string componentId)
    {
        if (string.IsNullOrEmpty(componentId))
        {
            return null;
        }

        for (int i = 0; i < tiers.Count; i++)
        {
            if (tiers[i] != null
                && tiers[i].RewardComponentId
                    == componentId)
            {
                return tiers[i];
            }
        }

        return null;
    }

    public HashSet<string> GetAllRewardBallIds()
    {
        var ids = new HashSet<string>();

        for (int i = 0; i < tiers.Count; i++)
        {
            string id = tiers[i]?.RewardBallId;

            if (!string.IsNullOrEmpty(id))
            {
                ids.Add(id);
            }
        }

        return ids;
    }

    public HashSet<string> GetAllRewardComponentIds()
    {
        var ids = new HashSet<string>();

        for (int i = 0; i < tiers.Count; i++)
        {
            string id = tiers[i]?.RewardComponentId;

            if (!string.IsNullOrEmpty(id))
            {
                ids.Add(id);
            }
        }

        return ids;
    }

    private void OnValidate()
    {
        if (tiers == null)
        {
            return;
        }

        for (int i = 0; i < tiers.Count; i++)
        {
            if (tiers[i] == null)
            {
                continue;
            }

            if (tiers[i].HasValidBallReward
                && tiers[i].HasValidComponentReward)
            {
                Debug.LogWarning(
                    $"{name}: Tier {i} has both a "
                    + "ball and a component reward. "
                    + "Each tier should have one or "
                    + "the other. The ball will be "
                    + "used.",
                    this);
            }

            if (i > 0
                && tiers[i - 1] != null
                && tiers[i].XpThreshold
                    < tiers[i - 1].XpThreshold)
            {
                Debug.LogWarning(
                    $"{name}: Tier {i} threshold "
                    + $"({tiers[i].XpThreshold}) is "
                    + $"lower than tier {i - 1} "
                    + $"({tiers[i - 1].XpThreshold})"
                    + ". Tiers should be in "
                    + "ascending order.",
                    this);
            }
        }
    }
}
