// Generated by Cursor AI for jjmil on 2026-03-22.
using System;
using UnityEngine;

[Serializable]
public sealed class ProgressionTier
{
    [Tooltip("Cumulative lifetime score required to unlock this tier.")]
    [Min(0)]
    [SerializeField] private double xpThreshold;

    [Tooltip("Ball unlocked when the player reaches this tier.")]
    [SerializeField] private BallDefinition rewardBall;

    public double XpThreshold => xpThreshold;
    public BallDefinition RewardBall => rewardBall;

    public string RewardBallId =>
        rewardBall != null ? rewardBall.Id : "";

    public bool HasValidReward =>
        rewardBall != null && rewardBall.IsValid();
}
