using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

// Generated by Cursor AI (GPT-5.2) for jjmil on 2026-02-16.

/// <summary>
/// UI entry for a single "replace this ball" slot in the shop.
/// Intended to be used as a prefab that ShopUIController instantiates.
/// </summary>
public sealed class BallReplaceSlotEntryUI : MonoBehaviour,
    IBeginDragHandler,
    IDragHandler,
    IEndDragHandler,
    IDropHandler
{
    [SerializeField] private Button button;
    [SerializeField] private TMP_Text labelText;
    [SerializeField] private Image iconImage;
    [SerializeField] private CanvasGroup canvasGroup;

    private int _slotIndex = -1;
    private ShopUIController _shop;
    private Canvas _rootCanvas;
    private float _startAlpha = 1f;
    private RectTransform _dragVisualRect;
    private CanvasGroup _dragVisualCanvasGroup;

    public void Init(ShopUIController shop, int slotIndex, string label, Sprite icon)
    {
        _shop = shop;
        _slotIndex = slotIndex;
        EnsureDragComponents();

        if (labelText != null)
        {
            labelText.text = label ?? string.Empty;
        }

        if (iconImage != null)
        {
            if (icon != null)
            {
                iconImage.enabled = true;
                iconImage.sprite = icon;
            }
            else
            {
                iconImage.enabled = false;
                iconImage.sprite = null;
            }
        }

        if (button != null)
        {
            button.onClick.RemoveListener(OnClick);
            button.onClick.AddListener(OnClick);
        }
    }

    private void OnClick()
    {
        if (_shop == null || _slotIndex < 0)
        {
            return;
        }
        _shop.ChooseReplaceSlot(_slotIndex);
    }

    private void OnDisable()
    {
        CleanupDragState();
    }

    private void OnDestroy()
    {
        CleanupDragState();
    }

    public void OnBeginDrag(PointerEventData eventData)
    {
        EnsureDragComponents();

        if (canvasGroup == null)
        {
            return;
        }

        _startAlpha = canvasGroup.alpha;
        canvasGroup.alpha = 0.35f;
        canvasGroup.blocksRaycasts = false;

        CreateDragVisualIfNeeded();
        UpdateDragVisual(eventData);
    }

    public void OnDrag(PointerEventData eventData)
    {
        if (_rootCanvas == null)
        {
            return;
        }

        UpdateDragVisual(eventData);
    }

    public void OnEndDrag(PointerEventData eventData)
    {
        CleanupDragState();
    }

    public void OnDrop(PointerEventData eventData)
    {
        if (_shop == null || eventData == null)
        {
            return;
        }

        GameObject dragged = eventData.pointerDrag;
        if (dragged == null)
        {
            return;
        }

        BallReplaceSlotEntryUI otherSlot = dragged.GetComponent<BallReplaceSlotEntryUI>();
        if (otherSlot != null && otherSlot != this)
        {
            _shop.TrySwapHandSlots(otherSlot._slotIndex, _slotIndex);
            return;
        }

        ShopBallOfferEntryUI offer = dragged.GetComponent<ShopBallOfferEntryUI>();
        if (offer != null)
        {
            _shop.TryOfferDropOntoSlot(offer.OfferIndex, _slotIndex);
        }
    }

    private void EnsureDragComponents()
    {
        if (canvasGroup == null)
        {
            canvasGroup = GetComponent<CanvasGroup>();
            if (canvasGroup == null)
            {
                canvasGroup = gameObject.AddComponent<CanvasGroup>();
            }
        }

        if (_rootCanvas == null)
        {
            _rootCanvas = GetComponentInParent<Canvas>();
        }
    }

    private void CreateDragVisualIfNeeded()
    {
        if (_dragVisualRect != null)
        {
            return;
        }

        if (_rootCanvas == null)
        {
            return;
        }

        RectTransform rootRect = _rootCanvas.transform as RectTransform;
        if (rootRect == null)
        {
            return;
        }

        var go = new GameObject($"{name}_DragVisual", typeof(RectTransform), typeof(CanvasGroup),
            typeof(Image));
        _dragVisualRect = go.GetComponent<RectTransform>();
        _dragVisualRect.SetParent(rootRect, worldPositionStays: false);

        _dragVisualCanvasGroup = go.GetComponent<CanvasGroup>();
        _dragVisualCanvasGroup.blocksRaycasts = false;
        _dragVisualCanvasGroup.interactable = false;
        _dragVisualCanvasGroup.alpha = 0.95f;

        Image img = go.GetComponent<Image>();
        if (iconImage != null)
        {
            img.sprite = iconImage.sprite;
            img.color = iconImage.color;
            img.preserveAspect = true;

            RectTransform iconRt = iconImage.rectTransform;
            _dragVisualRect.sizeDelta = iconRt.rect.size;
        }
        else
        {
            img.enabled = false;
        }
    }

    private void UpdateDragVisual(PointerEventData eventData)
    {
        if (_dragVisualRect == null || _rootCanvas == null || eventData == null)
        {
            return;
        }

        RectTransform rootRect = _rootCanvas.transform as RectTransform;
        if (rootRect == null)
        {
            return;
        }

        Camera cam = eventData.pressEventCamera;
        if (RectTransformUtility.ScreenPointToLocalPointInRectangle(
                rootRect,
                eventData.position,
                cam,
                out Vector2 local))
        {
            _dragVisualRect.anchoredPosition = local;
        }
    }

    private void DestroyDragVisual()
    {
        if (_dragVisualRect != null)
        {
            Destroy(_dragVisualRect.gameObject);
        }

        _dragVisualRect = null;
        _dragVisualCanvasGroup = null;
    }

    private void CleanupDragState()
    {
        if (canvasGroup != null)
        {
            canvasGroup.blocksRaycasts = true;
            canvasGroup.alpha = _startAlpha;
        }

        DestroyDragVisual();
    }
}

