// Generated by Cursor AI, 2025-03-12
using UnityEngine;
using UnityEngine.EventSystems;

public class ButtonTextShiftOnInteract : MonoBehaviour, IPointerEnterHandler, IPointerExitHandler, IPointerDownHandler, IPointerUpHandler, ISelectHandler, IDeselectHandler
{
    [SerializeField] private RectTransform textRect;
    [SerializeField] private float defaultOffset = -10f;
    [SerializeField] private float interactedOffset = 0f;

    private bool isHovered;
    private bool isPressed;
    private bool isSelected;

    private void Awake()
    {
        ResolveTextRect();
    }

    private void OnEnable()
    {
        isHovered = false;
        isPressed = false;
        isSelected = false;
        ResolveTextRect();
        ApplyOffset(defaultOffset);
    }

    private void OnDisable()
    {
        isHovered = false;
        isPressed = false;
        isSelected = false;
        ApplyOffset(defaultOffset);
    }

    private void ResolveTextRect()
    {
        if (textRect == null && transform.childCount > 0)
        {
            textRect = transform.GetChild(0).GetComponent<RectTransform>();
        }
    }

    private void ApplyOffset(float offset)
    {
        if (textRect == null)
        {
            return;
        }

        Vector2 offsetMax = textRect.offsetMax;
        offsetMax.y = -offset;
        textRect.offsetMax = offsetMax;
    }

    private void UpdateOffset()
    {
        float targetOffset = (isHovered || isPressed || isSelected) ? interactedOffset : defaultOffset;
        ApplyOffset(targetOffset);
    }

    public void OnSelect(BaseEventData eventData)
    {
        isSelected = true;
        UpdateOffset();
    }

    public void OnDeselect(BaseEventData eventData)
    {
        isSelected = false;
        UpdateOffset();
    }

    public void OnPointerEnter(PointerEventData eventData)
    {
        isHovered = true;
        UpdateOffset();
    }

    public void OnPointerExit(PointerEventData eventData)
    {
        isHovered = false;
        UpdateOffset();
    }

    public void OnPointerDown(PointerEventData eventData)
    {
        isPressed = true;
        UpdateOffset();
    }

    public void OnPointerUp(PointerEventData eventData)
    {
        isPressed = false;
        UpdateOffset();
    }
}
