// Generated by Cursor AI for jjmil on 2026-03-24.
using TMPro;
using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// Place on the challenge-card prefab so <see cref="MainMenuUI"/>
/// can populate it at runtime without building the card from code.
/// Wire the fields in the Inspector.
/// </summary>
public sealed class ChallengeCardUI : MonoBehaviour
{
    [Tooltip("Displays the rank / grade label (e.g. S+, A, B, C, --).")]
    public TMP_Text gradeText;

    [Tooltip("Displays the player's best score for this mode.")]
    public TMP_Text bestScoreText;

    [Tooltip("The 3 star Image components (left to right). Swapped between empty and filled sprites at runtime.")]
    public Image[] starImages = new Image[3];

    [Tooltip("Sprite used for an unfilled (grey) star.")]
    public Sprite emptyStarSprite;

    [Tooltip("Sprite used for a filled (yellow) star.")]
    public Sprite filledStarSprite;

    [Tooltip("Optional: displays the mode name. Populated at runtime.")]
    public TMP_Text nameText;
}
