// Generated by Cursor AI for jjmil on 2026-03-24.
using System.Collections;
using System.Globalization;
using TMPro;
using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// Displays the run ranking (letter grade,
/// 1-3 stars, time played, components hit)
/// on the game over screen when the player
/// dies in a challenge mode run.
/// Attach to the round-failed UI root or let
/// GameRulesManager add it automatically.
/// </summary>
public sealed class GameOverRankingDisplay
    : MonoBehaviour
{
    [Header("Star Icon Prefabs")]
    [Tooltip(
        "Prefab for a filled star. Must have "
        + "an Image component. Assign your own "
        + "sprite on the prefab's Image.")]
    [SerializeField] private GameObject
        filledStarPrefab;

    [Tooltip(
        "Prefab for an empty star. Must have "
        + "an Image component. Assign your own "
        + "sprite on the prefab's Image.")]
    [SerializeField] private GameObject
        emptyStarPrefab;

    [Header("UI References (auto-created)")]
    [SerializeField] private TMP_Text rankText;
    [SerializeField] private TMP_Text scoreText;
    [SerializeField] private TMP_Text timeText;
    [SerializeField] private TMP_Text hitsText;

    [Header("Star Instances (runtime)")]
    [SerializeField] private Image star1Image;
    [SerializeField] private Image star2Image;
    [SerializeField] private Image star3Image;

    [Header("Appearance")]
    [SerializeField] private Color
        filledStarColor =
            new Color(1f, 0.85f, 0.1f, 1f);
    [SerializeField] private Color
        emptyStarColor =
            new Color(0.35f, 0.35f, 0.35f, 0.6f);
    [SerializeField] private Color rankTextColor =
        Color.white;
    [SerializeField] private Color statLabelColor =
        new Color(0.65f, 0.65f, 0.65f, 1f);
    [SerializeField] private Color statValueColor =
        Color.white;

    [Header("Special Rank Pulse (S / S+)")]
    [SerializeField] private Color pulseHighColor =
        new Color(1f, 1f, 0.6f, 1f);
    [SerializeField] private float pulsePeriod =
        0.8f;

    [Header("Layout")]
    [SerializeField] private float starSize = 64f;
    [SerializeField] private float rankFontSize =
        48f;
    [SerializeField] private float scoreFontSize =
        24f;
    [SerializeField] private float statFontSize =
        20f;
    [SerializeField] private float starSpacing =
        20f;
    [SerializeField] private float panelWidth =
        400f;
    [SerializeField] private float panelHeight =
        280f;

    private GameObject _rankingPanel;
    private Coroutine _pulseRoutine;

    public void Show(
        long score,
        ChallengeModeDefinition challenge,
        float elapsedTime,
        int componentHits)
    {
        if (challenge == null)
        {
            return;
        }

        RunRank rank = RunRankUtility.Calculate(
            score,
            challenge.cRankThreshold,
            challenge.bRankThreshold,
            challenge.aRankThreshold,
            challenge.sRankThreshold,
            challenge.sPlusThreshold);

        EnsureRankingPanel();
        UpdateDisplay(
            rank, score, elapsedTime,
            componentHits);
    }

    public void Hide()
    {
        StopPulse();

        if (_rankingPanel != null)
        {
            _rankingPanel.SetActive(false);
        }
    }

    private void OnDisable()
    {
        StopPulse();
    }

    private void EnsureRankingPanel()
    {
        if (_rankingPanel != null)
        {
            _rankingPanel.SetActive(true);
            return;
        }

        BuildRankingPanel();
    }

    private void BuildRankingPanel()
    {
        var panel = new GameObject(
            "RankingDisplay",
            typeof(RectTransform),
            typeof(VerticalLayoutGroup),
            typeof(ContentSizeFitter));

        panel.transform.SetParent(
            transform, false);

        var panelRect =
            panel.GetComponent<RectTransform>();
        panelRect.anchorMin =
            new Vector2(0.5f, 0.65f);
        panelRect.anchorMax =
            new Vector2(0.5f, 0.65f);
        panelRect.pivot =
            new Vector2(0.5f, 0.5f);
        panelRect.sizeDelta =
            new Vector2(panelWidth, panelHeight);

        var vlg = panel
            .GetComponent<VerticalLayoutGroup>();
        vlg.childAlignment =
            TextAnchor.MiddleCenter;
        vlg.childControlWidth = true;
        vlg.childControlHeight = true;
        vlg.childForceExpandWidth = true;
        vlg.childForceExpandHeight = false;
        vlg.spacing = 8f;
        vlg.padding =
            new RectOffset(10, 10, 10, 10);

        var csf = panel
            .GetComponent<ContentSizeFitter>();
        csf.horizontalFit =
            ContentSizeFitter.FitMode
                .Unconstrained;
        csf.verticalFit =
            ContentSizeFitter.FitMode
                .PreferredSize;

        BuildStarRow(panel.transform);
        BuildRankLabel(panel.transform);
        BuildScoreLabel(panel.transform);
        BuildStatRow(
            panel.transform,
            "TimeRow", "TIME",
            out timeText);
        BuildStatRow(
            panel.transform,
            "HitsRow", "HITS",
            out hitsText);

        _rankingPanel = panel;
    }

    private void BuildStarRow(Transform parent)
    {
        var row = new GameObject(
            "StarRow",
            typeof(RectTransform),
            typeof(HorizontalLayoutGroup),
            typeof(LayoutElement));

        row.transform.SetParent(parent, false);

        var hlg = row
            .GetComponent<HorizontalLayoutGroup>();
        hlg.childAlignment =
            TextAnchor.MiddleCenter;
        hlg.childControlWidth = false;
        hlg.childControlHeight = false;
        hlg.childForceExpandWidth = false;
        hlg.childForceExpandHeight = false;
        hlg.spacing = starSpacing;

        var le = row.GetComponent<LayoutElement>();
        le.preferredHeight = starSize + 10f;

        star1Image = CreateStarSlot(
            row.transform, "Star1");
        star2Image = CreateStarSlot(
            row.transform, "Star2");
        star3Image = CreateStarSlot(
            row.transform, "Star3");
    }

    private Image CreateStarSlot(
        Transform parent, string name)
    {
        bool hasEmpty = emptyStarPrefab != null;
        bool hasFilled = filledStarPrefab != null;

        GameObject go;

        if (hasEmpty)
        {
            go = Instantiate(
                emptyStarPrefab, parent);
            go.name = name;
        }
        else
        {
            go = new GameObject(
                name,
                typeof(RectTransform),
                typeof(Image),
                typeof(LayoutElement));
            go.transform.SetParent(parent, false);

            var le =
                go.GetComponent<LayoutElement>();
            le.preferredWidth = starSize;
            le.preferredHeight = starSize;
        }

        var rect =
            go.GetComponent<RectTransform>();

        if (rect != null)
        {
            rect.sizeDelta =
                new Vector2(starSize, starSize);
        }

        var img = go.GetComponent<Image>();

        if (img == null)
        {
            img = go.AddComponent<Image>();
        }

        img.color = emptyStarColor;

        var layoutEl =
            go.GetComponent<LayoutElement>();

        if (layoutEl == null)
        {
            layoutEl =
                go.AddComponent<LayoutElement>();
        }

        layoutEl.preferredWidth = starSize;
        layoutEl.preferredHeight = starSize;

        return img;
    }

    private void BuildRankLabel(Transform parent)
    {
        var go = new GameObject(
            "RankLabel",
            typeof(RectTransform),
            typeof(TextMeshProUGUI),
            typeof(LayoutElement));

        go.transform.SetParent(parent, false);

        var le = go.GetComponent<LayoutElement>();
        le.preferredHeight = rankFontSize + 10f;

        rankText =
            go.GetComponent<TextMeshProUGUI>();
        rankText.text = "";
        rankText.fontSize = rankFontSize;
        rankText.fontStyle = FontStyles.Bold;
        rankText.alignment =
            TextAlignmentOptions.Center;
        rankText.color = rankTextColor;
        rankText.enableWordWrapping = false;
    }

    private void BuildScoreLabel(Transform parent)
    {
        var go = new GameObject(
            "ScoreLabel",
            typeof(RectTransform),
            typeof(TextMeshProUGUI),
            typeof(LayoutElement));

        go.transform.SetParent(parent, false);

        var le = go.GetComponent<LayoutElement>();
        le.preferredHeight = scoreFontSize + 6f;

        scoreText =
            go.GetComponent<TextMeshProUGUI>();
        scoreText.text = "";
        scoreText.fontSize = scoreFontSize;
        scoreText.alignment =
            TextAlignmentOptions.Center;
        scoreText.color =
            new Color(0.8f, 0.8f, 0.8f, 1f);
        scoreText.enableWordWrapping = false;
    }

    private void BuildStatRow(
        Transform parent,
        string rowName,
        string label,
        out TMP_Text valueText)
    {
        var row = new GameObject(
            rowName,
            typeof(RectTransform),
            typeof(HorizontalLayoutGroup),
            typeof(LayoutElement));

        row.transform.SetParent(parent, false);

        var hlg = row
            .GetComponent<HorizontalLayoutGroup>();
        hlg.childAlignment =
            TextAnchor.MiddleCenter;
        hlg.childControlWidth = true;
        hlg.childControlHeight = true;
        hlg.childForceExpandWidth = true;
        hlg.childForceExpandHeight = false;
        hlg.spacing = 8f;

        var rowLe =
            row.GetComponent<LayoutElement>();
        rowLe.preferredHeight =
            statFontSize + 6f;

        var labelGo = new GameObject(
            rowName + "_Label",
            typeof(RectTransform),
            typeof(TextMeshProUGUI));

        labelGo.transform.SetParent(
            row.transform, false);

        var labelTmp = labelGo
            .GetComponent<TextMeshProUGUI>();
        labelTmp.text = label;
        labelTmp.fontSize = statFontSize;
        labelTmp.fontStyle = FontStyles.Bold;
        labelTmp.alignment =
            TextAlignmentOptions.Right;
        labelTmp.color = statLabelColor;
        labelTmp.enableWordWrapping = false;

        var valueGo = new GameObject(
            rowName + "_Value",
            typeof(RectTransform),
            typeof(TextMeshProUGUI));

        valueGo.transform.SetParent(
            row.transform, false);

        var valueTmp = valueGo
            .GetComponent<TextMeshProUGUI>();
        valueTmp.text = "";
        valueTmp.fontSize = statFontSize;
        valueTmp.alignment =
            TextAlignmentOptions.Left;
        valueTmp.color = statValueColor;
        valueTmp.enableWordWrapping = false;

        valueText = valueTmp;
    }

    private void UpdateDisplay(
        RunRank rank,
        long score,
        float elapsedTime,
        int componentHits)
    {
        int stars =
            RunRankUtility.GetStarCount(rank);
        bool special =
            RunRankUtility.IsSpecialRank(rank);

        SetStar(star1Image, stars >= 1, special);
        SetStar(star2Image, stars >= 2, special);
        SetStar(star3Image, stars >= 3, special);

        if (rankText != null)
        {
            rankText.text =
                RunRankUtility.GetLabel(rank);

            rankText.color = special
                ? filledStarColor
                : rankTextColor;
        }

        if (scoreText != null)
        {
            scoreText.text =
                FormatScore(score);
        }

        if (timeText != null)
        {
            timeText.text =
                FormatTime(elapsedTime);
        }

        if (hitsText != null)
        {
            hitsText.text = componentHits
                .ToString("N0",
                    CultureInfo.InvariantCulture);
        }

        StopPulse();

        if (special && gameObject.activeInHierarchy)
        {
            _pulseRoutine =
                StartCoroutine(PulseStars());
        }
    }

    private void SetStar(
        Image star, bool filled, bool special)
    {
        if (star == null)
        {
            return;
        }

        bool hasPrefabs =
            filledStarPrefab != null
            && emptyStarPrefab != null;

        if (hasPrefabs)
        {
            SwapStarPrefab(star, filled);
        }

        if (!filled)
        {
            star.color = emptyStarColor;
            return;
        }

        star.color = special
            ? pulseHighColor
            : filledStarColor;
    }

    private void SwapStarPrefab(
        Image current, bool filled)
    {
        GameObject target = filled
            ? filledStarPrefab
            : emptyStarPrefab;

        if (target == null)
        {
            return;
        }

        var targetImg =
            target.GetComponent<Image>();

        if (targetImg == null
            || targetImg.sprite == null)
        {
            return;
        }

        current.sprite = targetImg.sprite;
    }

    private IEnumerator PulseStars()
    {
        float period = Mathf.Max(
            0.1f, pulsePeriod);

        while (true)
        {
            float t = Mathf.PingPong(
                Time.unscaledTime / period, 1f);

            Color c = Color.Lerp(
                filledStarColor,
                pulseHighColor, t);

            PulseImage(star1Image, c);
            PulseImage(star2Image, c);
            PulseImage(star3Image, c);

            if (rankText != null)
            {
                rankText.color = c;
            }

            yield return null;
        }
    }

    private void PulseImage(
        Image img, Color color)
    {
        if (img == null)
        {
            return;
        }

        if (img.color != emptyStarColor)
        {
            img.color = color;
        }
    }

    private void StopPulse()
    {
        if (_pulseRoutine != null)
        {
            StopCoroutine(_pulseRoutine);
            _pulseRoutine = null;
        }
    }

    private static string FormatScore(long value)
    {
        if (value >= 1000000L)
        {
            double m = value / 1000000.0;
            return m.ToString(
                "F1",
                CultureInfo.InvariantCulture)
                + "M";
        }

        if (value >= 10000L)
        {
            double k = value / 1000.0;
            return k.ToString(
                "F1",
                CultureInfo.InvariantCulture)
                + "K";
        }

        return value.ToString("N0",
            CultureInfo.InvariantCulture);
    }

    private static string FormatTime(
        float seconds)
    {
        if (seconds < 0f)
        {
            seconds = 0f;
        }

        int totalSeconds =
            Mathf.FloorToInt(seconds);
        int minutes = totalSeconds / 60;
        int secs = totalSeconds % 60;

        if (minutes >= 60)
        {
            int hours = minutes / 60;
            minutes %= 60;
            return string.Format(
                CultureInfo.InvariantCulture,
                "{0}:{1:D2}:{2:D2}",
                hours, minutes, secs);
        }

        return string.Format(
            CultureInfo.InvariantCulture,
            "{0}:{1:D2}",
            minutes, secs);
    }
}
