// Generated by Cursor (claude-4.6-opus) for jjmil on 2026-03-26.
// Updated: tooltip now follows the mouse cursor each frame.
// Updated 2026-03-27: screen-space center for shop confirm panel placement.
// Updated 2026-04-06 by Antigravity (claude-4.6-opus):
// added ElementType color label between title and description.
// Updated 2026-04-21: added ShowBuy/ShowSell with dedicated price panels
// so buy/sell prices render inside the prefab-authored panels instead of
// being prepended to the description string.
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using NUnit.Framework;
using System.Collections.Generic;



#if ENABLE_INPUT_SYSTEM
using UnityEngine.InputSystem;
#endif

/// <summary>
/// Attach to a tooltip panel root. Handles text content
/// and follows the mouse cursor while visible, with edge
/// clamping so the tooltip stays fully on-screen.
/// </summary>
[RequireComponent(typeof(CanvasGroup))]
public sealed class TooltipHeaderUI : MonoBehaviour
{
    public enum PriceMode
    {
        None,
        Buy,
        Sell,
    }

    [SerializeField] private TMP_Text nameText;
    [SerializeField] private TMP_Text typeText;

    [Header("Price panels")]
    [Tooltip("Child panel shown when the tooltip describes a buyable item. "
        + "Toggled on by ShowBuy, off by Show/ShowSell.")]
    [SerializeField] private GameObject descPanel;

    [Tooltip("Text inside the shop panel that renders the item cost.")]
    [SerializeField] private TMP_Text descText;

    [Header("Shop skin")]
    [Tooltip("Backgrounds for the shop-only skin; one is rolled per "
        + "visit via TooltipHeaderManager.ApplyShopSkin.")]
    [SerializeField] private List<Material> backgroundMaterials =
        new List<Material>();

    [Tooltip("Sliced sprite with the panel shape in alpha and the "
        + "neon border ring in the red channel.")]
    [SerializeField] private Sprite shopSkinSprite;

    [SerializeField] private float shopSkinAlpha = 0.85f;
    [SerializeField] private float shopSkinPpu = 4f;

    [SerializeField] private bool controllerInUse = false;
    [SerializeField] private Vector2 cachedVector;
    [SerializeField] private string defaultText = "Click to Inspect";
    [SerializeField] private string defaultBuyText = "Click to Inspect.\nDrag to Buy for: ";
    [SerializeField] private string defaultSellText = "Click to Inspect.\nDrag to Sell for: ";

    private RectTransform _rect;
    private Canvas _rootCanvas;
    private RectTransform _canvasRect;
    private CanvasGroup _canvasGroup;

    private const float cursorOffsetY = 40f;
    private const float screenEdgePadding = 12f;


    private void Awake()
    {
        // The prefab accidentally carries a TooltipHeaderUI on each child price
        // panel. Disable nested instances so they don't self-hide in Awake
        // or fight the root for mouse-positioning in LateUpdate.
        if (HasAncestorTooltipHeaderUI())
        {
            enabled = false;
            return;
        }

        _rect = GetComponent<RectTransform>();
        _canvasGroup = GetComponent<CanvasGroup>();
        _canvasGroup.blocksRaycasts = false;
        CacheCanvas();
        gameObject.SetActive(false);
    }

    private void LateUpdate()
    {
        if (!controllerInUse)
        {
            PositionAtMouse();
        }
        else
        {
            _rect.anchoredPosition = cachedVector;
        }
    }

    public void Show(
        string title,
        ElementType elementType = ElementType.None,
        ElementType secondaryElementType = ElementType.None)
    {
        ApplyContent(title, elementType, secondaryElementType);
        SetDescPanel(PriceMode.None, 0);

        gameObject.SetActive(true);
        _rect.SetAsLastSibling();

        LayoutRebuilder.ForceRebuildLayoutImmediate(
            _rect);
        PositionAtMouse();
        controllerInUse = false;
    }

    public void ShowBuy(
        string title,
        ElementType elementType = ElementType.None,
        ElementType secondaryElementType = ElementType.None,
        int price = 0)
    {
        Show(title, elementType, secondaryElementType);
        SetDescPanel(PriceMode.Buy, price);
    }

    public void ShowSell(
        string title,
        ElementType elementType = ElementType.None,
        ElementType secondaryElementType = ElementType.None,
        int price = 0)
    {
        Show(title, elementType, secondaryElementType);
        SetDescPanel(PriceMode.Sell, price);
    }

    public void ShowAtPosition(string title, Vector2 position, ElementType elementType = ElementType.None, ElementType secondaryElementType = ElementType.None)
    {
        ApplyContent(title, elementType, secondaryElementType);
        SetDescPanel(PriceMode.None, 0);

        gameObject.SetActive(true);
        _rect.SetAsLastSibling();

        LayoutRebuilder.ForceRebuildLayoutImmediate(_rect);

        RectTransformUtility.ScreenPointToLocalPointInRectangle(
                _canvasRect,
                position,
                _rootCanvas.renderMode == RenderMode.ScreenSpaceOverlay ? null : _rootCanvas.worldCamera,
                out Vector2 localPos);


        Vector2 tooltipSize = _rect.rect.size;
        localPos.y +=
            cursorOffsetY
            + tooltipSize.y * (1f - _rect.pivot.y);
        Vector2 canvasSize = _canvasRect.rect.size;
        Vector2 halfCanvas = canvasSize * 0.5f;

        float minX =
            -halfCanvas.x + screenEdgePadding
            + tooltipSize.x * _rect.pivot.x;

        float maxX =
            halfCanvas.x - screenEdgePadding
            - tooltipSize.x * (1f - _rect.pivot.x);

        float minY =
            -halfCanvas.y + screenEdgePadding
            + tooltipSize.y * _rect.pivot.y;

        float maxY =
            halfCanvas.y - screenEdgePadding
            - tooltipSize.y * (1f - _rect.pivot.y);

        localPos.x = Mathf.Clamp(localPos.x, minX, maxX);
        localPos.y = Mathf.Clamp(localPos.y, minY, maxY);

        _rect.anchoredPosition = localPos;
        cachedVector = localPos;
        controllerInUse = true;
    }

    public void ShowBuyAtPosition(
        string title,
        Vector2 position,
        ElementType elementType = ElementType.None,
        ElementType secondaryElementType = ElementType.None,
        int price = 0)
    {
        ShowAtPosition(title, position, elementType, secondaryElementType);
        SetDescPanel(PriceMode.Buy, price);
    }

    public void ShowSellAtPosition(
        string title,
        Vector2 position,
        ElementType elementType = ElementType.None,
        ElementType secondaryElementType = ElementType.None,
        int price = 0)
    {
        ShowAtPosition(title, position, elementType, secondaryElementType);
        SetDescPanel(PriceMode.Sell, price);
    }


    public void Hide()
    {
        if (gameObject.activeSelf)
        {
            gameObject.SetActive(false);
        }
    }

    // Shop-only skin; reverted on shop close so other screens keep the
    // prefab's original look. Same roll modulo count on tooltip and
    // header keeps both panels on the same theme for a given visit.
    public void ApplyShopSkin(int roll)
    {
        if (backgroundMaterials.Count == 0 || shopSkinSprite == null)
        {
            return;
        }

        CaptureDefaultSkinIfNeeded();

        Material mat =
            backgroundMaterials[Mathf.Abs(roll) % backgroundMaterials.Count];

        SkinImage(GetComponent<Image>(), mat);
        SkinImage(descPanel == null
            ? null
            : descPanel.GetComponent<Image>(), mat);
    }

    public void ApplyDefaultSkin()
    {
        if (!_defaultSkinCaptured)
        {
            return;
        }

        foreach (var entry in _defaultImageStates)
        {
            Image image = entry.Key;
            if (image == null)
            {
                continue;
            }

            DefaultImageState state = entry.Value;
            image.material = state.material;
            image.sprite = state.sprite;
            image.color = state.color;
            image.type = state.type;
            image.pixelsPerUnitMultiplier = state.pixelsPerUnitMultiplier;
        }
    }

    private struct DefaultImageState
    {
        public Material material;
        public Sprite sprite;
        public Color color;
        public Image.Type type;
        public float pixelsPerUnitMultiplier;
    }

    private readonly Dictionary<Image, DefaultImageState>
        _defaultImageStates = new Dictionary<Image, DefaultImageState>();
    private bool _defaultSkinCaptured;

    private void CaptureDefaultSkinIfNeeded()
    {
        if (_defaultSkinCaptured)
        {
            return;
        }

        _defaultSkinCaptured = true;

        CaptureImageDefault(GetComponent<Image>());
        CaptureImageDefault(descPanel == null
            ? null
            : descPanel.GetComponent<Image>());
    }

    private void CaptureImageDefault(Image image)
    {
        if (image == null || _defaultImageStates.ContainsKey(image))
        {
            return;
        }

        _defaultImageStates[image] = new DefaultImageState
        {
            material = image.material,
            sprite = image.sprite,
            color = image.color,
            type = image.type,
            pixelsPerUnitMultiplier = image.pixelsPerUnitMultiplier,
        };
    }

    private void SkinImage(Image image, Material mat)
    {
        if (image == null)
        {
            return;
        }

        image.material = mat;
        image.sprite = shopSkinSprite;
        image.type = Image.Type.Sliced;
        image.pixelsPerUnitMultiplier = shopSkinPpu;
        image.color = new Color(1f, 1f, 1f, shopSkinAlpha);
    }

    public bool IsVisible => gameObject.activeSelf;

    /// <summary>
    /// Center of the tooltip rect in screen pixels (bottom-left origin).
    /// Used to align other UI (e.g. shop confirm) with the hover tooltip.
    /// </summary>
    public bool TryGetScreenRectCenterInScreenSpace(
        out Vector2 screenCenter)
    {
        screenCenter = default;

        if (!IsVisible || _rect == null)
        {
            return false;
        }

        if (_canvasRect == null)
        {
            CacheCanvas();
        }

        if (_canvasRect == null || _rootCanvas == null)
        {
            return false;
        }

        Camera cam =
            _rootCanvas.renderMode
                == RenderMode.ScreenSpaceOverlay
                ? null
                : _rootCanvas.worldCamera;

        Vector3[] corners = new Vector3[4];
        _rect.GetWorldCorners(corners);
        Vector2 a =
            RectTransformUtility.WorldToScreenPoint(
                cam, corners[0]);
        Vector2 b =
            RectTransformUtility.WorldToScreenPoint(
                cam, corners[2]);
        screenCenter = (a + b) * 0.5f;

        return true;
    }

    public void AssignReferences(
        TMP_Text name,
        TMP_Text type)
    {
        nameText = name;
        typeText = type;
    }

    private void ApplyContent(
        string title,
        ElementType elementType = ElementType.None,
        ElementType secondaryElementType = ElementType.None)
    {
        if (nameText == null)
        {
            return;
        }

        nameText.text = title;

        if (typeText != null)
        {
            string typeName = ElementTypeColors.GetDisplayName(elementType);
            Color typeColor =
                ElementTypeColors.GetColor(elementType);
            typeText.text = $"<color=#{ColorUtility.ToHtmlStringRGB(typeColor)}><u>" + typeName + "</u></color>";
            if (secondaryElementType != ElementType.None)
            {
                string secondaryTypeName = ElementTypeColors.GetDisplayName(secondaryElementType);
                Color secondaryTypeColor =
                    ElementTypeColors.GetColor(secondaryElementType);
                typeText.text += $" <color=#{ColorUtility.ToHtmlStringRGB(secondaryTypeColor)}><u>" + secondaryTypeName + "</u></color>";
            }
        }
    }

    private void SetDescPanel(PriceMode mode, int price)
    {
        descPanel.SetActive(true);

        if (mode == PriceMode.Buy && descText != null)
        {
            descText.text = defaultBuyText + $"${price}";
        }
        else if (mode == PriceMode.Sell && descText != null)
        {
            descText.text = defaultSellText + $"${price}";
        }
        else if (descText != null)
        {
            descText.text = defaultText;
        }
    }

    private bool HasAncestorTooltipHeaderUI()
    {
        Transform parent = transform.parent;
        while (parent != null)
        {
            if (parent.GetComponent<TooltipHeaderUI>() != null)
            {
                return true;
            }
            parent = parent.parent;
        }
        return false;
    }

    private void CacheCanvas()
    {
        _rootCanvas = GetComponentInParent<Canvas>();

        if (_rootCanvas != null)
        {
            _rootCanvas = _rootCanvas.rootCanvas;
            _canvasRect =
                _rootCanvas.GetComponent<RectTransform>();
        }
    }

    private void PositionAtMouse()
    {
        if (_canvasRect == null)
        {
            CacheCanvas();
        }

        if (_canvasRect == null)
        {
            return;
        }

        Vector2 screenPos = GetMouseScreenPos();

        RectTransformUtility
            .ScreenPointToLocalPointInRectangle(
                _canvasRect,
                screenPos,
                _rootCanvas.renderMode
                    == RenderMode.ScreenSpaceOverlay
                    ? null
                    : _rootCanvas.worldCamera,
                out Vector2 localPos);

        Vector2 tooltipSize = _rect.rect.size;
        localPos.y +=
            cursorOffsetY
            + tooltipSize.y * (1f - _rect.pivot.y);
        Vector2 canvasSize = _canvasRect.rect.size;
        Vector2 halfCanvas = canvasSize * 0.5f;

        float minX =
            -halfCanvas.x + screenEdgePadding
            + tooltipSize.x * _rect.pivot.x;

        float maxX =
            halfCanvas.x - screenEdgePadding
            - tooltipSize.x * (1f - _rect.pivot.x);

        float minY =
            -halfCanvas.y + screenEdgePadding
            + tooltipSize.y * _rect.pivot.y;

        float maxY =
            halfCanvas.y - screenEdgePadding
            - tooltipSize.y * (1f - _rect.pivot.y);

        localPos.x = Mathf.Clamp(localPos.x, minX, maxX);
        localPos.y = Mathf.Clamp(localPos.y, minY, maxY);

        _rect.anchoredPosition = localPos;
    }

    private static Vector2 GetMouseScreenPos()
    {
#if ENABLE_INPUT_SYSTEM
        var mouse = Mouse.current;

        if (mouse != null)
        {
            return mouse.position.ReadValue();
        }

        return Vector2.zero;
#else
        return Input.mousePosition;
#endif
    }
}