// Generated by Cursor AI for jjmil on 2026-03-24.
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

/// <summary>
/// Drives the battle-pass-style progression track UI.
/// Attach to the Progression panel in the main menu scene.
/// Reads tier data from <see cref="ProgressionConfig"/> and
/// unlock / score state from <see cref="ProgressionService"/>.
/// </summary>
public sealed class ProgressionScreenController
    : MonoBehaviour
{
    [Header("Config")]
    [Tooltip(
        "Progression config asset. Falls back to "
        + "ProgressionService.Config if left null.")]
    [SerializeField] private ProgressionConfig config;

    [Header("Score Header")]
    [Tooltip(
        "Text that displays the player's lifetime "
        + "score total.")]
    [SerializeField] private TMP_Text xpTotalText;

    [Tooltip("Text showing progress toward the next unlock.")]
    [SerializeField] private TMP_Text nextUnlockText;

    [Header("Track")]
    [Tooltip(
        "ScrollRect that contains the tier track. "
        + "Auto-created if left null.")]
    [SerializeField] private ScrollRect trackScrollRect;

    [Tooltip(
        "Content transform inside the scroll view where "
        + "tier nodes are instantiated. Auto-created if "
        + "left null.")]
    [SerializeField] private RectTransform trackContent;

    [Header("Tier Node Prefab (optional)")]
    [Tooltip(
        "If set, instantiated per tier. Must have "
        + "children named Icon (Image), Name (TMP_Text), "
        + "Threshold (TMP_Text), Lock (GameObject), and "
        + "ProgressFill (Image). If left null nodes are "
        + "built in code.")]
    [SerializeField] private GameObject tierNodePrefab;

    [Header("Appearance")]
    [SerializeField] private float nodeWidth = 160f;
    [SerializeField] private float nodeHeight = 200f;
    [SerializeField] private Color unlockedColor =
        new Color(0.2f, 0.75f, 0.35f, 1f);
    [SerializeField] private Color lockedColor =
        new Color(0.35f, 0.35f, 0.35f, 1f);
    [SerializeField] private Color progressBarBgColor =
        new Color(0.2f, 0.2f, 0.2f, 1f);
    [SerializeField] private Color progressBarFillColor =
        new Color(0.95f, 0.75f, 0.15f, 1f);

    [Header("Timeline")]
    [SerializeField] private float connectorWidth = 40f;
    [SerializeField] private float timelineHeight = 8f;
    [SerializeField] private float timelineDotSize = 24f;
    [SerializeField] private float timelineGap = 15f;

    private readonly List<TierNodeRefs> _nodeRefs =
        new List<TierNodeRefs>();

    private readonly List<ConnectorRefs> _connectors =
        new List<ConnectorRefs>();

    private static Sprite _circleSprite;

    private GameObject _lastSelected;
    private int _selectedNodeIndex = -1;

    private sealed class TierNodeRefs
    {
        public RectTransform root;
        public Image cardBg;
        public Button cardButton;
        public Image iconImage;
        public TMP_Text nameText;
        public TMP_Text thresholdText;
        public GameObject lockOverlay;
        public Image progressFill;
        public Image timelineDot;
        public Image timelineBarFill;
        public BallDefinition ball;
        public BoardComponentDefinition component;
        public bool isStarter;
        public double nodeThreshold;
        public double nodePrevThreshold;
    }

    private sealed class ConnectorRefs
    {
        public GameObject root;
        public Image fill;
    }

    private void OnEnable()
    {
        Refresh();
    }

    public void Refresh()
    {
        EnsureConfig();
        EnsureTrackLayout();
        RebuildNodes();
        UpdateNodeStates();
        UpdateHeaderTexts();
        SetupGamepadNavigation();
        SelectInitialNode();
    }

    private void Update()
    {
        TrackSelectionForTooltip();
    }

    private void EnsureConfig()
    {
        if (config != null)
        {
            return;
        }

        if (ProgressionService.Instance != null)
        {
            config = ProgressionService.Instance.Config;
        }
    }

    private void EnsureTrackLayout()
    {
        if (trackScrollRect != null
            && trackContent != null)
        {
            return;
        }

        if (trackScrollRect == null)
        {
            trackScrollRect =
                GetComponentInChildren<ScrollRect>(true);
        }

        if (trackScrollRect == null)
        {
            var scrollGo = new GameObject(
                "TrackScroll",
                typeof(RectTransform),
                typeof(ScrollRect),
                typeof(Image),
                typeof(Mask));

            scrollGo.transform.SetParent(
                transform, false);

            var scrollRect =
                scrollGo.GetComponent<RectTransform>();
            scrollRect.anchorMin =
                new Vector2(0f, 0.05f);
            scrollRect.anchorMax =
                new Vector2(1f, 0.7f);
            scrollRect.offsetMin =
                new Vector2(40f, 0f);
            scrollRect.offsetMax =
                new Vector2(-40f, 0f);

            var scrollBg =
                scrollGo.GetComponent<Image>();
            scrollBg.color =
                new Color(0.1f, 0.1f, 0.1f, 0.6f);

            var mask = scrollGo.GetComponent<Mask>();
            mask.showMaskGraphic = true;

            trackScrollRect =
                scrollGo.GetComponent<ScrollRect>();
            trackScrollRect.horizontal = true;
            trackScrollRect.vertical = false;
            trackScrollRect.movementType =
                ScrollRect.MovementType.Elastic;

            var viewportGo = new GameObject(
                "Viewport",
                typeof(RectTransform));

            viewportGo.transform.SetParent(
                scrollGo.transform, false);

            var vpRect =
                viewportGo.GetComponent<RectTransform>();
            vpRect.anchorMin = Vector2.zero;
            vpRect.anchorMax = Vector2.one;
            vpRect.offsetMin = Vector2.zero;
            vpRect.offsetMax = Vector2.zero;

            trackScrollRect.viewport = vpRect;
        }

        if (trackContent == null)
        {
            var contentGo = new GameObject(
                "Content",
                typeof(RectTransform),
                typeof(HorizontalLayoutGroup),
                typeof(ContentSizeFitter));

            Transform parent =
                trackScrollRect.viewport != null
                    ? trackScrollRect.viewport
                    : trackScrollRect.transform;

            contentGo.transform.SetParent(parent, false);

            trackContent =
                contentGo.GetComponent<RectTransform>();
            trackContent.anchorMin =
                new Vector2(0f, 0f);
            trackContent.anchorMax =
                new Vector2(0f, 1f);
            trackContent.pivot =
                new Vector2(0f, 0.5f);
            trackContent.offsetMin = Vector2.zero;
            trackContent.offsetMax = Vector2.zero;

            var hlg = contentGo
                .GetComponent<HorizontalLayoutGroup>();
            hlg.childAlignment = TextAnchor.MiddleLeft;
            hlg.childControlWidth = false;
            hlg.childControlHeight = false;
            hlg.childForceExpandWidth = false;
            hlg.childForceExpandHeight = false;
            hlg.spacing = 0f;
            hlg.padding =
                new RectOffset(20, 20, 10, 10);

            var csf = contentGo
                .GetComponent<ContentSizeFitter>();
            csf.horizontalFit =
                ContentSizeFitter.FitMode.PreferredSize;
            csf.verticalFit =
                ContentSizeFitter.FitMode.Unconstrained;

            trackScrollRect.content = trackContent;
        }
    }

    private void RebuildNodes()
    {
        _lastSelected = null;
        _selectedNodeIndex = -1;

        for (int i = _nodeRefs.Count - 1; i >= 0; i--)
        {
            if (_nodeRefs[i].root != null)
            {
                Destroy(_nodeRefs[i].root.gameObject);
            }
        }

        _nodeRefs.Clear();

        for (int i = _connectors.Count - 1; i >= 0; i--)
        {
            if (_connectors[i].root != null)
            {
                Destroy(_connectors[i].root);
            }
        }

        _connectors.Clear();

        if (config == null)
        {
            return;
        }

        int totalNodes = 0;
        var starters = config.StarterBalls;

        for (int i = 0; i < starters.Count; i++)
        {
            if (starters[i] == null)
            {
                continue;
            }

            if (totalNodes > 0)
            {
                _connectors.Add(BuildConnector());
            }

            var node = BuildNode(
                starters[i].GetSafeDisplayName(),
                starters[i].Icon,
                0d,
                isStarter: true);

            node.ball = starters[i];
            node.isStarter = true;
            _nodeRefs.Add(node);
            AttachTooltipEvents(node);
            totalNodes++;
        }

        var starterComps = config.StarterComponents;

        for (int i = 0; i < starterComps.Count; i++)
        {
            if (starterComps[i] == null)
            {
                continue;
            }

            if (totalNodes > 0)
            {
                _connectors.Add(BuildConnector());
            }

            var node = BuildNode(
                starterComps[i].GetSafeDisplayName(),
                starterComps[i].Icon,
                0d,
                isStarter: true);

            node.component = starterComps[i];
            node.isStarter = true;
            _nodeRefs.Add(node);
            AttachTooltipEvents(node);
            totalNodes++;
        }

        var tiers = config.Tiers;
        double prevThreshold = 0d;

        for (int i = 0; i < tiers.Count; i++)
        {
            if (tiers[i] == null || !tiers[i].HasValidReward)
            {
                continue;
            }

            double threshold = tiers[i].XpThreshold;

            if (totalNodes > 0)
            {
                _connectors.Add(BuildConnector());
            }

            if (tiers[i].HasValidBallReward)
            {
                var ball = tiers[i].RewardBall;

                var node = BuildNode(
                    ball.GetSafeDisplayName(),
                    ball.Icon,
                    threshold,
                    isStarter: false);

                node.ball = ball;
                node.isStarter = false;
                node.nodeThreshold = threshold;
                node.nodePrevThreshold = prevThreshold;
                _nodeRefs.Add(node);
                AttachTooltipEvents(node);
                totalNodes++;
            }
            else if (tiers[i].HasValidComponentReward)
            {
                var comp = tiers[i].RewardComponent;

                var node = BuildNode(
                    comp.GetSafeDisplayName(),
                    comp.Icon,
                    threshold,
                    isStarter: false);

                node.component = comp;
                node.isStarter = false;
                node.nodeThreshold = threshold;
                node.nodePrevThreshold = prevThreshold;
                _nodeRefs.Add(node);
                AttachTooltipEvents(node);
                totalNodes++;
            }

            prevThreshold = threshold;
        }
    }

    private TierNodeRefs BuildNode(
        string displayName,
        Sprite icon,
        double xpThreshold,
        bool isStarter)
    {
        if (tierNodePrefab != null)
        {
            return BuildNodeFromPrefab(
                displayName, icon,
                xpThreshold, isStarter);
        }

        return BuildNodeFromCode(
            displayName, icon,
            xpThreshold, isStarter);
    }

    private TierNodeRefs BuildNodeFromPrefab(
        string displayName,
        Sprite icon,
        double xpThreshold,
        bool isStarter)
    {
        var go = Instantiate(tierNodePrefab, trackContent);
        var refs = new TierNodeRefs
        {
            root = go.GetComponent<RectTransform>()
        };

        var images =
            go.GetComponentsInChildren<Image>(true);

        for (int i = 0; i < images.Length; i++)
        {
            if (images[i].gameObject.name == "Icon")
            {
                refs.iconImage = images[i];
            }
            else if (images[i].gameObject.name
                == "ProgressFill")
            {
                refs.progressFill = images[i];
            }
        }

        var texts =
            go.GetComponentsInChildren<TMP_Text>(true);

        for (int i = 0; i < texts.Length; i++)
        {
            if (texts[i].gameObject.name == "Name")
            {
                refs.nameText = texts[i];
            }
            else if (texts[i].gameObject.name
                == "Threshold")
            {
                refs.thresholdText = texts[i];
            }
        }

        var lockT = go.transform.Find("Lock");

        if (lockT != null)
        {
            refs.lockOverlay = lockT.gameObject;
        }

        var btn = go.GetComponentInChildren<Button>();

        if (btn == null)
        {
            var img = go.GetComponent<Image>();

            if (img == null)
            {
                img = go.AddComponent<Image>();
                img.color = Color.clear;
            }

            btn = go.AddComponent<Button>();
            btn.transition =
                Selectable.Transition.None;
            btn.targetGraphic = img;
        }

        refs.cardButton = btn;

        if (go.GetComponent<ControllerFocusHighlight>()
            == null)
        {
            go.AddComponent<ControllerFocusHighlight>();
        }

        ApplyNodeData(
            refs, displayName, icon,
            xpThreshold, isStarter);

        return refs;
    }

    private TierNodeRefs BuildNodeFromCode(
        string displayName,
        Sprite icon,
        double xpThreshold,
        bool isStarter)
    {
        float totalH =
            nodeHeight + timelineGap + timelineDotSize;

        var nodeGo = new GameObject(
            "TierNode_" + displayName,
            typeof(RectTransform),
            typeof(LayoutElement));

        nodeGo.transform.SetParent(trackContent, false);

        var nodeRect =
            nodeGo.GetComponent<RectTransform>();
        nodeRect.sizeDelta =
            new Vector2(nodeWidth, totalH);

        var le = nodeGo.GetComponent<LayoutElement>();
        le.preferredWidth = nodeWidth;
        le.preferredHeight = totalH;

        var refs = new TierNodeRefs { root = nodeRect };

        var cardBgGo = new GameObject(
            "CardBg",
            typeof(RectTransform),
            typeof(Image));

        cardBgGo.transform.SetParent(
            nodeGo.transform, false);

        var cardBgRect =
            cardBgGo.GetComponent<RectTransform>();
        cardBgRect.anchorMin = new Vector2(0f, 1f);
        cardBgRect.anchorMax = new Vector2(1f, 1f);
        cardBgRect.pivot = new Vector2(0.5f, 1f);
        cardBgRect.sizeDelta =
            new Vector2(0f, nodeHeight);

        refs.cardBg = cardBgGo.GetComponent<Image>();
        refs.cardBg.color = lockedColor;

        var cardBtn = cardBgGo.AddComponent<Button>();
        cardBtn.transition =
            Selectable.Transition.None;
        cardBtn.targetGraphic = refs.cardBg;
        refs.cardButton = cardBtn;
        cardBgGo
            .AddComponent<ControllerFocusHighlight>();

        float iconSize = nodeWidth * 0.55f;
        var iconGo = new GameObject(
            "Icon",
            typeof(RectTransform),
            typeof(Image));

        iconGo.transform.SetParent(
            cardBgGo.transform, false);

        var iconRect =
            iconGo.GetComponent<RectTransform>();
        iconRect.anchorMin = new Vector2(0.5f, 1f);
        iconRect.anchorMax = new Vector2(0.5f, 1f);
        iconRect.pivot = new Vector2(0.5f, 1f);
        iconRect.anchoredPosition =
            new Vector2(0f, -12f);
        iconRect.sizeDelta =
            new Vector2(iconSize, iconSize);

        refs.iconImage = iconGo.GetComponent<Image>();

        refs.nameText = CreateNodeText(
            cardBgGo.transform,
            "Name",
            new Vector2(0.5f, 0.35f),
            18f);

        refs.thresholdText = CreateNodeText(
            cardBgGo.transform,
            "Threshold",
            new Vector2(0.5f, 0.18f),
            14f);

        var lockGo = new GameObject(
            "Lock",
            typeof(RectTransform),
            typeof(Image));

        lockGo.transform.SetParent(
            cardBgGo.transform, false);

        var lockRect =
            lockGo.GetComponent<RectTransform>();
        lockRect.anchorMin = Vector2.zero;
        lockRect.anchorMax = Vector2.one;
        lockRect.offsetMin = Vector2.zero;
        lockRect.offsetMax = Vector2.zero;

        lockGo.GetComponent<Image>().color =
            new Color(0f, 0f, 0f, 0.55f);

        var lockLabel = new GameObject(
            "LockLabel",
            typeof(RectTransform),
            typeof(TextMeshProUGUI));

        lockLabel.transform.SetParent(
            lockGo.transform, false);

        var llRect =
            lockLabel.GetComponent<RectTransform>();
        llRect.anchorMin = Vector2.zero;
        llRect.anchorMax = Vector2.one;
        llRect.offsetMin = Vector2.zero;
        llRect.offsetMax = Vector2.zero;

        var llText =
            lockLabel.GetComponent<TextMeshProUGUI>();
        llText.text = "LOCKED";
        llText.fontSize = 22f;
        llText.alignment =
            TextAlignmentOptions.Center;
        llText.color = Color.white;

        refs.lockOverlay = lockGo;

        float tlBarBottomY =
            (timelineDotSize - timelineHeight) / 2f;

        var tlBarBg = new GameObject(
            "TimelineBg",
            typeof(RectTransform),
            typeof(Image));

        tlBarBg.transform.SetParent(
            nodeGo.transform, false);

        var tlBgRect =
            tlBarBg.GetComponent<RectTransform>();
        tlBgRect.anchorMin = new Vector2(0f, 0f);
        tlBgRect.anchorMax = new Vector2(1f, 0f);
        tlBgRect.pivot = new Vector2(0.5f, 0f);
        tlBgRect.sizeDelta =
            new Vector2(0f, timelineHeight);
        tlBgRect.anchoredPosition =
            new Vector2(0f, tlBarBottomY);

        tlBarBg.GetComponent<Image>().color =
            progressBarBgColor;

        var tlFillGo = new GameObject(
            "TimelineFill",
            typeof(RectTransform),
            typeof(Image));

        tlFillGo.transform.SetParent(
            tlBarBg.transform, false);

        var tlFillRect =
            tlFillGo.GetComponent<RectTransform>();
        tlFillRect.anchorMin = Vector2.zero;
        tlFillRect.anchorMax =
            new Vector2(0f, 1f);
        tlFillRect.offsetMin = Vector2.zero;
        tlFillRect.offsetMax = Vector2.zero;

        refs.timelineBarFill =
            tlFillGo.GetComponent<Image>();
        refs.timelineBarFill.color =
            progressBarFillColor;

        var dotGo = new GameObject(
            "TimelineDot",
            typeof(RectTransform),
            typeof(Image));

        dotGo.transform.SetParent(
            nodeGo.transform, false);

        var dotRect =
            dotGo.GetComponent<RectTransform>();
        dotRect.anchorMin = new Vector2(0.5f, 0f);
        dotRect.anchorMax = new Vector2(0.5f, 0f);
        dotRect.pivot = new Vector2(0.5f, 0f);
        dotRect.sizeDelta = new Vector2(
            timelineDotSize, timelineDotSize);
        dotRect.anchoredPosition = Vector2.zero;

        refs.timelineDot =
            dotGo.GetComponent<Image>();
        refs.timelineDot.sprite = GetCircleSprite();
        refs.timelineDot.color = progressBarFillColor;

        ApplyNodeData(
            refs, displayName, icon,
            xpThreshold, isStarter);

        return refs;
    }

    private static TMP_Text CreateNodeText(
        Transform parent,
        string name,
        Vector2 anchorCenter,
        float fontSize)
    {
        var go = new GameObject(
            name,
            typeof(RectTransform),
            typeof(TextMeshProUGUI));

        go.transform.SetParent(parent, false);

        var rect = go.GetComponent<RectTransform>();
        rect.anchorMin =
            new Vector2(0f, anchorCenter.y - 0.06f);
        rect.anchorMax =
            new Vector2(1f, anchorCenter.y + 0.06f);
        rect.offsetMin = new Vector2(4f, 0f);
        rect.offsetMax = new Vector2(-4f, 0f);

        var text =
            go.GetComponent<TextMeshProUGUI>();
        text.fontSize = fontSize;
        text.alignment =
            TextAlignmentOptions.Center;
        text.color = Color.white;
        text.textWrappingMode =
            TextWrappingModes.NoWrap;
        text.overflowMode =
            TextOverflowModes.Ellipsis;

        return text;
    }

    private ConnectorRefs BuildConnector()
    {
        float totalH =
            nodeHeight + timelineGap + timelineDotSize;

        var go = new GameObject(
            "Connector",
            typeof(RectTransform),
            typeof(LayoutElement));

        go.transform.SetParent(trackContent, false);

        var rect = go.GetComponent<RectTransform>();
        rect.sizeDelta =
            new Vector2(connectorWidth, totalH);

        var le = go.GetComponent<LayoutElement>();
        le.preferredWidth = connectorWidth;
        le.preferredHeight = totalH;

        float tlBarBottomY =
            (timelineDotSize - timelineHeight) / 2f;

        var barBg = new GameObject(
            "ConnectorBg",
            typeof(RectTransform),
            typeof(Image));

        barBg.transform.SetParent(
            go.transform, false);

        var bgRect =
            barBg.GetComponent<RectTransform>();
        bgRect.anchorMin = new Vector2(0f, 0f);
        bgRect.anchorMax = new Vector2(1f, 0f);
        bgRect.pivot = new Vector2(0.5f, 0f);
        bgRect.sizeDelta =
            new Vector2(0f, timelineHeight);
        bgRect.anchoredPosition =
            new Vector2(0f, tlBarBottomY);

        barBg.GetComponent<Image>().color =
            progressBarBgColor;

        var fillGo = new GameObject(
            "ConnectorFill",
            typeof(RectTransform),
            typeof(Image));

        fillGo.transform.SetParent(
            barBg.transform, false);

        var fillRect =
            fillGo.GetComponent<RectTransform>();
        fillRect.anchorMin = Vector2.zero;
        fillRect.anchorMax = new Vector2(0f, 1f);
        fillRect.offsetMin = Vector2.zero;
        fillRect.offsetMax = Vector2.zero;

        var fillImg = fillGo.GetComponent<Image>();
        fillImg.color = progressBarFillColor;

        return new ConnectorRefs
        {
            root = go,
            fill = fillImg
        };
    }

    private static Sprite GetCircleSprite()
    {
        if (_circleSprite != null)
        {
            return _circleSprite;
        }

        const int size = 64;
        var tex = new Texture2D(
            size, size, TextureFormat.RGBA32, false);

        float center = size / 2f;
        float radius = center - 1f;

        for (int y = 0; y < size; y++)
        {
            for (int x = 0; x < size; x++)
            {
                float dist = Vector2.Distance(
                    new Vector2(x, y),
                    new Vector2(center, center));

                float a =
                    Mathf.Clamp01(radius - dist);

                tex.SetPixel(
                    x, y, new Color(1f, 1f, 1f, a));
            }
        }

        tex.Apply();

        _circleSprite = Sprite.Create(
            tex,
            new Rect(0, 0, size, size),
            new Vector2(0.5f, 0.5f));

        return _circleSprite;
    }

    private static void ApplyNodeData(
        TierNodeRefs refs,
        string displayName,
        Sprite icon,
        double xpThreshold,
        bool isStarter)
    {
        if (refs.iconImage != null && icon != null)
        {
            refs.iconImage.sprite = icon;
        }

        if (refs.nameText != null)
        {
            refs.nameText.text = displayName;
        }

        if (refs.thresholdText != null)
        {
            refs.thresholdText.text = isStarter
                ? "Starter"
                : FormatXp(xpThreshold);
        }
    }

    private void UpdateNodeStates()
    {
        if (config == null)
        {
            return;
        }

        double xp =
            ProgressionService.Instance != null
                ? ProgressionService.Instance
                    .GetCurrentXp()
                : 0d;

        for (int i = 0; i < _nodeRefs.Count; i++)
        {
            var refs = _nodeRefs[i];
            bool unlocked = refs.isStarter
                || xp >= refs.nodeThreshold;

            if (refs.lockOverlay != null)
            {
                refs.lockOverlay.SetActive(!unlocked);
            }

            var bg = refs.cardBg != null
                ? refs.cardBg
                : refs.root.GetComponent<Image>();

            if (bg != null)
            {
                bg.color = unlocked
                    ? unlockedColor
                    : lockedColor;
            }

            if (refs.progressFill != null)
            {
                float fill;

                if (refs.isStarter || unlocked)
                {
                    fill = 1f;
                }
                else
                {
                    double range =
                        refs.nodeThreshold
                        - refs.nodePrevThreshold;

                    fill = range > 0d
                        ? Mathf.Clamp01(
                            (float)(
                                (xp
                                    - refs
                                        .nodePrevThreshold)
                                / range))
                        : 0f;
                }

                refs.progressFill
                    .rectTransform.anchorMax =
                    new Vector2(fill, 1f);
            }

            if (refs.timelineBarFill != null)
            {
                float nodeFill =
                    (refs.isStarter || unlocked)
                        ? 1f
                        : 0f;

                refs.timelineBarFill
                    .rectTransform.anchorMax =
                    new Vector2(nodeFill, 1f);
            }

            if (refs.timelineDot != null)
            {
                refs.timelineDot.color =
                    (refs.isStarter || unlocked)
                        ? progressBarFillColor
                        : progressBarBgColor;
            }
        }

        for (int c = 0; c < _connectors.Count; c++)
        {
            if (_connectors[c].fill == null)
            {
                continue;
            }

            int nextIdx = c + 1;
            float connFill = 0f;

            if (nextIdx < _nodeRefs.Count)
            {
                var next = _nodeRefs[nextIdx];

                if (next.isStarter)
                {
                    connFill = 1f;
                }
                else
                {
                    double threshold =
                        next.nodeThreshold;

                    if (xp >= threshold)
                    {
                        connFill = 1f;
                    }
                    else
                    {
                        double prev =
                            next.nodePrevThreshold;

                        double range =
                            threshold - prev;

                        connFill = range > 0d
                            ? Mathf.Clamp01(
                                (float)(
                                    (xp - prev)
                                    / range))
                            : 0f;
                    }
                }
            }

            _connectors[c].fill
                .rectTransform.anchorMax =
                new Vector2(connFill, 1f);
        }
    }

    private void UpdateHeaderTexts()
    {
        double xp =
            ProgressionService.Instance != null
                ? ProgressionService.Instance
                    .GetCurrentXp()
                : 0d;

        if (xpTotalText != null)
        {
            xpTotalText.text =
                $"Total Score Earned: {FormatXp(xp)}";
        }

        if (nextUnlockText != null)
        {
            ProgressionTier next =
                ProgressionService.Instance != null
                    ? ProgressionService.Instance
                        .GetNextLockedTier()
                    : null;

            if (next != null && next.HasValidReward)
            {
                double remaining =
                    next.XpThreshold - xp;

                string rewardName =
                    GetTierRewardName(next);

                nextUnlockText.text =
                    $"Next: {rewardName}"
                    + $" in {FormatXp(remaining)}";
            }
            else
            {
                nextUnlockText.text =
                    "All rewards unlocked!";
            }
        }
    }

    private static string GetTierRewardName(
        ProgressionTier tier)
    {
        if (tier.HasValidBallReward)
        {
            return tier.RewardBall
                .GetSafeDisplayName();
        }

        if (tier.HasValidComponentReward)
        {
            return tier.RewardComponent
                .GetSafeDisplayName();
        }

        return "Unknown";
    }

    private void SetupGamepadNavigation()
    {
        for (int i = 0; i < _nodeRefs.Count; i++)
        {
            var button = _nodeRefs[i].cardButton;

            if (button == null)
            {
                continue;
            }

            var nav = new Navigation
            {
                mode = Navigation.Mode.Explicit
            };

            if (i > 0)
            {
                nav.selectOnLeft =
                    _nodeRefs[i - 1].cardButton;
            }

            if (i < _nodeRefs.Count - 1)
            {
                nav.selectOnRight =
                    _nodeRefs[i + 1].cardButton;
            }

            button.navigation = nav;
        }
    }

    private void SelectInitialNode()
    {
        if (_nodeRefs.Count == 0
            || EventSystem.current == null)
        {
            return;
        }

        int selectIndex = 0;

        for (int i = 0; i < _nodeRefs.Count; i++)
        {
            if (_nodeRefs[i].lockOverlay != null
                && _nodeRefs[i].lockOverlay.activeSelf)
            {
                selectIndex = Mathf.Max(0, i - 1);
                break;
            }

            selectIndex = i;
        }

        if (_nodeRefs[selectIndex].cardButton != null)
        {
            EventSystem.current
                .SetSelectedGameObject(
                    _nodeRefs[selectIndex]
                        .cardButton.gameObject);
        }

        ScrollToNode(selectIndex);
    }

    private void TrackSelectionForTooltip()
    {
        if (EventSystem.current == null)
        {
            return;
        }

        var selected = EventSystem.current
            .currentSelectedGameObject;

        if (selected == _lastSelected)
        {
            return;
        }

        _lastSelected = selected;

        for (int i = 0; i < _nodeRefs.Count; i++)
        {
            if (_nodeRefs[i].cardButton != null
                && _nodeRefs[i].cardButton.gameObject
                    == selected)
            {
                _selectedNodeIndex = i;
                ShowTooltip(_nodeRefs[i]);
                ScrollToNode(i);
                return;
            }
        }

        if (_selectedNodeIndex >= 0)
        {
            _selectedNodeIndex = -1;
            HideTooltip();
        }
    }

    private void ScrollToNode(int index)
    {
        if (trackScrollRect == null
            || _nodeRefs.Count == 0)
        {
            return;
        }

        if (index < 0 || index >= _nodeRefs.Count)
        {
            return;
        }

        Canvas.ForceUpdateCanvases();

        RectTransform viewportRect =
            trackScrollRect.viewport != null
                ? trackScrollRect.viewport
                : trackScrollRect
                    .GetComponent<RectTransform>();

        float contentWidth =
            trackContent.rect.width;

        float viewportWidth =
            viewportRect.rect.width;

        if (contentWidth <= viewportWidth)
        {
            return;
        }

        float nodeX =
            _nodeRefs[index].root.localPosition.x
            + _nodeRefs[index].root.rect.width * 0.5f;

        float targetX =
            nodeX - viewportWidth * 0.5f;

        float maxScroll =
            contentWidth - viewportWidth;

        trackScrollRect
            .horizontalNormalizedPosition =
            Mathf.Clamp01(targetX / maxScroll);
    }

    private void AttachTooltipEvents(TierNodeRefs node)
    {
        var trigger = node.root.gameObject
            .AddComponent<EventTrigger>();

        var enterEntry = new EventTrigger.Entry
        {
            eventID = EventTriggerType.PointerEnter
        };

        enterEntry.callback.AddListener(_ =>
            ShowTooltip(node));

        var exitEntry = new EventTrigger.Entry
        {
            eventID = EventTriggerType.PointerExit
        };

        exitEntry.callback.AddListener(_ =>
            HideTooltip());

        trigger.triggers.Add(enterEntry);
        trigger.triggers.Add(exitEntry);
    }

    private void ShowTooltip(TierNodeRefs node)
    {
        string title = null;
        string desc = null;

        if (node.ball != null)
        {
            title = node.ball.GetSafeDisplayName();
            desc = node.ball.Description;
        }
        else if (node.component != null)
        {
            title =
                node.component.GetSafeDisplayName();
            desc = node.component.Description;
        }

        if (title == null)
        {
            return;
        }

        TooltipManager.Show(title, desc);
    }

    private void HideTooltip()
    {
        TooltipManager.Hide();
    }

    private static string FormatXp(double value)
    {
        if (value >= 1_000_000d)
        {
            return $"{value / 1_000_000d:F1}M";
        }

        if (value >= 1_000d)
        {
            return $"{value / 1_000d:F1}K";
        }

        return $"{value:N0}";
    }
}
