// Generated by Cursor AI for jjmil on 2026-03-24.
using System.Globalization;
using TMPro;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

/// <summary>
/// Attach to the round-failed prefab root.
/// Wire up all child references in the Inspector
/// so nothing needs to be built by code.
/// <see cref="GameRulesManager"/> calls
/// <see cref="Show"/> when the round ends.
/// </summary>
[DisallowMultipleComponent]
public sealed class RoundFailedPanelController
    : MonoBehaviour
{
    [Header("Title")]
    [SerializeField] private TMP_Text titleText;

    [Header("Run Stats")]
    [Tooltip("Displays the player's total score.")]
    [SerializeField] private TMP_Text scoreText;

    [Tooltip("Displays the level the player reached.")]
    [SerializeField] private TMP_Text levelText;

    [Tooltip("Displays total elapsed run time.")]
    [SerializeField] private TMP_Text timeText;

    [Header("Stars / Rank")]
    [Tooltip(
        "The 3 star Image components "
        + "(left to right). Swapped between "
        + "empty and filled sprites at runtime.")]
    [SerializeField] private Image[] starImages =
        new Image[3];

    [Tooltip("Sprite used for an unfilled star.")]
    [SerializeField] private Sprite emptyStarSprite;

    [Tooltip("Sprite used for a filled star.")]
    [SerializeField] private Sprite filledStarSprite;

    [Tooltip(
        "Displays the rank / grade label "
        + "(e.g. S+, A, B, C, --).")]
    [SerializeField] private TMP_Text gradeText;

    [Header("Star Colors")]
    [SerializeField] private Color filledStarColor =
        new Color(1f, 0.85f, 0.1f, 1f);

    [SerializeField] private Color emptyStarColor =
        new Color(0.35f, 0.35f, 0.35f, 0.6f);

    [Header("Stars Root (optional)")]
    [Tooltip(
        "Parent object of the stars row. "
        + "Hidden when no challenge is active.")]
    [SerializeField] private GameObject starsRoot;

    [Header("Buttons")]
    [Tooltip(
        "Calls RetryRound on GameRulesManager.")]
    [SerializeField] private Button retryButton;

    [Tooltip("Returns to the main menu scene.")]
    [SerializeField] private Button quitButton;

    [Header("Scene")]
    [SerializeField] private string
        mainMenuSceneName = "MainMenu";

    [Header("Defaults")]
    [SerializeField] private string defaultTitle =
        "ROUND FAILED";

    private GameRulesManager _rules;
    private bool _buttonsWired;

    /// <summary>
    /// Populate every text field, show the panel,
    /// and display stars / rank when a challenge
    /// is active. Called by
    /// <see cref="GameRulesManager"/>.
    /// </summary>
    public void Show(
        float score,
        float goal,
        int level,
        int ballsRemaining,
        int coins,
        float elapsedTime,
        ChallengeModeDefinition challenge)
    {
        gameObject.SetActive(true);
        WireButtons();

        if (titleText != null)
        {
            titleText.text = defaultTitle;
        }

        if (scoreText != null)
        {
            scoreText.text = FormatScore(score);
        }

        if (levelText != null)
        {
            levelText.text = (level + 1).ToString(
                CultureInfo.InvariantCulture);
        }

        if (timeText != null)
        {
            timeText.text = FormatTime(elapsedTime);
        }

        UpdateStars(score, challenge);
    }

    /// <summary>
    /// Hides the panel.
    /// </summary>
    public void Hide()
    {
        gameObject.SetActive(false);
    }

    private void UpdateStars(
        float score,
        ChallengeModeDefinition challenge)
    {
        bool hasChallenge = challenge != null;

        if (starsRoot != null)
        {
            starsRoot.SetActive(hasChallenge);
        }

        if (!hasChallenge)
        {
            if (gradeText != null)
            {
                gradeText.text = "--";
            }

            SetAllStarsEmpty();
            return;
        }

        long rounded = (long)System.Math.Round(
            System.Math.Max(0f, score));

        RunRank rank = RunRankUtility.Calculate(
            rounded,
            challenge.cRankThreshold,
            challenge.bRankThreshold,
            challenge.aRankThreshold,
            challenge.sRankThreshold,
            challenge.sPlusThreshold);

        int starCount =
            RunRankUtility.GetStarCount(rank);

        if (gradeText != null)
        {
            gradeText.text =
                RunRankUtility.GetLabel(rank);
        }

        for (int i = 0;
            i < starImages.Length;
            i++)
        {
            if (starImages[i] == null)
            {
                continue;
            }

            bool filled = i < starCount;

            starImages[i].sprite = filled
                ? filledStarSprite
                : emptyStarSprite;

            starImages[i].color = filled
                ? filledStarColor
                : emptyStarColor;
        }
    }

    private void SetAllStarsEmpty()
    {
        for (int i = 0;
            i < starImages.Length;
            i++)
        {
            if (starImages[i] == null)
            {
                continue;
            }

            starImages[i].sprite = emptyStarSprite;
            starImages[i].color = emptyStarColor;
        }
    }

    private void WireButtons()
    {
        if (_buttonsWired)
        {
            return;
        }

        _buttonsWired = true;

        if (retryButton != null)
        {
            retryButton.onClick.AddListener(
                OnRetryPressed);
        }

        if (quitButton != null)
        {
            quitButton.onClick.AddListener(
                OnQuitPressed);
        }
    }

    private void OnRetryPressed()
    {
        ResolveRules();

        if (_rules != null)
        {
            _rules.RetryRound();
        }
    }

    private void OnQuitPressed()
    {
        if (ProgressionService.Instance != null)
        {
            ProgressionService.Instance
                .CheckAndGrantUnlocks();
        }

        if (string.IsNullOrWhiteSpace(
            mainMenuSceneName))
        {
            return;
        }

        SceneManager.LoadScene(mainMenuSceneName);
    }

    private void ResolveRules()
    {
        if (_rules != null)
        {
            return;
        }

        _rules = FindFirstObjectByType<
            GameRulesManager>();
    }

    private static string FormatScore(float value)
    {
        int whole = Mathf.CeilToInt(value);
        double d = whole;

        if (d >= 1_000_000d)
        {
            return (d / 1_000_000d).ToString(
                "F1", CultureInfo.InvariantCulture)
                + "M";
        }

        if (d >= 1_000d)
        {
            return (d / 1_000d).ToString(
                "F1", CultureInfo.InvariantCulture)
                + "K";
        }

        return whole.ToString(
            "N0", CultureInfo.InvariantCulture);
    }

    private static string FormatTime(float seconds)
    {
        if (seconds < 0f)
        {
            seconds = 0f;
        }

        int totalMinutes =
            Mathf.FloorToInt(seconds / 60f);
        int hours = totalMinutes / 60;
        int minutes = totalMinutes % 60;

        return string.Format(
            CultureInfo.InvariantCulture,
            "{0}:{1:D2}",
            hours, minutes);
    }
}
