// Generated by Antigravity on 2026-03-29
// Updated with Cursor (Composer) on 2026-04-08: merchant visit roll (name,
// catalog element, visitor price mult), offer count range, optional title TMP.
// Updated 2026-04-08: merchant name uses TooltipManager via
// ShopMerchantTooltipHover (IPointerEnter/Exit).
using System.Collections;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;

/// <summary>
/// Controls the visual spaceship that flies in/out during shop transitions.
/// Listens to ShopTransitionController and moves to the active ShopShipMarker.
/// </summary>
public class ShopShipController : MonoBehaviour
{
    public event System.Action SpaceshipParked;
    public event System.Action SpaceshipDeparting;

    [Header("Visuals")]
    [Tooltip("List of possible spaceship visual objects. One will be picked at random.")]
    [SerializeField] private List<GameObject> spaceshipModels;

    [Header("Animation Settings")]
    [SerializeField] private float flyDuration = 0.55f;
    [SerializeField] private AnimationCurve flyEase = AnimationCurve.EaseInOut(0f, 0f, 1f, 1f);
    
    [Header("Bobbing Settings")]
    [SerializeField] private float bobSpeed = 2f;
    [SerializeField] private float bobHeight = 0.2f;

    [Header("Merchant visit (rolled each FlyIn)")]
    [Tooltip("Random element each visit; None = mixed catalog. If empty, all " +
        "element types including None are eligible.")]
    [SerializeField]
    private ElementType[] merchantElementPool;

    [Tooltip("Minimum number of shelf offers for this shop ship.")]
    [SerializeField]
    [Min(1)]
    private int minOffers = 3;

    [Tooltip("Maximum number of shelf offers for this shop ship.")]
    [SerializeField]
    [Min(1)]
    private int maxOffers = 6;

    [Tooltip("Spread of visitor price multiplier around 1 (normal, clamped 0–2).")]
    [SerializeField]
    private float visitorPriceSigma = 0.35f;

    [Tooltip("Visiting merchant name. Raycast target is enabled for " +
        "TooltipManager hover (catalog, prices, offer count).")]
    [SerializeField]
    private TMP_Text merchantNameLabel;

    private ShopTransitionController _transitionController;
    private Coroutine _flyRoutine;

    private bool _isParked = false;
    private float _bobTime = 0f;
    private Vector3 _parkedBasePos;
    private Quaternion _rotationCorrection = Quaternion.identity;

    private string _currentMerchantDisplayName = "";
    private ElementType _currentCatalogElement = ElementType.None;
    private float _currentVisitorPriceMultiplier = 1f;

    public string CurrentMerchantDisplayName => _currentMerchantDisplayName;

    public ElementType CurrentCatalogElement => _currentCatalogElement;

    public float CurrentVisitorPriceMultiplier => _currentVisitorPriceMultiplier;

    public int MinOffers => minOffers;

    public int MaxOffers => maxOffers;

    public bool IsParked => _isParked;

    private void Start()
    {
        // Move far away initially so it's not visible at 0,0,0 if the board isn't fully loaded yet.
        transform.position = new Vector3(0, -9999f, 0);

        PickRandomShip();
        RollMerchantVisit();
        EnsureMerchantTooltipHover();
        SnapToOffscreen();

        _transitionController = ServiceLocator.Get<ShopTransitionController>();
        if (_transitionController == null)
        {
            _transitionController =
                UnityEngine.Object.FindFirstObjectByType<ShopTransitionController>();
        }

        if (_transitionController != null)
        {
            _transitionController.OpenTransitionStarted += OnOpenStarted;
            _transitionController.CloseTransitionStarted += OnCloseStarted;
        }
    }

    private void OnDestroy()
    {
        if (_transitionController != null)
        {
            _transitionController.OpenTransitionStarted -= OnOpenStarted;
            _transitionController.CloseTransitionStarted -= OnCloseStarted;
        }
    }

    private void Update()
    {
        if (_isParked && _activeShipInstance != null)
        {
            _bobTime += Time.deltaTime;
            float offsetY = Mathf.Sin(_bobTime * bobSpeed) * bobHeight;
            transform.position = _parkedBasePos + new Vector3(0, offsetY, 0);
        }
    }

    private GameObject _activeShipInstance;

    private void PickRandomShip()
    {
        if (spaceshipModels == null || spaceshipModels.Count == 0) return;

        // If the user dragged scene children into the array, disable them all first
        foreach (var model in spaceshipModels)
        {
            if (model != null && model.scene.IsValid()) 
            {
                model.SetActive(false);
            }
        }

        if (_activeShipInstance != null && !spaceshipModels.Contains(_activeShipInstance))
        {
            Destroy(_activeShipInstance);
        }
        _activeShipInstance = null;

        int index = Random.Range(0, spaceshipModels.Count);
        GameObject prefabOrInstance = spaceshipModels[index];

        if (prefabOrInstance != null)
        {
            if (prefabOrInstance.scene.IsValid())
            {
                // The user assigned an object already in the scene.
                prefabOrInstance.SetActive(true);
                prefabOrInstance.transform.localRotation = Quaternion.identity;
                _activeShipInstance = prefabOrInstance;
            }
            else
            {
                // The user assigned a project prefab. Instantiate it.
                _activeShipInstance = Instantiate(prefabOrInstance, transform);
                _activeShipInstance.transform.localPosition = Vector3.zero;
                _activeShipInstance.transform.localRotation = Quaternion.identity;
            }

            if (_activeShipInstance != null)
            {
                Outline outline = _activeShipInstance.GetComponent<Outline>();
                if (outline == null)
                {
                    outline = _activeShipInstance.AddComponent<Outline>();
                    outline.OutlineMode = Outline.Mode.OutlineAll;
                }
                outline.enabled = true;
                outline.OutlineColor = Color.black;
                outline.OutlineWidth = 10f;
                // Offset queue to draw over the board/skybox so black is visible
                outline.RenderQueueOffset = 100;
            }
        }

        UpdateRotationCorrection();
    }

    private void RollMerchantVisit()
    {
        _currentMerchantDisplayName = AlienMerchantNameGenerator.Generate();
        _currentCatalogElement = PickRandomCatalogElement();
        _currentVisitorPriceMultiplier =
            ShopPricingMath.SampleVisitorPriceMultiplier(visitorPriceSigma);

        if (merchantNameLabel != null)
        {
            merchantNameLabel.text = _currentMerchantDisplayName;
        }

        EnsureMerchantTooltipHover();
    }

    private void EnsureMerchantTooltipHover()
    {
        if (merchantNameLabel == null)
        {
            return;
        }

        merchantNameLabel.raycastTarget = true;

        ShopMerchantTooltipHover hover =
            merchantNameLabel.GetComponent<ShopMerchantTooltipHover>();

        if (hover == null)
        {
            hover = merchantNameLabel.gameObject
                .AddComponent<ShopMerchantTooltipHover>();
        }

        hover.Bind(this);
    }

    private ElementType PickRandomCatalogElement()
    {
        if (merchantElementPool != null && merchantElementPool.Length > 0)
        {
            int i = Random.Range(0, merchantElementPool.Length);

            return merchantElementPool[i];
        }

        ElementType[] all = (ElementType[])System.Enum.GetValues(
            typeof(ElementType));
        int j = Random.Range(0, all.Length);

        return all[j];
    }

    private void UpdateRotationCorrection()
    {
        _rotationCorrection = Quaternion.identity;
        if (_activeShipInstance == null) return;

        // Try to find BoidShip to get the forward indicator
        BoidShip boid = _activeShipInstance.GetComponentInChildren<BoidShip>();
        Transform indicator = null;
        if (boid != null)
        {
            indicator = boid.ForwardIndicator;
        }
        else
        {
            // Fallback: search for a child named "Forward"
            indicator = _activeShipInstance.transform.Find("Forward");
        }

        if (indicator != null)
        {
            // Calculate local forward of the indicator relative to the model root
            // We transform the indicator's forward vector into the model root's local space.
            Vector3 localForward = _activeShipInstance.transform.InverseTransformDirection(indicator.forward);
            _rotationCorrection = Quaternion.FromToRotation(localForward, Vector3.forward);
        }
    }

    private void SnapToOffscreen()
    {
        var marker = ServiceLocator.Get<ShopShipMarker>();
        if (marker != null && marker.offscreenTransform != null)
        {
            transform.position = marker.offscreenTransform.position;
            transform.rotation = marker.offscreenTransform.rotation;
        }
    }

    private void OnOpenStarted()
    {
        FlyIn();
    }

    private void OnCloseStarted()
    {
        FlyOut();
    }

    public void FlyIn(System.Action onComplete = null)
    {
        PickRandomShip();
        RollMerchantVisit();
        _isParked = false;

        var marker = ServiceLocator.Get<ShopShipMarker>();
        if (marker == null || marker.offscreenTransform == null || marker.parkTransform == null)
        {
            SpaceshipParked?.Invoke();
            onComplete?.Invoke();
            return;
        }

        if (_flyRoutine != null) StopCoroutine(_flyRoutine);
        _flyRoutine = StartCoroutine(FlyRoutine(marker.offscreenTransform.position, marker.parkTransform.position, marker.offscreenTransform.rotation, true, onComplete));
    }

    public void FlyOut(System.Action onComplete = null)
    {
        _isParked = false;
        SpaceshipDeparting?.Invoke();
        ServiceLocator.Get<AudioManager>()?.PlayAlienDeparture();

        var marker = ServiceLocator.Get<ShopShipMarker>();
        if (marker == null || marker.offscreenTransform == null || marker.parkTransform == null)
        {
            onComplete?.Invoke();
            return;
        }

        Transform exitTransform = marker.exitOffscreenTransform != null ? marker.exitOffscreenTransform : marker.offscreenTransform;
        
        if (_flyRoutine != null) StopCoroutine(_flyRoutine);
        _flyRoutine = StartCoroutine(FlyRoutine(transform.position, exitTransform.position, transform.rotation, false, onComplete));
    }

    private IEnumerator FlyRoutine(Vector3 fromPos, Vector3 toPos, Quaternion startRot, bool isFlyingIn, System.Action onComplete)
    {
        _isParked = false;
        ServiceLocator.Get<AudioManager>()?.StartAlienShipRumble();

        Vector3 direction = toPos - fromPos;
        Quaternion lookRotation = startRot;
        if (direction.sqrMagnitude > 0.001f)
        {
            lookRotation = Quaternion.LookRotation(direction);
        }

        transform.position = fromPos;
        transform.rotation = lookRotation * _rotationCorrection;

        float t = 0f;
        while (t < flyDuration)
        {
            t += Time.unscaledDeltaTime; 
            float n = Mathf.Clamp01(t / flyDuration);
            float easeN = flyEase != null ? flyEase.Evaluate(n) : n;

            transform.position = Vector3.LerpUnclamped(fromPos, toPos, easeN);
            transform.rotation = lookRotation * _rotationCorrection;

            yield return null;
        }

        transform.position = toPos;
        transform.rotation = lookRotation * _rotationCorrection;

        var audio = ServiceLocator.Get<AudioManager>();
        audio?.StopAlienShipRumble();
        if (isFlyingIn)
        {
            audio?.PlayAlienArrival(0);
        }

        if (isFlyingIn)
        {
            _parkedBasePos = toPos;
            _bobTime = 0f;
            _isParked = true;
            SpaceshipParked?.Invoke();
        }

        onComplete?.Invoke();
    }
}

/// <summary>
/// Lives on the merchant name <see cref="TMP_Text"/>; uses
/// <see cref="TooltipManager"/> like progression hovers.
/// </summary>
[DisallowMultipleComponent]
public sealed class ShopMerchantTooltipHover : MonoBehaviour,
    IPointerEnterHandler,
    IPointerExitHandler
{
    private ShopShipController _ship;

    public void Bind(ShopShipController ship)
    {
        _ship = ship;
    }

    public void OnPointerEnter(PointerEventData eventData)
    {
        if (_ship == null)
        {
            return;
        }

        string title = _ship.CurrentMerchantDisplayName;

        if (string.IsNullOrWhiteSpace(title))
        {
            title = "Visiting merchant";
        }

        ElementType catalog = _ship.CurrentCatalogElement;
        string desc = BuildDescription(_ship, catalog);

        TooltipManager.Show(
            title,
            desc,
            catalog);
    }

    public void OnPointerExit(PointerEventData eventData)
    {
        TooltipManager.Hide();
    }

    private void OnDisable()
    {
        TooltipManager.Hide();
    }

    public static string BuildDescription(
        ShopShipController ship,
        ElementType catalog)
    {
        var inv = CultureInfo.InvariantCulture;
        return $"Shop Multiplier: {ship.CurrentVisitorPriceMultiplier.ToString("0.##", inv)}x";
    }
}
