using TMPro;
using UnityEngine;
using UnityEngine.EventSystems;
using UnityEngine.UI;

// Generated by Cursor AI (GPT-5.2) for jjmil on 2026-02-16.

/// <summary>
/// UI entry for a single shop offer (one of the 3 balls offered this shop visit).
/// Intended to be used as a prefab that ShopUIController instantiates.
/// </summary>
public sealed class ShopBallOfferEntryUI : MonoBehaviour,
    IBeginDragHandler,
    IDragHandler,
    IEndDragHandler
{
    [SerializeField] private Button button;
    [SerializeField] private TMP_Text titleText;
    [SerializeField] private TMP_Text costText;
    [SerializeField] private Image iconImage;
    [Tooltip("RectTransform to offset upward when selected. Keep this as an inner child to avoid fighting layout groups.")]
    [SerializeField] private RectTransform raiseTarget;
    [SerializeField] private float selectedRaiseY = 12f;
    [SerializeField] private CanvasGroup canvasGroup;

    private int _offerIndex = -1;
    private ShopUIController _shop;
    private Vector2 _baseRaiseTargetAnchoredPos;
    private bool _hasBaseRaiseTargetAnchoredPos;
    private Canvas _rootCanvas;
    private float _startAlpha = 1f;
    private RectTransform _dragVisualRect;
    private CanvasGroup _dragVisualCanvasGroup;

    public int OfferIndex => _offerIndex;

    public void Init(ShopUIController shop, int offerIndex, string title, int cost, Sprite icon)
    {
        _shop = shop;
        _offerIndex = offerIndex;
        EnsureDragComponents();

        if (titleText != null) titleText.text = title ?? string.Empty;
        if (costText != null) costText.text = cost.ToString();

        if (iconImage != null)
        {
            if (icon != null)
            {
                iconImage.enabled = true;
                iconImage.sprite = icon;
            }
            else
            {
                iconImage.enabled = false;
                iconImage.sprite = null;
            }
        }

        if (button != null)
        {
            button.onClick.RemoveListener(OnClick);
            button.onClick.AddListener(OnClick);
        }

        CacheRaiseTargetBasePositionIfNeeded();
        SetSelected(false);
    }

    private void OnDisable()
    {
        CleanupDragState();
    }

    private void OnDestroy()
    {
        CleanupDragState();
    }

    public void SetSelected(bool selected)
    {
        RectTransform rt = GetRaiseTargetRectTransform();
        if (rt == null)
        {
            return;
        }

        CacheRaiseTargetBasePositionIfNeeded();

        Vector2 pos = _baseRaiseTargetAnchoredPos;
        if (selected)
        {
            pos.y += selectedRaiseY;
        }
        rt.anchoredPosition = pos;
    }

    private void OnClick()
    {
        if (_shop == null || _offerIndex < 0)
        {
            return;
        }

        _shop.SelectOfferByIndex(_offerIndex);
    }

    public void OnBeginDrag(PointerEventData eventData)
    {
        EnsureDragComponents();

        if (canvasGroup == null)
        {
            return;
        }

        _startAlpha = canvasGroup.alpha;
        canvasGroup.alpha = 0.35f;
        canvasGroup.blocksRaycasts = false;

        CreateDragVisualIfNeeded();
        UpdateDragVisual(eventData);
    }

    public void OnDrag(PointerEventData eventData)
    {
        if (_rootCanvas == null)
        {
            return;
        }

        UpdateDragVisual(eventData);
    }

    public void OnEndDrag(PointerEventData eventData)
    {
        CleanupDragState();
    }

    private RectTransform GetRaiseTargetRectTransform()
    {
        if (raiseTarget != null)
        {
            return raiseTarget;
        }

        if (iconImage != null)
        {
            return iconImage.rectTransform;
        }

        return null;
    }

    private void CacheRaiseTargetBasePositionIfNeeded()
    {
        if (_hasBaseRaiseTargetAnchoredPos)
        {
            return;
        }

        RectTransform rt = GetRaiseTargetRectTransform();
        if (rt == null)
        {
            return;
        }

        _baseRaiseTargetAnchoredPos = rt.anchoredPosition;
        _hasBaseRaiseTargetAnchoredPos = true;
    }

    private void EnsureDragComponents()
    {
        if (canvasGroup == null)
        {
            canvasGroup = GetComponent<CanvasGroup>();
            if (canvasGroup == null)
            {
                canvasGroup = gameObject.AddComponent<CanvasGroup>();
            }
        }

        if (_rootCanvas == null)
        {
            _rootCanvas = GetComponentInParent<Canvas>();
        }
    }

    private void CreateDragVisualIfNeeded()
    {
        if (_dragVisualRect != null)
        {
            return;
        }

        if (_rootCanvas == null)
        {
            return;
        }

        RectTransform rootRect = _rootCanvas.transform as RectTransform;
        if (rootRect == null)
        {
            return;
        }

        var go = new GameObject($"{name}_DragVisual", typeof(RectTransform), typeof(CanvasGroup),
            typeof(Image));
        _dragVisualRect = go.GetComponent<RectTransform>();
        _dragVisualRect.SetParent(rootRect, worldPositionStays: false);

        _dragVisualCanvasGroup = go.GetComponent<CanvasGroup>();
        _dragVisualCanvasGroup.blocksRaycasts = false;
        _dragVisualCanvasGroup.interactable = false;
        _dragVisualCanvasGroup.alpha = 0.95f;

        Image img = go.GetComponent<Image>();
        if (iconImage != null)
        {
            img.sprite = iconImage.sprite;
            img.color = iconImage.color;
            img.preserveAspect = true;

            RectTransform iconRt = iconImage.rectTransform;
            _dragVisualRect.sizeDelta = iconRt.rect.size;
        }
        else
        {
            img.enabled = false;
        }
    }

    private void UpdateDragVisual(PointerEventData eventData)
    {
        if (_dragVisualRect == null || _rootCanvas == null || eventData == null)
        {
            return;
        }

        RectTransform rootRect = _rootCanvas.transform as RectTransform;
        if (rootRect == null)
        {
            return;
        }

        Camera cam = eventData.pressEventCamera;
        if (RectTransformUtility.ScreenPointToLocalPointInRectangle(
                rootRect,
                eventData.position,
                cam,
                out Vector2 local))
        {
            _dragVisualRect.anchoredPosition = local;
        }
    }

    private void DestroyDragVisual()
    {
        if (_dragVisualRect != null)
        {
            Destroy(_dragVisualRect.gameObject);
        }

        _dragVisualRect = null;
        _dragVisualCanvasGroup = null;
    }

    private void CleanupDragState()
    {
        if (canvasGroup != null)
        {
            canvasGroup.blocksRaycasts = true;
            canvasGroup.alpha = _startAlpha;
        }

        DestroyDragVisual();
    }
}

