// Generated by Antigravity on 2026-03-29
using UnityEngine;

/// <summary>
/// A marker placed in the Board scene to designate where the shop spaceship should wait offscreen,
/// and where it should park when the shop is open.
/// Registers itself with ServiceLocator so the ShopShipController can find it across scenes.
/// </summary>
public class ShopShipMarker : MonoBehaviour
{
    [Tooltip("The transform where the spaceship waits while the shop is closed (offscreen).")]
    public Transform offscreenTransform;

    [Tooltip("The transform where the spaceship parks while the shop is open.")]
    public Transform parkTransform;

    [Tooltip("The transform where the spaceship exits to while the shop closes. If unassigned, uses offscreenTransform.")]
    public Transform exitOffscreenTransform;

    private void OnEnable()
    {
        ServiceLocator.Register<ShopShipMarker>(this);
    }

    private void OnDisable()
    {
        ServiceLocator.Unregister<ShopShipMarker>();
    }
}
