// Generated by Cursor AI (claude-4.6-opus) for jjmil on 2026-03-27.
// Updated 2026-03-27: drag visual for shelf offer drag-and-drop.
using UnityEngine;

/// <summary>
/// Attached to each 3D prefab instantiated on the shop display shelf.
/// Handles hover tooltips and click-to-select via the existing
/// <see cref="RenderTextureRaycaster"/> / <see cref="TooltipManager"/> infrastructure.
/// When a collider is missing one is added automatically so raycasts can hit this object.
/// </summary>
public sealed class ShopOffer3DEntry : MonoBehaviour
{
    private const float DefaultOutlineWidth = 5f;

    private UnifiedShopController _shop;
    private int _offerIndex = -1;
    private ShopOffer _offer;
    private Outline _outline;
    private bool _isHighlighted;
    private bool _isDragVisual;

    public int OfferIndex => _offerIndex;
    public ShopOffer Offer => _offer;

    public void Init(UnifiedShopController shop, int offerIndex, ShopOffer offer)
    {
        _shop = shop;
        _offerIndex = offerIndex;
        _offer = offer;

        EnsureCollider();
        EnsureDefinitionLink();
        SetupOutline();
    }

    /// <summary>
    /// Called by <see cref="RenderTextureRaycaster"/> (or any click handler)
    /// when the player clicks on this offer.
    /// </summary>
    public void OnClick()
    {
        if (_shop != null)
        {
            _shop.OnOfferClicked(_offerIndex);
        }
    }

    public void SetDragVisual(bool dragging)
    {
        _isDragVisual = dragging;

        if (_outline != null)
        {
            if (dragging)
            {
                _outline.OutlineColor = new Color(0.4f, 0.85f, 1f);
                _outline.enabled = true;
            }
            else if (!_isHighlighted)
            {
                _outline.OutlineColor = Color.white;
                _outline.enabled = true;
            }
            else
            {
                _outline.OutlineColor = Color.yellow;
            }
        }
    }

    public void Highlight()
    {
        if (_isHighlighted)
        {
            return;
        }

        _isHighlighted = true;

        if (_outline != null)
        {
            _outline.OutlineColor = Color.yellow;
            _outline.enabled = true;
        }
    }

    public void Unhighlight()
    {
        if (!_isHighlighted)
        {
            return;
        }

        _isHighlighted = false;

        if (_outline != null)
        {
            if (_isDragVisual)
            {
                _outline.OutlineColor = new Color(0.4f, 0.85f, 1f);
            }
            else
            {
                _outline.OutlineColor = Color.white;
            }

            _outline.enabled = true;
        }
    }

    private void EnsureCollider()
    {
        Collider existing = GetComponentInChildren<Collider>();
        if (existing != null)
        {
            existing.enabled = true;
            existing.isTrigger = true;
            return;
        }

        Renderer rend = GetComponentInChildren<Renderer>();
        if (rend != null)
        {
            BoxCollider box = rend.gameObject.AddComponent<BoxCollider>();
            box.isTrigger = true;
        }
    }

    /// <summary>
    /// Attaches the appropriate DefinitionLink component so the existing
    /// <see cref="RenderTextureRaycaster"/> can resolve tooltip text.
    /// </summary>
    private void EnsureDefinitionLink()
    {
        if (_offer == null)
        {
            return;
        }

        if (_offer.Type == ShopOffer.OfferType.Ball)
        {
            BallDefinitionLink link = GetComponentInChildren<BallDefinitionLink>();
            if (link == null)
            {
                // The original prefab should already have one, but if not we cannot
                // add one without a serialized reference. Tooltip fallback will use
                // the ShopOffer3DEntry directly via the raycaster extension.
            }
        }
        else
        {
            BoardComponentDefinitionLink link = GetComponentInChildren<BoardComponentDefinitionLink>();
            if (link == null)
            {
                // Same as above; rely on raycaster extension if link is missing.
            }
        }
    }

    private void SetupOutline()
    {
        _outline = GetComponentInChildren<Outline>();
        if (_outline == null)
        {
            Renderer rend = GetComponentInChildren<Renderer>();
            if (rend != null)
            {
                _outline = rend.gameObject.AddComponent<Outline>();
            }
        }

        if (_outline != null)
        {
            _outline.OutlineMode = Outline.Mode.OutlineAll;
            _outline.OutlineColor = Color.white;
            _outline.OutlineWidth = DefaultOutlineWidth;
            _outline.enabled = true;
        }
    }
}
