// Generated by Antigravity on 2026-03-29
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Controls the visual spaceship that flies in/out during shop transitions.
/// Listens to ShopTransitionController and moves to the active ShopShipMarker.
/// </summary>
public class ShopShipController : MonoBehaviour
{
    public event System.Action SpaceshipParked;
    public event System.Action SpaceshipDeparting;

    [Header("Visuals")]
    [Tooltip("List of possible spaceship visual objects. One will be picked at random.")]
    [SerializeField] private List<GameObject> spaceshipModels;

    [Header("Animation Settings")]
    [SerializeField] private float flyDuration = 0.55f;
    [SerializeField] private AnimationCurve flyEase = AnimationCurve.EaseInOut(0f, 0f, 1f, 1f);
    
    [Header("Bobbing Settings")]
    [SerializeField] private float bobSpeed = 2f;
    [SerializeField] private float bobHeight = 0.2f;

    private ShopTransitionController _transitionController;
    private Coroutine _flyRoutine;

    private bool _isParked = false;
    private float _bobTime = 0f;
    private Vector3 _parkedBasePos;
    private Quaternion _rotationCorrection = Quaternion.identity;

    private void Start()
    {
        // Move far away initially so it's not visible at 0,0,0 if the board isn't fully loaded yet.
        transform.position = new Vector3(0, -9999f, 0);

        PickRandomShip();
        SnapToOffscreen();

        _transitionController = ServiceLocator.Get<ShopTransitionController>();
        if (_transitionController == null)
        {
            _transitionController = Object.FindFirstObjectByType<ShopTransitionController>();
        }

        if (_transitionController != null)
        {
            _transitionController.OpenTransitionStarted += OnOpenStarted;
            _transitionController.CloseTransitionStarted += OnCloseStarted;
        }
    }

    private void OnDestroy()
    {
        if (_transitionController != null)
        {
            _transitionController.OpenTransitionStarted -= OnOpenStarted;
            _transitionController.CloseTransitionStarted -= OnCloseStarted;
        }
    }

    private void Update()
    {
        if (_isParked && _activeShipInstance != null)
        {
            _bobTime += Time.deltaTime;
            float offsetY = Mathf.Sin(_bobTime * bobSpeed) * bobHeight;
            transform.position = _parkedBasePos + new Vector3(0, offsetY, 0);
        }
    }

    private GameObject _activeShipInstance;

    private void PickRandomShip()
    {
        if (spaceshipModels == null || spaceshipModels.Count == 0) return;

        // If the user dragged scene children into the array, disable them all first
        foreach (var model in spaceshipModels)
        {
            if (model != null && model.scene.IsValid()) 
            {
                model.SetActive(false);
            }
        }

        if (_activeShipInstance != null)
        {
            Destroy(_activeShipInstance);
            _activeShipInstance = null;
        }

        int index = Random.Range(0, spaceshipModels.Count);
        GameObject prefabOrInstance = spaceshipModels[index];

        if (prefabOrInstance != null)
        {
            if (prefabOrInstance.scene.IsValid())
            {
                // The user assigned an object already in the scene.
                prefabOrInstance.SetActive(true);
                prefabOrInstance.transform.localRotation = Quaternion.identity;
            }
            else
            {
                // The user assigned a project prefab. Instantiate it.
                _activeShipInstance = Instantiate(prefabOrInstance, transform);
                _activeShipInstance.transform.localPosition = Vector3.zero;
                _activeShipInstance.transform.localRotation = Quaternion.identity;
            }
        }

        UpdateRotationCorrection();
    }

    private void UpdateRotationCorrection()
    {
        _rotationCorrection = Quaternion.identity;
        if (_activeShipInstance == null) return;

        // Try to find BoidShip to get the forward indicator
        BoidShip boid = _activeShipInstance.GetComponentInChildren<BoidShip>();
        Transform indicator = null;
        if (boid != null)
        {
            indicator = boid.ForwardIndicator;
        }
        else
        {
            // Fallback: search for a child named "Forward"
            indicator = _activeShipInstance.transform.Find("Forward");
        }

        if (indicator != null)
        {
            // Calculate local forward of the indicator relative to the model root
            // We transform the indicator's forward vector into the model root's local space.
            Vector3 localForward = _activeShipInstance.transform.InverseTransformDirection(indicator.forward);
            _rotationCorrection = Quaternion.FromToRotation(localForward, Vector3.forward);
        }
    }

    private void SnapToOffscreen()
    {
        var marker = ServiceLocator.Get<ShopShipMarker>();
        if (marker != null && marker.offscreenTransform != null)
        {
            transform.position = marker.offscreenTransform.position;
            transform.rotation = marker.offscreenTransform.rotation;
        }
    }

    private void OnOpenStarted()
    {
        FlyIn();
    }

    private void OnCloseStarted()
    {
        FlyOut();
    }

    public void FlyIn(System.Action onComplete = null)
    {
        PickRandomShip();
        _isParked = false;

        var marker = ServiceLocator.Get<ShopShipMarker>();
        if (marker == null || marker.offscreenTransform == null || marker.parkTransform == null)
        {
            onComplete?.Invoke();
            return;
        }

        if (_flyRoutine != null) StopCoroutine(_flyRoutine);
        _flyRoutine = StartCoroutine(FlyRoutine(marker.offscreenTransform.position, marker.parkTransform.position, marker.offscreenTransform.rotation, true, onComplete));
    }

    public void FlyOut(System.Action onComplete = null)
    {
        _isParked = false;
        SpaceshipDeparting?.Invoke();
        ServiceLocator.Get<AudioManager>()?.PlayAlienDeparture();

        var marker = ServiceLocator.Get<ShopShipMarker>();
        if (marker == null || marker.offscreenTransform == null || marker.parkTransform == null)
        {
            onComplete?.Invoke();
            return;
        }

        Transform exitTransform = marker.exitOffscreenTransform != null ? marker.exitOffscreenTransform : marker.offscreenTransform;
        
        if (_flyRoutine != null) StopCoroutine(_flyRoutine);
        _flyRoutine = StartCoroutine(FlyRoutine(transform.position, exitTransform.position, transform.rotation, false, onComplete));
    }

    private IEnumerator FlyRoutine(Vector3 fromPos, Vector3 toPos, Quaternion startRot, bool isFlyingIn, System.Action onComplete)
    {
        _isParked = false;
        ServiceLocator.Get<AudioManager>()?.StartAlienShipRumble();

        Vector3 direction = toPos - fromPos;
        Quaternion lookRotation = startRot;
        if (direction.sqrMagnitude > 0.001f)
        {
            lookRotation = Quaternion.LookRotation(direction);
        }

        transform.position = fromPos;
        transform.rotation = lookRotation * _rotationCorrection;

        float t = 0f;
        while (t < flyDuration)
        {
            t += Time.unscaledDeltaTime; 
            float n = Mathf.Clamp01(t / flyDuration);
            float easeN = flyEase != null ? flyEase.Evaluate(n) : n;

            transform.position = Vector3.LerpUnclamped(fromPos, toPos, easeN);
            transform.rotation = lookRotation * _rotationCorrection;

            yield return null;
        }

        transform.position = toPos;
        transform.rotation = lookRotation * _rotationCorrection;

        var audio = ServiceLocator.Get<AudioManager>();
        audio?.StopAlienShipRumble();
        if (isFlyingIn)
        {
            audio?.PlayAlienArrival(0);
        }

        if (isFlyingIn)
        {
            _parkedBasePos = toPos;
            _bobTime = 0f;
            _isParked = true;
            SpaceshipParked?.Invoke();
        }

        onComplete?.Invoke();
    }
}
