// Generated by Cursor (claude-4.6-opus) for jjmil on 2026-03-26.
// Updated: tooltip now follows the mouse cursor each frame.
// Updated 2026-03-27: screen-space center for shop confirm panel placement.
// Updated 2026-04-06 by Antigravity (claude-4.6-opus):
// added ElementType color label between title and description.
// Updated 2026-04-21: added ShowBuy/ShowSell with dedicated price panels
// so buy/sell prices render inside the prefab-authored panels instead of
// being prepended to the description string.
// Updated 2026-07-24 by Claude Code (claude-opus-5): definition panels now also
// resolve keywords found in the description text and load their terms from
// Resources, so every tooltip source gets keyword panels and an unresolved tag
// hides its panel instead of showing the previous item's text.
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using NUnit.Framework;
using System.Collections.Generic;
using System.Text.RegularExpressions;


#if ENABLE_INPUT_SYSTEM
using UnityEngine.InputSystem;
#endif

/// <summary>
/// Attach to a tooltip panel root. Handles text content
/// and follows the mouse cursor while visible, with edge
/// clamping so the tooltip stays fully on-screen.
/// </summary>
[RequireComponent(typeof(CanvasGroup))]
public sealed class TooltipUI : MonoBehaviour
{
    public enum PriceMode
    {
        None,
        Buy,
        Sell,
    }

    [SerializeField] private TMP_Text nameText;
    [SerializeField] private TMP_Text typeText;
    [SerializeField] private TMP_Text descText;

    [Header("Price panels")]
    [Tooltip("Child panel shown when the tooltip describes a buyable item. "
        + "Toggled on by ShowBuy, off by Show/ShowSell.")]
    [SerializeField] private GameObject shopPanel;

    [Tooltip("Text inside the shop panel that renders the item cost.")]
    [SerializeField] private TMP_Text costText;

    [Tooltip("Child panel shown when the tooltip describes a sellable item. "
        + "Toggled on by ShowSell, off by Show/ShowBuy.")]
    [SerializeField] private GameObject sellPanel;

    [Tooltip("Text inside the sell panel that renders the item sell price.")]
    [SerializeField] private TMP_Text sellPriceText;

    [SerializeField] private DefinitionPanel firstDefinitionPanel;
    [SerializeField] private DefinitionPanel secondDefinitionPanel;

    [Header("Keyword definitions")]
    [Tooltip("Resources folder holding every TermDefinition. Loaded at runtime "
        + "so a keyword resolves even when the list below was never re-populated "
        + "by the CSV import.")]
    [SerializeField] private string termDefinitionResourcePath =
        "TermDefinitions";

    [Tooltip("Resources folder holding every BallDefinition, used when a tag "
        + "names another ball rather than a term.")]
    [SerializeField] private string ballDefinitionResourcePath =
        "BallDefinitions";

    [Header("Shop skin")]
    [Tooltip("Backgrounds for the shop-only skin; one is rolled per "
        + "visit via TooltipManager.ApplyShopSkin.")]
    [SerializeField] private List<Material> backgroundMaterials =
        new List<Material>();

    [Tooltip("Sliced sprite with the panel shape in alpha and the "
        + "neon border ring in the red channel.")]
    [SerializeField] private Sprite shopSkinSprite;

    [Tooltip("Backgrounds indexed by BallRarity (Common through "
        + "Legendary); items without a rarity keep the rolled visit "
        + "material.")]
    [SerializeField] private List<Material> rarityMaterials =
        new List<Material>();

    [Tooltip("Shop background for tooltips without a rarity (hub, "
        + "ships, modules). Leave empty to roll blue/pink per visit.")]
    [SerializeField] private Material defaultShopMaterial;

    [Tooltip("Static twins of the rarity materials, used on the buy/"
        + "sell price bars so they match the header's frozen look.")]
    [SerializeField] private List<Material> staticRarityMaterials =
        new List<Material>();

    [Tooltip("Static material for the price bars when the item has no "
        + "rarity.")]
    [SerializeField] private Material staticDefaultMaterial;

    [SerializeField] private float shopSkinAlpha = 0.85f;
    [SerializeField] private float shopSkinPanelPpu = 2f;
    [SerializeField] private float shopSkinBarPpu = 4f;

    [SerializeField] private bool controllerInUse = false;
    [SerializeField] private Vector2 cachedVector;

    //Auto populated from ball CSV population.
    public List<BallDefinition> necessaryBallDefinitions = new List<BallDefinition>();
    public List<TermDefinition> necessaryTermDefinitions = new List<TermDefinition>();


    private RectTransform _rect;
    private Canvas _rootCanvas;
    private RectTransform _canvasRect;
    private CanvasGroup _canvasGroup;

    private const float cursorOffsetY = 40f;
    private const float screenEdgePadding = 12f;
    private const int definitionPanelCount = 2;

    // Matches a whole word, allowing the plural/past/gerund forms the ball and
    // component copy uses: Ignite -> Ignited, Fuel -> Fueled, Detonate ->
    // detonates.
    private const string keywordSuffixPattern = "(s|es|d|ed|ing)?";

    private static readonly RegexOptions keywordRegexOptions =
        RegexOptions.IgnoreCase | RegexOptions.CultureInvariant;

    private List<TermDefinition> _termLookup;
    private List<BallDefinition> _ballLookup;
    private List<Regex> _keywordPatterns;

    private readonly List<DefinitionEntry> _resolvedDefinitions =
        new List<DefinitionEntry>();

    private readonly List<KeywordMatch> _keywordMatches =
        new List<KeywordMatch>();

    private readonly struct DefinitionEntry
    {
        public DefinitionEntry(string displayName, string description)
        {
            DisplayName = displayName;
            Description = description;
        }

        public string DisplayName { get; }
        public string Description { get; }
    }

    private readonly struct KeywordMatch
    {
        public KeywordMatch(int index, int length, TermDefinition definition)
        {
            Index = index;
            Length = length;
            Definition = definition;
        }

        public int Index { get; }
        public int Length { get; }
        public TermDefinition Definition { get; }
    }


    private void Awake()
    {
        // The prefab accidentally carries a TooltipUI on each child price
        // panel. Disable nested instances so they don't self-hide in Awake
        // or fight the root for mouse-positioning in LateUpdate.
        if (HasAncestorTooltipUI())
        {
            enabled = false;
            return;
        }

        _rect = GetComponent<RectTransform>();
        _canvasGroup = GetComponent<CanvasGroup>();
        _canvasGroup.blocksRaycasts = false;
        CacheCanvas();
        EnsureDefinitionLookups();
        SkinAllPanels(staticDefaultMaterial, staticDefaultMaterial);
        gameObject.SetActive(false);
    }

    private void LateUpdate()
    {
        if (!controllerInUse)
        {
            PositionAtMouse();
        } else
        {
            _rect.anchoredPosition = cachedVector;
        }
    }

    public void Show(
        string title,
        string description,
        List<string> tags,
        string type)
    {
        ApplyContent(title, description, type);
        SetPricePanels(PriceMode.None, 0);
        SetDefinitionPanels(tags, description);

        gameObject.SetActive(true);
        _rect.SetAsLastSibling();

        LayoutRebuilder.ForceRebuildLayoutImmediate(
            _rect);
        PositionAtMouse();
        controllerInUse = false;
    }

    public void ShowBuy(
        string title,
        string description,
        List<string> tags,
        string type,
        int price)
    {
        Show(title, description, tags, type);
        SetPricePanels(PriceMode.Buy, price);
    }

    public void ShowSell(
        string title,
        string description,
        List<string> tags,
        string type,
        int price)
    {
        Show(title, description, tags, type);
        SetPricePanels(PriceMode.Sell, price);
    }

    public void ShowAtPosition(string title,
                               string description,
                               List<string> tags,
                               Vector2 position,
                               string type)
    {
        ApplyContent(title, description, type);
        SetPricePanels(PriceMode.None, 0);
        SetDefinitionPanels(tags, description);

        gameObject.SetActive(true);
        _rect.SetAsLastSibling();

        LayoutRebuilder.ForceRebuildLayoutImmediate(_rect);

        RectTransformUtility.ScreenPointToLocalPointInRectangle(
                _canvasRect,
                position,
                _rootCanvas.renderMode == RenderMode.ScreenSpaceOverlay ? null : _rootCanvas.worldCamera,
                out Vector2 localPos);


        Vector2 tooltipSize = _rect.rect.size;
        localPos.y +=
            cursorOffsetY
            + tooltipSize.y * (1f - _rect.pivot.y);
        Vector2 canvasSize = _canvasRect.rect.size;
        Vector2 halfCanvas = canvasSize * 0.5f;

        float minX =
            -halfCanvas.x + screenEdgePadding
            + tooltipSize.x * _rect.pivot.x;

        float maxX =
            halfCanvas.x - screenEdgePadding
            - tooltipSize.x * (1f - _rect.pivot.x);

        float minY =
            -halfCanvas.y + screenEdgePadding
            + tooltipSize.y * _rect.pivot.y;

        float maxY =
            halfCanvas.y - screenEdgePadding
            - tooltipSize.y * (1f - _rect.pivot.y);

        localPos.x = Mathf.Clamp(localPos.x, minX, maxX);
        localPos.y = Mathf.Clamp(localPos.y, minY, maxY);

        _rect.anchoredPosition = localPos;
        cachedVector = localPos;
        controllerInUse = true;
    }

    public void ShowBuyAtPosition(
        string title,
        string description,
        List<string> tags,
        Vector2 position,
        string type,
        int price)
    {
        ShowAtPosition(title, description, tags, position, type);
        SetPricePanels(PriceMode.Buy, price);
    }

    public void ShowSellAtPosition(
        string title,
        string description,
        List<string> tags,
        Vector2 position,
        string type,
        int price)
    {
        ShowAtPosition(title, description, tags, position, type);
        SetPricePanels(PriceMode.Sell, price);
    }

    /// <summary>
    /// Fills the two keyword panels from the item's authored tags first, then
    /// from any term named in its description. A panel is only shown once a
    /// definition actually resolved, so it can never keep a previous item's
    /// text.
    /// </summary>
    private void SetDefinitionPanels(List<string> tags, string description)
    {
        EnsureDefinitionLookups();

        _resolvedDefinitions.Clear();
        CollectTaggedDefinitions(tags);
        CollectKeywordDefinitions(description);

        ApplyDefinitionPanel(firstDefinitionPanel, 0);
        ApplyDefinitionPanel(secondDefinitionPanel, 1);
    }

    private void ApplyDefinitionPanel(DefinitionPanel panel, int index)
    {
        if (panel == null)
        {
            return;
        }

        if (index >= _resolvedDefinitions.Count)
        {
            panel.gameObject.SetActive(false);
            return;
        }

        DefinitionEntry entry = _resolvedDefinitions[index];
        panel.Populate(entry.DisplayName, entry.Description);
        panel.gameObject.SetActive(true);
    }

    private void CollectTaggedDefinitions(List<string> tags)
    {
        if (tags == null)
        {
            return;
        }

        foreach (string tag in tags)
        {
            if (_resolvedDefinitions.Count >= definitionPanelCount)
            {
                return;
            }

            if (string.IsNullOrWhiteSpace(tag))
            {
                continue;
            }

            TermDefinition term = FindTerm(tag);
            if (term != null)
            {
                AddDefinition(
                    term.GetSafeDisplayName(), term.Description);
                continue;
            }

            BallDefinition ball = FindBall(tag);
            if (ball != null)
            {
                AddDefinition(
                    ball.GetSafeDisplayName(), ball.Description);
            }
        }
    }

    private void CollectKeywordDefinitions(string description)
    {
        if (string.IsNullOrWhiteSpace(description)
            || _resolvedDefinitions.Count >= definitionPanelCount)
        {
            return;
        }

        _keywordMatches.Clear();

        for (int i = 0; i < _termLookup.Count; i++)
        {
            if (_keywordPatterns[i] == null)
            {
                continue;
            }

            System.Text.RegularExpressions.Match match =
                _keywordPatterns[i].Match(description);
            if (!match.Success || OverlapsExistingMatch(match))
            {
                continue;
            }

            _keywordMatches.Add(new KeywordMatch(
                match.Index, match.Length, _termLookup[i]));
        }

        // Terms were tested longest-first so an overlap resolves to the longer
        // name, but the panels read better in the order the copy mentions them.
        _keywordMatches.Sort(
            (a, b) => a.Index.CompareTo(b.Index));

        foreach (KeywordMatch match in _keywordMatches)
        {
            if (_resolvedDefinitions.Count >= definitionPanelCount)
            {
                return;
            }

            AddDefinition(
                match.Definition.GetSafeDisplayName(),
                match.Definition.Description);
        }
    }

    private bool OverlapsExistingMatch(
        System.Text.RegularExpressions.Match match)
    {
        foreach (KeywordMatch existing in _keywordMatches)
        {
            if (match.Index < existing.Index + existing.Length
                && existing.Index < match.Index + match.Length)
            {
                return true;
            }
        }

        return false;
    }

    private void AddDefinition(string displayName, string description)
    {
        foreach (DefinitionEntry entry in _resolvedDefinitions)
        {
            if (entry.DisplayName == displayName)
            {
                return;
            }
        }

        _resolvedDefinitions.Add(
            new DefinitionEntry(displayName, description));
    }

    // Tags are authored as CSV asset names, so the locale-invariant asset name
    // is matched first and the localized display name only as a fallback.
    private TermDefinition FindTerm(string tag)
    {
        foreach (TermDefinition def in _termLookup)
        {
            if (def.name == tag || def.DisplayName == tag)
            {
                return def;
            }
        }

        return null;
    }

    private BallDefinition FindBall(string tag)
    {
        foreach (BallDefinition def in _ballLookup)
        {
            if (def.name == tag || def.DisplayName == tag)
            {
                return def;
            }
        }

        return null;
    }

    /// <summary>
    /// Builds the term/ball lookups once. The prefab's hand-wired lists are
    /// kept for authored overrides but the Resources sweep is what guarantees
    /// every shipped term is reachable.
    /// </summary>
    private void EnsureDefinitionLookups()
    {
        if (_termLookup != null)
        {
            return;
        }

        _termLookup = new List<TermDefinition>();
        AddNamedDefinitions(_termLookup, necessaryTermDefinitions);
        AddNamedDefinitions(
            _termLookup,
            Resources.LoadAll<TermDefinition>(termDefinitionResourcePath));

        _termLookup.Sort((a, b) =>
            b.GetSafeDisplayName().Length
                .CompareTo(a.GetSafeDisplayName().Length));

        // Index-aligned with _termLookup; an unnamed term stays findable by
        // tag but is given no pattern so it can't match stray prose.
        _keywordPatterns = new List<Regex>(_termLookup.Count);
        foreach (TermDefinition def in _termLookup)
        {
            if (string.IsNullOrWhiteSpace(def.DisplayName))
            {
                _keywordPatterns.Add(null);
                continue;
            }

            _keywordPatterns.Add(new Regex(
                @"\b"
                + Regex.Escape(def.DisplayName)
                + keywordSuffixPattern
                + @"\b",
                keywordRegexOptions));
        }

        _ballLookup = new List<BallDefinition>();
        AddNamedDefinitions(_ballLookup, necessaryBallDefinitions);
        AddNamedDefinitions(
            _ballLookup,
            Resources.LoadAll<BallDefinition>(ballDefinitionResourcePath));
    }

    private static void AddNamedDefinitions<T>(
        List<T> target, IEnumerable<T> source)
        where T : UnityEngine.Object
    {
        if (source == null)
        {
            return;
        }

        foreach (T item in source)
        {
            if (item != null && !target.Contains(item))
            {
                target.Add(item);
            }
        }
    }

    public void Hide()
    {
        if (gameObject.activeSelf)
        {
            gameObject.SetActive(false);
        }
    }

    // The shared tooltip serves every screen (shop, progression, ship
    // select), so the arcade restyle is applied only while the shop is
    // open and reverted on close; other screens keep the prefab look.
    // Same roll modulo count on tooltip and header keeps both panels
    // on the same theme for a given shop visit.
    public void ApplyShopSkin(int roll)
    {
        if (backgroundMaterials.Count == 0 || shopSkinSprite == null)
        {
            return;
        }

        CaptureDefaultSkinIfNeeded();

        _rolledMaterial = defaultShopMaterial != null
            ? defaultShopMaterial
            : backgroundMaterials[Mathf.Abs(roll) % backgroundMaterials.Count];
        _shopSkinActive = true;

        SkinAllPanels(_rolledMaterial, staticDefaultMaterial);
    }

    // Recolors the skin for the item being shown. Rarity items are
    // skinned even outside the shop (hand balls, placed components);
    // without a rarity the panel falls back to the visit's rolled
    // material in the shop, or the default look elsewhere.
    public void ApplyRaritySkin(BallRarity? rarity)
    {
        Material mat = PickByRarity(rarityMaterials, rarity);

        if (mat == null)
        {
            if (_shopSkinActive && _rolledMaterial != null)
            {
                SkinAllPanels(_rolledMaterial, staticDefaultMaterial);
            }
            else
            {
                RestoreDefaultImages();
            }
            return;
        }

        Material barMat = PickByRarity(staticRarityMaterials, rarity);

        CaptureDefaultSkinIfNeeded();
        SkinAllPanels(mat, barMat != null ? barMat : staticDefaultMaterial);
    }

    private static Material PickByRarity(
        List<Material> materials, BallRarity? rarity)
    {
        if (!rarity.HasValue)
        {
            return null;
        }

        int index = (int)rarity.Value;
        return index >= 0 && index < materials.Count
            ? materials[index]
            : null;
    }

    // The main panel and definition panels animate; the price bars use
    // the static twin so they match the header's frozen look.
    private void SkinAllPanels(Material mat, Material barMat)
    {
        SkinImage(GetComponent<Image>(), mat, shopSkinPanelPpu);
        SkinImage(GetPanelImage(firstDefinitionPanel), mat, shopSkinPanelPpu);
        SkinImage(GetPanelImage(secondDefinitionPanel), mat, shopSkinPanelPpu);

        if (barMat != null)
        {
            SkinImage(GetPanelImage(shopPanel), barMat, shopSkinBarPpu);
            SkinImage(GetPanelImage(sellPanel), barMat, shopSkinBarPpu);
        }
    }

    public void ApplyDefaultSkin()
    {
        RestoreDefaultImages();
        _shopSkinActive = false;
        _rolledMaterial = null;
    }

    private void RestoreDefaultImages()
    {
        if (!_defaultSkinCaptured)
        {
            return;
        }

        foreach (var entry in _defaultImageStates)
        {
            Image image = entry.Key;
            if (image == null)
            {
                continue;
            }

            DefaultImageState state = entry.Value;
            image.material = state.material;
            image.sprite = state.sprite;
            image.color = state.color;
            image.type = state.type;
            image.pixelsPerUnitMultiplier = state.pixelsPerUnitMultiplier;
        }
    }

    private struct DefaultImageState
    {
        public Material material;
        public Sprite sprite;
        public Color color;
        public Image.Type type;
        public float pixelsPerUnitMultiplier;
    }

    private readonly Dictionary<Image, DefaultImageState>
        _defaultImageStates = new Dictionary<Image, DefaultImageState>();
    private Material _rolledMaterial;
    private bool _shopSkinActive;
    private bool _defaultSkinCaptured;

    private void CaptureDefaultSkinIfNeeded()
    {
        if (_defaultSkinCaptured)
        {
            return;
        }

        _defaultSkinCaptured = true;

        CaptureImageDefault(GetComponent<Image>());
        CaptureImageDefault(GetPanelImage(firstDefinitionPanel));
        CaptureImageDefault(GetPanelImage(secondDefinitionPanel));
        CaptureImageDefault(GetPanelImage(shopPanel));
        CaptureImageDefault(GetPanelImage(sellPanel));
    }

    private void CaptureImageDefault(Image image)
    {
        if (image == null || _defaultImageStates.ContainsKey(image))
        {
            return;
        }

        _defaultImageStates[image] = new DefaultImageState
        {
            material = image.material,
            sprite = image.sprite,
            color = image.color,
            type = image.type,
            pixelsPerUnitMultiplier = image.pixelsPerUnitMultiplier,
        };
    }

    private void SkinImage(Image image, Material mat, float ppu)
    {
        if (image == null)
        {
            return;
        }

        image.material = mat;
        image.sprite = shopSkinSprite;
        image.type = Image.Type.Sliced;
        image.pixelsPerUnitMultiplier = ppu;
        image.color = new Color(1f, 1f, 1f, shopSkinAlpha);
    }

    private static Image GetPanelImage(DefinitionPanel panel)
    {
        return panel == null ? null : panel.GetComponent<Image>();
    }

    private static Image GetPanelImage(GameObject panel)
    {
        return panel == null ? null : panel.GetComponent<Image>();
    }

    public bool IsVisible => gameObject.activeSelf;

    /// <summary>
    /// Center of the tooltip rect in screen pixels (bottom-left origin).
    /// Used to align other UI (e.g. shop confirm) with the hover tooltip.
    /// </summary>
    public bool TryGetScreenRectCenterInScreenSpace(
        out Vector2 screenCenter)
    {
        screenCenter = default;

        if (!IsVisible || _rect == null)
        {
            return false;
        }

        if (_canvasRect == null)
        {
            CacheCanvas();
        }

        if (_canvasRect == null || _rootCanvas == null)
        {
            return false;
        }

        Camera cam =
            _rootCanvas.renderMode
                == RenderMode.ScreenSpaceOverlay
                ? null
                : _rootCanvas.worldCamera;

        Vector3[] corners = new Vector3[4];
        _rect.GetWorldCorners(corners);
        Vector2 a =
            RectTransformUtility.WorldToScreenPoint(
                cam, corners[0]);
        Vector2 b =
            RectTransformUtility.WorldToScreenPoint(
                cam, corners[2]);
        screenCenter = (a + b) * 0.5f;

        return true;
    }

    public void AssignReferences(
        TMP_Text name,
        TMP_Text type,
        TMP_Text desc)
    {
        nameText = name;
        typeText = type;
        descText = desc;
    }

    private void ApplyContent(
        string title,
        string description,
        string type)
    {
        // Reset to the visit material so a previous item's rarity color
        // never lingers; callers with a rarity re-skin right after.
        ApplyRaritySkin(null);

        if (nameText == null || descText == null)
        {
            return;
        }

        nameText.text = title;

        if (typeText != null)
        {
            typeText.text = string.IsNullOrWhiteSpace(type)
                ? "N/A"
                : type;
        }

        descText.text =
            string.IsNullOrWhiteSpace(description)
                ? "No description."
                : description;
    }

    private void SetPricePanels(PriceMode mode, int price)
    {
        if (shopPanel != null)
        {
            bool buyActive = mode == PriceMode.Buy;
            if (shopPanel.activeSelf != buyActive)
            {
                shopPanel.SetActive(buyActive);
            }
        }

        if (sellPanel != null)
        {
            bool sellActive = mode == PriceMode.Sell;
            if (sellPanel.activeSelf != sellActive)
            {
                sellPanel.SetActive(sellActive);
            }
        }

        if (mode == PriceMode.Buy && costText != null)
        {
            costText.text = $"${price}";
        }
        else if (mode == PriceMode.Sell && sellPriceText != null)
        {
            sellPriceText.text = LocalizedUI.Format("gameplay.sellPrice", "Sell Price: ${0}", price);
        }
    }

    private bool HasAncestorTooltipUI()
    {
        Transform parent = transform.parent;
        while (parent != null)
        {
            if (parent.GetComponent<TooltipUI>() != null)
            {
                return true;
            }
            parent = parent.parent;
        }
        return false;
    }

    private void CacheCanvas()
    {
        _rootCanvas = GetComponentInParent<Canvas>();

        if (_rootCanvas != null)
        {
            _rootCanvas = _rootCanvas.rootCanvas;
            _canvasRect =
                _rootCanvas.GetComponent<RectTransform>();
        }
    }

    private void PositionAtMouse()
    {
        if (_canvasRect == null)
        {
            CacheCanvas();
        }

        if (_canvasRect == null)
        {
            return;
        }

        Vector2 screenPos = GetMouseScreenPos();

        RectTransformUtility
            .ScreenPointToLocalPointInRectangle(
                _canvasRect,
                screenPos,
                _rootCanvas.renderMode
                    == RenderMode.ScreenSpaceOverlay
                    ? null
                    : _rootCanvas.worldCamera,
                out Vector2 localPos);

        Vector2 tooltipSize = _rect.rect.size;
        localPos.y +=
            cursorOffsetY
            + tooltipSize.y * (1f - _rect.pivot.y);
        Vector2 canvasSize = _canvasRect.rect.size;
        Vector2 halfCanvas = canvasSize * 0.5f;

        float minX =
            -halfCanvas.x + screenEdgePadding
            + tooltipSize.x * _rect.pivot.x;

        float maxX =
            halfCanvas.x - screenEdgePadding
            - tooltipSize.x * (1f - _rect.pivot.x);

        float minY =
            -halfCanvas.y + screenEdgePadding
            + tooltipSize.y * _rect.pivot.y;

        float maxY =
            halfCanvas.y - screenEdgePadding
            - tooltipSize.y * (1f - _rect.pivot.y);

        localPos.x = Mathf.Clamp(localPos.x, minX, maxX);
        localPos.y = Mathf.Clamp(localPos.y, minY, maxY);

        _rect.anchoredPosition = localPos;
    }

    private static Vector2 GetMouseScreenPos()
    {
#if ENABLE_INPUT_SYSTEM
        var mouse = Mouse.current;

        if (mouse != null)
        {
            return mouse.position.ReadValue();
        }

        return Vector2.zero;
#else
        return Input.mousePosition;
#endif
    }
}
