// Generated by Cursor (claude-4.6-opus) for jjmil on 2026-03-26.
using TMPro;
using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// Global singleton that owns the single shared tooltip instance.
/// Call <see cref="Show"/> / <see cref="Hide"/> from anywhere.
/// If no prefab is assigned the tooltip is built at runtime
/// matching the original progression-screen style.
/// </summary>
public sealed class TooltipManager : MonoBehaviour
{
    [Tooltip(
        "Optional tooltip prefab with a TooltipUI component. "
        + "If left null, one is created at runtime.")]
    [SerializeField] private TooltipUI tooltipPrefab;

    private TooltipUI _instance;
    private Canvas _overlayCanvas;

    private const int tooltipSortOrder = 9999;
    private const float panelWidth = 220f;
    private const float nameFontSize = 18f;
    private const float descFontSize = 14f;

    public static TooltipManager Instance { get; private set; }

    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }

        Instance = this;
        DontDestroyOnLoad(gameObject);
        EnsureTooltip();
    }

    private void OnDestroy()
    {
        if (Instance == this)
        {
            Instance = null;
        }
    }

    public static void Show(
        string title,
        string description)
    {
        if (Instance == null || Instance._instance == null)
        {
            return;
        }

        Instance._instance.Show(title, description);
    }

    public static void Hide()
    {
        if (Instance == null || Instance._instance == null)
        {
            return;
        }

        Instance._instance.Hide();
    }

    public static bool IsVisible
    {
        get
        {
            if (Instance == null
                || Instance._instance == null)
            {
                return false;
            }

            return Instance._instance.IsVisible;
        }
    }

    private void EnsureTooltip()
    {
        if (_instance != null)
        {
            return;
        }

        EnsureOverlayCanvas();

        if (tooltipPrefab != null)
        {
            _instance = Instantiate(
                tooltipPrefab,
                _overlayCanvas.transform,
                false);
        }
        else
        {
            _instance = BuildRuntimeTooltip();
        }
    }

    private void EnsureOverlayCanvas()
    {
        if (_overlayCanvas != null)
        {
            return;
        }

        var canvasGo = new GameObject(
            "TooltipCanvas",
            typeof(RectTransform),
            typeof(Canvas),
            typeof(CanvasScaler),
            typeof(GraphicRaycaster));

        canvasGo.transform.SetParent(
            transform, false);

        _overlayCanvas = canvasGo.GetComponent<Canvas>();
        _overlayCanvas.renderMode =
            RenderMode.ScreenSpaceOverlay;
        _overlayCanvas.sortingOrder = tooltipSortOrder;

        var scaler =
            canvasGo.GetComponent<CanvasScaler>();
        scaler.uiScaleMode =
            CanvasScaler.ScaleMode.ScaleWithScreenSize;
        scaler.referenceResolution =
            new Vector2(1920f, 1080f);
        scaler.matchWidthOrHeight = 0.5f;
    }

    private TooltipUI BuildRuntimeTooltip()
    {
        var panelGo = new GameObject(
            "Tooltip",
            typeof(RectTransform),
            typeof(Image),
            typeof(VerticalLayoutGroup),
            typeof(ContentSizeFitter),
            typeof(CanvasGroup),
            typeof(TooltipUI));

        panelGo.transform.SetParent(
            _overlayCanvas.transform, false);

        var panelRect =
            panelGo.GetComponent<RectTransform>();
        panelRect.pivot = new Vector2(0.5f, 0f);
        panelRect.anchorMin = new Vector2(0.5f, 0.5f);
        panelRect.anchorMax = new Vector2(0.5f, 0.5f);
        panelRect.sizeDelta =
            new Vector2(panelWidth, 0f);

        var bg = panelGo.GetComponent<Image>();
        bg.color =
            new Color(0.12f, 0.12f, 0.14f, 0.95f);

        var vlg = panelGo
            .GetComponent<VerticalLayoutGroup>();
        vlg.padding = new RectOffset(12, 12, 10, 10);
        vlg.spacing = 4f;
        vlg.childAlignment = TextAnchor.UpperLeft;
        vlg.childControlWidth = true;
        vlg.childControlHeight = true;
        vlg.childForceExpandWidth = true;
        vlg.childForceExpandHeight = false;

        var csf = panelGo
            .GetComponent<ContentSizeFitter>();
        csf.horizontalFit =
            ContentSizeFitter.FitMode.Unconstrained;
        csf.verticalFit =
            ContentSizeFitter.FitMode.PreferredSize;

        var nameGo = new GameObject(
            "TooltipName",
            typeof(RectTransform),
            typeof(TextMeshProUGUI));
        nameGo.transform.SetParent(
            panelGo.transform, false);

        var nameText =
            nameGo.GetComponent<TextMeshProUGUI>();
        nameText.fontSize = nameFontSize;
        nameText.fontStyle = FontStyles.Bold;
        nameText.color = Color.white;
        nameText.textWrappingMode =
            TextWrappingModes.Normal;

        var descGo = new GameObject(
            "TooltipDesc",
            typeof(RectTransform),
            typeof(TextMeshProUGUI));
        descGo.transform.SetParent(
            panelGo.transform, false);

        var descText =
            descGo.GetComponent<TextMeshProUGUI>();
        descText.fontSize = descFontSize;
        descText.color =
            new Color(0.78f, 0.78f, 0.78f, 1f);
        descText.textWrappingMode =
            TextWrappingModes.Normal;

        var tooltipUI =
            panelGo.GetComponent<TooltipUI>();
        tooltipUI.AssignReferences(nameText, descText);

        panelGo.SetActive(false);

        return tooltipUI;
    }
}
