// Generated by Cursor (claude-4.6-opus) for jjmil on 2026-03-26.
// Updated: tooltip now follows the mouse cursor each frame.
// Updated 2026-03-27: screen-space center for shop confirm panel placement.
// Updated 2026-04-06 by Antigravity (claude-4.6-opus):
// added ElementType color label between title and description.
// Updated 2026-04-21: added ShowBuy/ShowSell with dedicated price panels
// so buy/sell prices render inside the prefab-authored panels instead of
// being prepended to the description string.
using TMPro;
using UnityEngine;
using UnityEngine.UI;

#if ENABLE_INPUT_SYSTEM
using UnityEngine.InputSystem;
#endif

/// <summary>
/// Attach to a tooltip panel root. Handles text content
/// and follows the mouse cursor while visible, with edge
/// clamping so the tooltip stays fully on-screen.
/// </summary>
[RequireComponent(typeof(CanvasGroup))]
public sealed class TooltipUI : MonoBehaviour
{
    public enum PriceMode
    {
        None,
        Buy,
        Sell,
    }

    [SerializeField] private TMP_Text nameText;
    [SerializeField] private TMP_Text typeText;
    [SerializeField] private TMP_Text descText;

    [Header("Price panels")]
    [Tooltip("Child panel shown when the tooltip describes a buyable item. "
        + "Toggled on by ShowBuy, off by Show/ShowSell.")]
    [SerializeField] private GameObject shopPanel;

    [Tooltip("Text inside the shop panel that renders the item cost.")]
    [SerializeField] private TMP_Text costText;

    [Tooltip("Child panel shown when the tooltip describes a sellable item. "
        + "Toggled on by ShowSell, off by Show/ShowBuy.")]
    [SerializeField] private GameObject sellPanel;

    [Tooltip("Text inside the sell panel that renders the item sell price.")]
    [SerializeField] private TMP_Text sellPriceText;

    [SerializeField] private bool controllerInUse = false;
    [SerializeField] private Vector2 cachedVector;

    private RectTransform _rect;
    private Canvas _rootCanvas;
    private RectTransform _canvasRect;
    private CanvasGroup _canvasGroup;

    private const float cursorOffsetY = 40f;
    private const float screenEdgePadding = 12f;


    private void Awake()
    {
        // The prefab accidentally carries a TooltipUI on each child price
        // panel. Disable nested instances so they don't self-hide in Awake
        // or fight the root for mouse-positioning in LateUpdate.
        if (HasAncestorTooltipUI())
        {
            enabled = false;
            return;
        }

        _rect = GetComponent<RectTransform>();
        _canvasGroup = GetComponent<CanvasGroup>();
        _canvasGroup.blocksRaycasts = false;
        CacheCanvas();
        gameObject.SetActive(false);
    }

    private void LateUpdate()
    {
        if (!controllerInUse)
        {
            PositionAtMouse();
        } else
        {
            _rect.anchoredPosition = cachedVector;
        }
    }

    public void Show(
        string title,
        string description,
        ElementType elementType = ElementType.None)
    {
        ApplyContent(title, description, elementType);
        SetPricePanels(PriceMode.None, 0);

        gameObject.SetActive(true);
        _rect.SetAsLastSibling();

        LayoutRebuilder.ForceRebuildLayoutImmediate(
            _rect);
        PositionAtMouse();
        controllerInUse = false;
    }

    public void ShowBuy(
        string title,
        string description,
        ElementType elementType,
        int price)
    {
        Show(title, description, elementType);
        SetPricePanels(PriceMode.Buy, price);
    }

    public void ShowSell(
        string title,
        string description,
        ElementType elementType,
        int price)
    {
        Show(title, description, elementType);
        SetPricePanels(PriceMode.Sell, price);
    }

    public void ShowAtPosition(string title, string description, Vector2 position, ElementType elementType = ElementType.None)
    {
        ApplyContent(title, description, elementType);
        SetPricePanels(PriceMode.None, 0);

        gameObject.SetActive(true);
        _rect.SetAsLastSibling();

        LayoutRebuilder.ForceRebuildLayoutImmediate(_rect);

        RectTransformUtility.ScreenPointToLocalPointInRectangle(
                _canvasRect,
                position,
                _rootCanvas.renderMode == RenderMode.ScreenSpaceOverlay ? null : _rootCanvas.worldCamera,
                out Vector2 localPos);


        Vector2 tooltipSize = _rect.rect.size;
        localPos.y +=
            cursorOffsetY
            + tooltipSize.y * (1f - _rect.pivot.y);
        Vector2 canvasSize = _canvasRect.rect.size;
        Vector2 halfCanvas = canvasSize * 0.5f;

        float minX =
            -halfCanvas.x + screenEdgePadding
            + tooltipSize.x * _rect.pivot.x;

        float maxX =
            halfCanvas.x - screenEdgePadding
            - tooltipSize.x * (1f - _rect.pivot.x);

        float minY =
            -halfCanvas.y + screenEdgePadding
            + tooltipSize.y * _rect.pivot.y;

        float maxY =
            halfCanvas.y - screenEdgePadding
            - tooltipSize.y * (1f - _rect.pivot.y);

        localPos.x = Mathf.Clamp(localPos.x, minX, maxX);
        localPos.y = Mathf.Clamp(localPos.y, minY, maxY);

        _rect.anchoredPosition = localPos;
        cachedVector = localPos;
        controllerInUse = true;
    }

    public void ShowBuyAtPosition(
        string title,
        string description,
        Vector2 position,
        ElementType elementType,
        int price)
    {
        ShowAtPosition(title, description, position, elementType);
        SetPricePanels(PriceMode.Buy, price);
    }

    public void ShowSellAtPosition(
        string title,
        string description,
        Vector2 position,
        ElementType elementType,
        int price)
    {
        ShowAtPosition(title, description, position, elementType);
        SetPricePanels(PriceMode.Sell, price);
    }


    public void Hide()
    {
        if (gameObject.activeSelf)
        {
            gameObject.SetActive(false);
        }
    }

    public bool IsVisible => gameObject.activeSelf;

    /// <summary>
    /// Center of the tooltip rect in screen pixels (bottom-left origin).
    /// Used to align other UI (e.g. shop confirm) with the hover tooltip.
    /// </summary>
    public bool TryGetScreenRectCenterInScreenSpace(
        out Vector2 screenCenter)
    {
        screenCenter = default;

        if (!IsVisible || _rect == null)
        {
            return false;
        }

        if (_canvasRect == null)
        {
            CacheCanvas();
        }

        if (_canvasRect == null || _rootCanvas == null)
        {
            return false;
        }

        Camera cam =
            _rootCanvas.renderMode
                == RenderMode.ScreenSpaceOverlay
                ? null
                : _rootCanvas.worldCamera;

        Vector3[] corners = new Vector3[4];
        _rect.GetWorldCorners(corners);
        Vector2 a =
            RectTransformUtility.WorldToScreenPoint(
                cam, corners[0]);
        Vector2 b =
            RectTransformUtility.WorldToScreenPoint(
                cam, corners[2]);
        screenCenter = (a + b) * 0.5f;

        return true;
    }

    public void AssignReferences(
        TMP_Text name,
        TMP_Text type,
        TMP_Text desc)
    {
        nameText = name;
        typeText = type;
        descText = desc;
    }

    private void ApplyContent(
        string title,
        string description,
        ElementType elementType)
    {
        if (nameText == null || descText == null)
        {
            return;
        }

        nameText.text = title;

        if (typeText != null)
        {
            string typeName = ElementTypeColors.GetDisplayName(elementType);
            Color typeColor =
                ElementTypeColors.GetColor(elementType);
            typeText.text = typeName;
            typeText.color = typeColor;
        }

        descText.text =
            string.IsNullOrWhiteSpace(description)
                ? "No description."
                : description;
    }

    private void SetPricePanels(PriceMode mode, int price)
    {
        if (shopPanel != null)
        {
            bool buyActive = mode == PriceMode.Buy;
            if (shopPanel.activeSelf != buyActive)
            {
                shopPanel.SetActive(buyActive);
            }
        }

        if (sellPanel != null)
        {
            bool sellActive = mode == PriceMode.Sell;
            if (sellPanel.activeSelf != sellActive)
            {
                sellPanel.SetActive(sellActive);
            }
        }

        if (mode == PriceMode.Buy && costText != null)
        {
            costText.text = $"${price}";
        }
        else if (mode == PriceMode.Sell && sellPriceText != null)
        {
            sellPriceText.text = $"Sell Price: ${price}";
        }
    }

    private bool HasAncestorTooltipUI()
    {
        Transform parent = transform.parent;
        while (parent != null)
        {
            if (parent.GetComponent<TooltipUI>() != null)
            {
                return true;
            }
            parent = parent.parent;
        }
        return false;
    }

    private void CacheCanvas()
    {
        _rootCanvas = GetComponentInParent<Canvas>();

        if (_rootCanvas != null)
        {
            _rootCanvas = _rootCanvas.rootCanvas;
            _canvasRect =
                _rootCanvas.GetComponent<RectTransform>();
        }
    }

    private void PositionAtMouse()
    {
        if (_canvasRect == null)
        {
            CacheCanvas();
        }

        if (_canvasRect == null)
        {
            return;
        }

        Vector2 screenPos = GetMouseScreenPos();

        RectTransformUtility
            .ScreenPointToLocalPointInRectangle(
                _canvasRect,
                screenPos,
                _rootCanvas.renderMode
                    == RenderMode.ScreenSpaceOverlay
                    ? null
                    : _rootCanvas.worldCamera,
                out Vector2 localPos);

        Vector2 tooltipSize = _rect.rect.size;
        localPos.y +=
            cursorOffsetY
            + tooltipSize.y * (1f - _rect.pivot.y);
        Vector2 canvasSize = _canvasRect.rect.size;
        Vector2 halfCanvas = canvasSize * 0.5f;

        float minX =
            -halfCanvas.x + screenEdgePadding
            + tooltipSize.x * _rect.pivot.x;

        float maxX =
            halfCanvas.x - screenEdgePadding
            - tooltipSize.x * (1f - _rect.pivot.x);

        float minY =
            -halfCanvas.y + screenEdgePadding
            + tooltipSize.y * _rect.pivot.y;

        float maxY =
            halfCanvas.y - screenEdgePadding
            - tooltipSize.y * (1f - _rect.pivot.y);

        localPos.x = Mathf.Clamp(localPos.x, minX, maxX);
        localPos.y = Mathf.Clamp(localPos.y, minY, maxY);

        _rect.anchoredPosition = localPos;
    }

    private static Vector2 GetMouseScreenPos()
    {
#if ENABLE_INPUT_SYSTEM
        var mouse = Mouse.current;

        if (mouse != null)
        {
            return mouse.position.ReadValue();
        }

        return Vector2.zero;
#else
        return Input.mousePosition;
#endif
    }
}
