// Generated by Cursor (claude-4.6-opus) for jjmil on 2026-03-26.
// Updated: tooltip now follows the mouse cursor each frame.
// Updated 2026-03-27: screen-space center for shop confirm panel placement.
// Updated 2026-04-06 by Antigravity (claude-4.6-opus):
// added ElementType color label between title and description.
using TMPro;
using UnityEngine;
using UnityEngine.UI;

#if ENABLE_INPUT_SYSTEM
using UnityEngine.InputSystem;
#endif

/// <summary>
/// Attach to a tooltip panel root. Handles text content
/// and follows the mouse cursor while visible, with edge
/// clamping so the tooltip stays fully on-screen.
/// </summary>
[RequireComponent(typeof(CanvasGroup))]
public sealed class TooltipUI : MonoBehaviour
{
    [SerializeField] private TMP_Text nameText;
    [SerializeField] private TMP_Text typeText;
    [SerializeField] private TMP_Text descText;
    [SerializeField] private bool controllerInUse = false;
    [SerializeField] private Vector2 cachedVector;

    private RectTransform _rect;
    private Canvas _rootCanvas;
    private RectTransform _canvasRect;
    private CanvasGroup _canvasGroup;

    private const float cursorOffsetY = 40f;
    private const float screenEdgePadding = 12f;
    

    private void Awake()
    {
        _rect = GetComponent<RectTransform>();
        _canvasGroup = GetComponent<CanvasGroup>();
        _canvasGroup.blocksRaycasts = false;
        CacheCanvas();
        gameObject.SetActive(false);
    }

    private void LateUpdate()
    {
        if (!controllerInUse)
        {
            PositionAtMouse();
        } else
        {
            _rect.anchoredPosition = cachedVector;
        }
    }

    public void Show(
        string title,
        string description,
        ElementType elementType = ElementType.None)
    {
        if (nameText == null || descText == null)
        {
            return;
        }

        nameText.text = title;

        if (typeText != null)
        {
            string typeName = ElementTypeColors.GetDisplayName(elementType);
            Color typeColor =
                ElementTypeColors.GetColor(
                    elementType);
            typeText.text = typeName;
            typeText.color = typeColor;
        }

        descText.text =
            string.IsNullOrWhiteSpace(description)
                ? "No description."
                : description;

        gameObject.SetActive(true);
        _rect.SetAsLastSibling();

        LayoutRebuilder.ForceRebuildLayoutImmediate(
            _rect);
        PositionAtMouse();
        controllerInUse = false;
    }

    public void ShowAtPosition(string title, string description, Vector2 position, ElementType elementType = ElementType.None)
    {
        if (nameText == null || descText == null)
        {
            return;
        }

        nameText.text = title;

        if (typeText != null)
        {
            string typeName = ElementTypeColors.GetDisplayName(elementType);
            Color typeColor =
                ElementTypeColors.GetColor(
                    elementType);
            typeText.text = typeName;
            typeText.color = typeColor;
        }

        descText.text =
            string.IsNullOrWhiteSpace(description)
                ? "No description."
                : description;

        gameObject.SetActive(true);
        _rect.SetAsLastSibling();

        LayoutRebuilder.ForceRebuildLayoutImmediate(_rect);

        RectTransformUtility.ScreenPointToLocalPointInRectangle(
                _canvasRect,
                position,
                _rootCanvas.renderMode == RenderMode.ScreenSpaceOverlay ? null : _rootCanvas.worldCamera,
                out Vector2 localPos);


        Vector2 tooltipSize = _rect.rect.size;
        localPos.y +=
            cursorOffsetY
            + tooltipSize.y * (1f - _rect.pivot.y);
        Vector2 canvasSize = _canvasRect.rect.size;
        Vector2 halfCanvas = canvasSize * 0.5f;

        float minX =
            -halfCanvas.x + screenEdgePadding
            + tooltipSize.x * _rect.pivot.x;

        float maxX =
            halfCanvas.x - screenEdgePadding
            - tooltipSize.x * (1f - _rect.pivot.x);

        float minY =
            -halfCanvas.y + screenEdgePadding
            + tooltipSize.y * _rect.pivot.y;

        float maxY =
            halfCanvas.y - screenEdgePadding
            - tooltipSize.y * (1f - _rect.pivot.y);

        localPos.x = Mathf.Clamp(localPos.x, minX, maxX);
        localPos.y = Mathf.Clamp(localPos.y, minY, maxY);

        _rect.anchoredPosition = localPos;
        cachedVector = localPos;
        controllerInUse = true;
    }


    public void Hide()
    {
        if (gameObject.activeSelf)
        {
            gameObject.SetActive(false);
        }
    }

    public bool IsVisible => gameObject.activeSelf;

    /// <summary>
    /// Center of the tooltip rect in screen pixels (bottom-left origin).
    /// Used to align other UI (e.g. shop confirm) with the hover tooltip.
    /// </summary>
    public bool TryGetScreenRectCenterInScreenSpace(
        out Vector2 screenCenter)
    {
        screenCenter = default;

        if (!IsVisible || _rect == null)
        {
            return false;
        }

        if (_canvasRect == null)
        {
            CacheCanvas();
        }

        if (_canvasRect == null || _rootCanvas == null)
        {
            return false;
        }

        Camera cam =
            _rootCanvas.renderMode
                == RenderMode.ScreenSpaceOverlay
                ? null
                : _rootCanvas.worldCamera;

        Vector3[] corners = new Vector3[4];
        _rect.GetWorldCorners(corners);
        Vector2 a =
            RectTransformUtility.WorldToScreenPoint(
                cam, corners[0]);
        Vector2 b =
            RectTransformUtility.WorldToScreenPoint(
                cam, corners[2]);
        screenCenter = (a + b) * 0.5f;

        return true;
    }

    public void AssignReferences(
        TMP_Text name,
        TMP_Text type,
        TMP_Text desc)
    {
        nameText = name;
        typeText = type;
        descText = desc;
    }

    private void CacheCanvas()
    {
        _rootCanvas = GetComponentInParent<Canvas>();

        if (_rootCanvas != null)
        {
            _rootCanvas = _rootCanvas.rootCanvas;
            _canvasRect =
                _rootCanvas.GetComponent<RectTransform>();
        }
    }

    private void PositionAtMouse()
    {
        if (_canvasRect == null)
        {
            CacheCanvas();
        }

        if (_canvasRect == null)
        {
            return;
        }

        Vector2 screenPos = GetMouseScreenPos();

        RectTransformUtility
            .ScreenPointToLocalPointInRectangle(
                _canvasRect,
                screenPos,
                _rootCanvas.renderMode
                    == RenderMode.ScreenSpaceOverlay
                    ? null
                    : _rootCanvas.worldCamera,
                out Vector2 localPos);

        Vector2 tooltipSize = _rect.rect.size;
        localPos.y +=
            cursorOffsetY
            + tooltipSize.y * (1f - _rect.pivot.y);
        Vector2 canvasSize = _canvasRect.rect.size;
        Vector2 halfCanvas = canvasSize * 0.5f;

        float minX =
            -halfCanvas.x + screenEdgePadding
            + tooltipSize.x * _rect.pivot.x;

        float maxX =
            halfCanvas.x - screenEdgePadding
            - tooltipSize.x * (1f - _rect.pivot.x);

        float minY =
            -halfCanvas.y + screenEdgePadding
            + tooltipSize.y * _rect.pivot.y;

        float maxY =
            halfCanvas.y - screenEdgePadding
            - tooltipSize.y * (1f - _rect.pivot.y);

        localPos.x = Mathf.Clamp(localPos.x, minX, maxX);
        localPos.y = Mathf.Clamp(localPos.y, minY, maxY);

        _rect.anchoredPosition = localPos;
    }

    private static Vector2 GetMouseScreenPos()
    {
#if ENABLE_INPUT_SYSTEM
        var mouse = Mouse.current;

        if (mouse != null)
        {
            return mouse.position.ReadValue();
        }

        return Vector2.zero;
#else
        return Input.mousePosition;
#endif
    }
}
