// Generated by Cursor AI (GPT-5.2), user: jjmil, date: 2026-02-24

using UnityEngine;

[DisallowMultipleComponent]
[RequireComponent(typeof(RectTransform))]
public sealed class UIHoverBob : MonoBehaviour
{
    [Header("Bobbing")]
    [SerializeField] private float amplitudePixels = 8f;
    [SerializeField] private float frequencyHz = 1.5f;
    [SerializeField] private bool useUnscaledTime = true;
    [SerializeField] private bool randomizePhase = false;

    [Header("Rotation")]
    [SerializeField] private float rotationAmplitudeDegrees = 1.5f;
    [SerializeField] private float rotationFrequencyHz = 0.75f;
    [SerializeField] private float rotationPhaseOffset = 0.25f;

    private RectTransform _rectTransform;
    private Vector3 _baseAnchoredPosition;
    private Quaternion _baseLocalRotation;
    private float _phaseOffsetSeconds;

    private void Awake()
    {
        _rectTransform = GetComponent<RectTransform>();
    }

    private void OnEnable()
    {
        if (_rectTransform == null)
            _rectTransform = GetComponent<RectTransform>();

        _baseAnchoredPosition = _rectTransform.anchoredPosition3D;
        _baseLocalRotation = transform.localRotation;
        _phaseOffsetSeconds = randomizePhase ? Random.value : 0f;
    }

    private void Update()
    {
        if (_rectTransform == null)
            return;

        float time = useUnscaledTime ? Time.unscaledTime : Time.time;
        float seconds = time + _phaseOffsetSeconds;
        float angle = seconds * (Mathf.PI * 2f) * frequencyHz;
        float offsetY = Mathf.Sin(angle) * amplitudePixels;

        Vector3 pos = _baseAnchoredPosition;
        pos.y += offsetY;
        _rectTransform.anchoredPosition3D = pos;

        float rotationSeconds = seconds + rotationPhaseOffset;
        float rotationAngle = rotationSeconds * (Mathf.PI * 2f) * rotationFrequencyHz;
        float offsetZ = Mathf.Sin(rotationAngle) * rotationAmplitudeDegrees;
        transform.localRotation = _baseLocalRotation * Quaternion.Euler(0f, 0f, offsetZ);
    }

    private void OnDisable()
    {
        if (_rectTransform == null)
            return;

        _rectTransform.anchoredPosition3D = _baseAnchoredPosition;
        transform.localRotation = _baseLocalRotation;
    }
}

