#if UNITY_EDITOR
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

// Generated by Cursor AI for jjmil on 2026-03-09.

/// <summary>
/// Editor helper to create BoardComponentDefinition assets and link them to board component prefabs.
/// Access via menu: Tools > Board Components > Create Definitions + Link Prefabs
/// </summary>
public static class BoardComponentDefinitionSetupHelper
{
    private const string BoardComponentPrefabsPath = "Assets/Prefabs/Board Components/";
    private const string BoardComponentDefinitionsPath = "Assets/Scripts/BoardComponentDefinitions/";

    [MenuItem("Tools/Board Components/Create Definitions + Link Prefabs")]
    public static void CreateDefinitionsAndLinkPrefabs()
    {
        EnsureDirectoryExists(BoardComponentDefinitionsPath);

        string[] prefabGuids = AssetDatabase.FindAssets("t:Prefab", new[] { BoardComponentPrefabsPath });
        if (prefabGuids == null || prefabGuids.Length == 0)
        {
            Debug.LogWarning($"No prefabs found under {BoardComponentPrefabsPath}");
            return;
        }

        int created = 0;
        int updated = 0;
        int linked = 0;

        for (int i = 0; i < prefabGuids.Length; i++)
        {
            string prefabPath = AssetDatabase.GUIDToAssetPath(prefabGuids[i]);
            GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath);
            if (prefab == null)
            {
                continue;
            }

            string assetName = SanitizeAssetFileName(prefab.name);
            string defPath = $"{BoardComponentDefinitionsPath}{assetName}.asset";

            var def = AssetDatabase.LoadAssetAtPath<BoardComponentDefinition>(defPath);
            if (def == null)
            {
                def = ScriptableObject.CreateInstance<BoardComponentDefinition>();
                SetDefinitionDefaults(def, prefab, prefabPath);
                AssetDatabase.CreateAsset(def, defPath);
                created++;
            }
            else
            {
                bool changed = EnsureDefinitionReferencesPrefab(def, prefab);
                if (changed)
                {
                    updated++;
                }
            }

            bool didLink = EnsurePrefabHasLink(prefabPath, def);
            if (didLink)
            {
                linked++;
            }
        }

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        Debug.Log(
            $"Board component definitions: created={created}, updated={updated}, linkedPrefabs={linked}. " +
            $"Definitions path: {BoardComponentDefinitionsPath}");
    }

    [MenuItem("Tools/Board Components/Create New Definition (Selected Prefab)")]
    public static void CreateDefinitionFromSelection()
    {
        GameObject prefab = Selection.activeGameObject;
        if (prefab == null)
        {
            string prefabPath = AssetDatabase.GetAssetPath(Selection.activeObject);
            if (!string.IsNullOrEmpty(prefabPath) && prefabPath.EndsWith(".prefab"))
            {
                prefab = AssetDatabase.LoadAssetAtPath<GameObject>(prefabPath);
            }
        }

        if (prefab == null)
        {
            Debug.LogWarning("Select a board component prefab in the Project window.");
            return;
        }

        string prefabPathForDef = AssetDatabase.GetAssetPath(prefab);
        if (string.IsNullOrEmpty(prefabPathForDef) || !prefabPathForDef.StartsWith(BoardComponentPrefabsPath))
        {
            Debug.LogWarning($"Prefab must be under {BoardComponentPrefabsPath}");
            return;
        }

        EnsureDirectoryExists(BoardComponentDefinitionsPath);

        string assetName = SanitizeAssetFileName(prefab.name);
        string defPath = $"{BoardComponentDefinitionsPath}{assetName}.asset";

        var def = AssetDatabase.LoadAssetAtPath<BoardComponentDefinition>(defPath);
        if (def == null)
        {
            def = ScriptableObject.CreateInstance<BoardComponentDefinition>();
            SetDefinitionDefaults(def, prefab, prefabPathForDef);
            AssetDatabase.CreateAsset(def, defPath);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Debug.Log($"Created BoardComponentDefinition at {defPath}");
        }

        EnsurePrefabHasLink(prefabPathForDef, def);
        AssetDatabase.SaveAssets();
        Selection.activeObject = def;
        EditorGUIUtility.PingObject(def);
    }

    private static void SetDefinitionDefaults(
        BoardComponentDefinition def,
        GameObject prefab,
        string prefabPath)
    {
        if (def == null)
        {
            return;
        }

        var so = new SerializedObject(def);
        so.FindProperty("id").stringValue = prefab != null ? prefab.name : "";
        so.FindProperty("displayName").stringValue = prefab != null ? prefab.name : "Component";
        so.FindProperty("description").stringValue = "";
        so.FindProperty("componentType").enumValueIndex =
            (int)InferComponentType(prefab != null ? prefab.name : "", prefabPath);
        so.FindProperty("icon").objectReferenceValue =
            BoardComponentDefinitionUtilities.TryGetPrefabSpriteIcon(prefab);
        so.FindProperty("prefab").objectReferenceValue = prefab;
        so.FindProperty("baseScore").floatValue = 5f;
        so.ApplyModifiedPropertiesWithoutUndo();

        EditorUtility.SetDirty(def);
    }

    private static BoardComponentType InferComponentType(string prefabName, string prefabPath)
    {
        string lowerName = (prefabName ?? "").ToLowerInvariant();
        string lowerPath = (prefabPath ?? "").ToLowerInvariant();

        if (lowerName.Contains("bumper"))
        {
            return BoardComponentType.Bumper;
        }

        if (lowerName.Contains("target") || lowerPath.Contains("target"))
        {
            return BoardComponentType.Target;
        }

        if (lowerName.Contains("drop"))
        {
            return BoardComponentType.DropTarget;
        }

        if (lowerName.Contains("spinner"))
        {
            return BoardComponentType.Spinner;
        }

        if (lowerName.Contains("portal"))
        {
            return BoardComponentType.Portal;
        }

        if (lowerName.Contains("flipper"))
        {
            return BoardComponentType.Flipper;
        }

        if (lowerName.Contains("launcher"))
        {
            return BoardComponentType.Launcher;
        }

        if (lowerName.Contains("bomb") && !lowerName.Contains("bumper") && !lowerName.Contains("target"))
        {
            return BoardComponentType.Bomb;
        }

        if (lowerName.Contains("alien"))
        {
            return BoardComponentType.Alien;
        }

        return BoardComponentType.Other;
    }

    private static bool EnsureDefinitionReferencesPrefab(BoardComponentDefinition def, GameObject prefab)
    {
        if (def == null)
        {
            return false;
        }

        bool changed = false;
        var so = new SerializedObject(def);

        var prefabProp = so.FindProperty("prefab");
        if (prefabProp.objectReferenceValue == null && prefab != null)
        {
            prefabProp.objectReferenceValue = prefab;
            changed = true;
        }

        var iconProp = so.FindProperty("icon");
        if (iconProp.objectReferenceValue == null)
        {
            Sprite sprite = BoardComponentDefinitionUtilities.TryGetPrefabSpriteIcon(prefab);
            if (sprite != null)
            {
                iconProp.objectReferenceValue = sprite;
                changed = true;
            }
        }

        if (changed)
        {
            so.ApplyModifiedPropertiesWithoutUndo();
            EditorUtility.SetDirty(def);
        }

        return changed;
    }

    private static bool EnsurePrefabHasLink(string prefabPath, BoardComponentDefinition def)
    {
        if (string.IsNullOrWhiteSpace(prefabPath) || def == null)
        {
            return false;
        }

        GameObject root = PrefabUtility.LoadPrefabContents(prefabPath);
        if (root == null)
        {
            return false;
        }

        bool changed = false;

        BoardComponentDefinitionLink link = root.GetComponent<BoardComponentDefinitionLink>();
        if (link == null)
        {
            link = root.AddComponent<BoardComponentDefinitionLink>();
            changed = true;
        }

        var so = new SerializedObject(link);
        var defProp = so.FindProperty("definition");
        if (defProp.objectReferenceValue != def)
        {
            defProp.objectReferenceValue = def;
            changed = true;
        }

        if (changed)
        {
            so.ApplyModifiedPropertiesWithoutUndo();
            PrefabUtility.SaveAsPrefabAsset(root, prefabPath);
        }

        PrefabUtility.UnloadPrefabContents(root);
        return changed;
    }

    private static void EnsureDirectoryExists(string assetPathWithTrailingSlash)
    {
        if (!AssetDatabase.IsValidFolder(assetPathWithTrailingSlash.TrimEnd('/')))
        {
            string parent = Path.GetDirectoryName(assetPathWithTrailingSlash.TrimEnd('/'));
            string folderName = Path.GetFileName(assetPathWithTrailingSlash.TrimEnd('/'));

            if (!string.IsNullOrEmpty(parent) && !string.IsNullOrEmpty(folderName))
            {
                if (!AssetDatabase.IsValidFolder(parent))
                {
                    EnsureDirectoryExists(parent + "/");
                }

                AssetDatabase.CreateFolder(parent, folderName);
            }
        }
    }

    private static string SanitizeAssetFileName(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            return "Component";
        }

        foreach (char c in Path.GetInvalidFileNameChars())
        {
            name = name.Replace(c.ToString(), "_");
        }

        return name.Replace(" ", "_");
    }
}
#endif
