// Generated by Cursor AI for jjmil on 2026-03-12.
#if UNITY_EDITOR
using System.Collections.Generic;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using TMPro;

/// <summary>
/// Editor tool to mass-change fonts in all TextMeshPro texts across prefabs and scenes.
/// Access via menu: Tools > TextMeshPro > Mass Font Changer
/// </summary>
public class MassFontChanger : EditorWindow
{
    private TMP_FontAsset _newFont;
    private TMP_FontAsset _replaceOnlyFont; // optional: only change texts using this font
    private bool _includePrefabs = true;
    private bool _includeScenes = true;
    private string _searchPath = "Assets";
    private Vector2 _scrollPos;
    private string _log = "";
    private bool _onlySelected;

    [MenuItem("Tools/TextMeshPro/Mass Font Changer")]
    public static void ShowWindow()
    {
        var w = GetWindow<MassFontChanger>("Mass Font Changer");
        w.minSize = new Vector2(360, 320);
    }

    private void OnGUI()
    {
        _scrollPos = EditorGUILayout.BeginScrollView(_scrollPos);

        EditorGUILayout.Space(6);
        EditorGUILayout.LabelField("Mass Font Changer", EditorStyles.boldLabel);
        EditorGUILayout.HelpBox(
            "Replace fonts in all TMP_Text/TextMeshProUGUI components across prefabs and scenes.",
            MessageType.Info);
        EditorGUILayout.Space(4);

        _newFont = (TMP_FontAsset)EditorGUILayout.ObjectField("New Font", _newFont, typeof(TMP_FontAsset), false);
        _replaceOnlyFont = (TMP_FontAsset)EditorGUILayout.ObjectField(
            "Replace Only (optional)",
            _replaceOnlyFont,
            typeof(TMP_FontAsset),
            false);
        if (_replaceOnlyFont != null)
        {
            EditorGUILayout.HelpBox("If set, only texts currently using this font will be changed.", MessageType.None);
        }

        EditorGUILayout.Space(6);
        EditorGUILayout.LabelField("Scope", EditorStyles.boldLabel);
        _includePrefabs = EditorGUILayout.Toggle("Include Prefabs", _includePrefabs);
        _includeScenes = EditorGUILayout.Toggle("Include Scenes", _includeScenes);
        _onlySelected = EditorGUILayout.Toggle("Only Selected Objects", _onlySelected);
        _searchPath = EditorGUILayout.TextField("Search Path", _searchPath);

        EditorGUILayout.Space(8);

        GUI.enabled = _newFont != null;
        if (GUILayout.Button("Apply Font to All TMP Texts", GUILayout.Height(32)))
        {
            ApplyFont();
        }
        GUI.enabled = true;

        EditorGUILayout.Space(8);
        EditorGUILayout.LabelField("Log", EditorStyles.boldLabel);
        EditorGUILayout.TextArea(_log, GUILayout.MinHeight(80));

        EditorGUILayout.EndScrollView();
    }

    private void ApplyFont()
    {
        _log = "";
        int totalChanged = 0;
        int totalSkipped = 0;

        if (_onlySelected && Selection.gameObjects.Length > 0)
        {
            foreach (GameObject go in Selection.gameObjects)
            {
                int c, s;
                ChangeFontInHierarchy(go.transform, out c, out s);
                totalChanged += c;
                totalSkipped += s;
            }
            Log($"Selection: changed {totalChanged}, skipped {totalSkipped}");
        }
        else
        {
            if (_includePrefabs)
            {
                string[] guids = AssetDatabase.FindAssets("t:Prefab", new[] { _searchPath });
                foreach (string guid in guids)
                {
                    string path = AssetDatabase.GUIDToAssetPath(guid);
                    int c, s;
                    ChangeFontInPrefab(path, out c, out s);
                    totalChanged += c;
                    totalSkipped += s;
                }
            }

            if (_includeScenes)
            {
                string[] guids = AssetDatabase.FindAssets("t:Scene", new[] { _searchPath });
                string currentScene = SceneManager.GetActiveScene().path;
                foreach (string guid in guids)
                {
                    string path = AssetDatabase.GUIDToAssetPath(guid);
                    int c, s;
                    ChangeFontInScene(path, out c, out s);
                    totalChanged += c;
                    totalSkipped += s;
                }
                if (!string.IsNullOrEmpty(currentScene))
                {
                    EditorSceneManager.OpenScene(currentScene);
                }
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            Log($"Total: changed {totalChanged}, skipped {totalSkipped}");
        }

        Repaint();
    }

    private void ChangeFontInPrefab(string prefabPath, out int changed, out int skipped)
    {
        changed = 0;
        skipped = 0;
        GameObject root = PrefabUtility.LoadPrefabContents(prefabPath);
        if (root == null) return;

        ChangeFontInHierarchy(root.transform, out changed, out skipped);
        if (changed > 0)
        {
            PrefabUtility.SaveAsPrefabAsset(root, prefabPath);
            Log($"Prefab: {prefabPath} — {changed} changed");
        }
        PrefabUtility.UnloadPrefabContents(root);
    }

    private void ChangeFontInScene(string scenePath, out int changed, out int skipped)
    {
        changed = 0;
        skipped = 0;
        Scene scene = EditorSceneManager.OpenScene(scenePath, OpenSceneMode.Single);
        if (!scene.IsValid()) return;

        GameObject[] roots = scene.GetRootGameObjects();
        foreach (GameObject root in roots)
        {
            int c, s;
            ChangeFontInHierarchy(root.transform, out c, out s);
            changed += c;
            skipped += s;
        }
        if (changed > 0)
        {
            EditorSceneManager.SaveScene(scene);
            Log($"Scene: {scenePath} — {changed} changed");
        }
    }

    private void ChangeFontInHierarchy(Transform root, out int changed, out int skipped)
    {
        changed = 0;
        skipped = 0;
        TMP_Text[] texts = root.GetComponentsInChildren<TMP_Text>(true);
        foreach (TMP_Text t in texts)
        {
            if (_replaceOnlyFont != null && t.font != _replaceOnlyFont)
            {
                skipped++;
                continue;
            }
            if (t.font == _newFont)
            {
                skipped++;
                continue;
            }
            Undo.RecordObject(t, "Mass Font Change");
            t.font = _newFont;
            changed++;
        }
    }

    private void Log(string msg)
    {
        _log += msg + "\n";
    }
}
#endif
