#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using UnityEngine;

// Generated by Gemini (Antigravity) for jjmil on 2026-04-07.

/// <summary>
/// Editor tool that detects scripts, models, materials, prefabs, and other
/// assets inside Assets/ that are not referenced by any scene, prefab,
/// ScriptableObject, or other asset.
///
/// Menu:
///   Tools > Assets > Find Unreferenced Assets
///   Tools > Assets > Find Unreferenced Assets (Save Report)
///   Tools > Assets > Move Unreferenced Assets to _Unused
///
/// Limitations:
///   - Cannot detect references made purely through C# code
///     (e.g. typeof(), reflection, string-based Instantiate).
///   - Resources.Load and Addressable entries are flagged separately
///     rather than marked unreferenced.
/// </summary>
public static class UnreferencedAssetDetector
{
    private const string ReportDirectory = "Assets/_Reports";
    private const string ReportFileName = "UnreferencedAssets.txt";
    private const string UnusedDirectory = "Assets/_Unused";

    private static readonly string[] excludedDirectories = new string[]
    {
        "Assets/Plugins/",
        "Assets/TextMesh Pro/",
        "Assets/QuickOutline/",
        "Assets/FMOD Banks/",
        "Assets/AddressableAssetsData/",
        "Assets/StreamingAssets/",
        "Assets/_Recovery/",
        "Assets/TutorialInfo/",
        "Assets/Editor/",
        "Assets/_Reports/",
        "Assets/_Unused/"
    };

    private static readonly string[] candidateTypeFilters = new string[]
    {
        "t:Model",
        "t:Material",
        "t:Prefab",
        "t:ScriptableObject",
        "t:Shader",
        "t:Texture",
        "t:AudioClip",
        "t:AnimationClip",
        "t:Font",
        "t:Mesh",
        "t:ShaderGraph"
    };

    // ----------------------------------------------------------------
    // Menu Items
    // ----------------------------------------------------------------

    [MenuItem("Tools/Assets/Find Unreferenced Assets")]
    public static void FindUnreferencedAssets()
    {
        RunDetection(saveReport: false, moveAssets: false);
    }

    [MenuItem("Tools/Assets/Find Unreferenced Assets (Save Report)")]
    public static void FindUnreferencedAssetsSaveReport()
    {
        RunDetection(saveReport: true, moveAssets: false);
    }

    [MenuItem("Tools/Assets/Move Unreferenced Assets to _Unused")]
    public static void MoveUnreferencedAssets()
    {
        bool confirm = EditorUtility.DisplayDialog(
            "Move Unreferenced Assets",
            "This will scan for unreferenced assets and move them to "
            + "Assets/_Unused/.\n\n"
            + "Assets in Resources/ and Addressable groups will NOT be "
            + "moved.\n\nContinue?",
            "Move",
            "Cancel");

        if (!confirm)
        {
            return;
        }

        RunDetection(saveReport: true, moveAssets: true);
    }

    // ----------------------------------------------------------------
    // Core Detection
    // ----------------------------------------------------------------

    private static void RunDetection(
        bool saveReport,
        bool moveAssets)
    {
        EditorUtility.DisplayProgressBar(
            "Unreferenced Asset Detector",
            "Collecting candidate assets...",
            0f);

        try
        {
            HashSet<string> candidates = CollectCandidateAssets();
            HashSet<string> resourcesAssets = new HashSet<string>();
            HashSet<string> addressableAssets = CollectAddressableAssets();

            SeparateResourcesAssets(candidates, resourcesAssets);

            EditorUtility.DisplayProgressBar(
                "Unreferenced Asset Detector",
                "Building reference graph from scenes...",
                0.2f);

            HashSet<string> referencedAssets =
                BuildReferencedSet();

            EditorUtility.DisplayProgressBar(
                "Unreferenced Asset Detector",
                "Cross-referencing...",
                0.8f);

            List<string> unreferenced = candidates
                .Where(path => !referencedAssets.Contains(path))
                .Where(path => !addressableAssets.Contains(path))
                .OrderBy(path => path)
                .ToList();

            Dictionary<string, List<string>> categorized =
                CategorizeAssets(unreferenced);

            LogResults(
                categorized,
                resourcesAssets,
                addressableAssets,
                candidates.Count);

            if (saveReport)
            {
                SaveReport(
                    categorized,
                    resourcesAssets,
                    addressableAssets,
                    candidates.Count);
            }

            if (moveAssets)
            {
                MoveAssetsToUnused(unreferenced);
            }
        }
        finally
        {
            EditorUtility.ClearProgressBar();
        }
    }

    // ----------------------------------------------------------------
    // Step 1: Collect Candidates
    // ----------------------------------------------------------------

    private static HashSet<string> CollectCandidateAssets()
    {
        HashSet<string> candidates = new HashSet<string>();

        foreach (string filter in candidateTypeFilters)
        {
            string[] guids = AssetDatabase.FindAssets(
                filter,
                new[] { "Assets" });

            foreach (string guid in guids)
            {
                string path = AssetDatabase.GUIDToAssetPath(guid);

                if (IsExcluded(path))
                {
                    continue;
                }

                if (path.EndsWith(".meta"))
                {
                    continue;
                }

                candidates.Add(path);
            }
        }

        return candidates;
    }

    private static void SeparateResourcesAssets(
        HashSet<string> candidates,
        HashSet<string> resourcesAssets)
    {
        List<string> toRemove = new List<string>();

        foreach (string path in candidates)
        {
            if (IsInsideResourcesFolder(path))
            {
                resourcesAssets.Add(path);
                toRemove.Add(path);
            }
        }

        foreach (string path in toRemove)
        {
            candidates.Remove(path);
        }
    }

    // ----------------------------------------------------------------
    // Step 2: Build Referenced Set
    // ----------------------------------------------------------------

    private static HashSet<string> BuildReferencedSet()
    {
        HashSet<string> referenced = new HashSet<string>();

        string[] sceneGuids = AssetDatabase.FindAssets(
            "t:Scene",
            new[] { "Assets" });

        List<string> seedPaths = new List<string>();

        foreach (string guid in sceneGuids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);

            if (!IsExcluded(path))
            {
                seedPaths.Add(path);
            }
        }

        string[] prefabGuids = AssetDatabase.FindAssets(
            "t:Prefab",
            new[] { "Assets" });

        foreach (string guid in prefabGuids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);

            if (!IsExcluded(path))
            {
                seedPaths.Add(path);
            }
        }

        string[] soGuids = AssetDatabase.FindAssets(
            "t:ScriptableObject",
            new[] { "Assets" });

        foreach (string guid in soGuids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);

            if (!IsExcluded(path))
            {
                seedPaths.Add(path);
            }
        }

        int total = seedPaths.Count;

        for (int i = 0; i < total; i++)
        {
            if (i % 50 == 0)
            {
                float progress = 0.2f + (0.6f * i / total);

                EditorUtility.DisplayProgressBar(
                    "Unreferenced Asset Detector",
                    $"Resolving dependencies ({i}/{total})...",
                    progress);
            }

            string[] dependencies = AssetDatabase.GetDependencies(
                seedPaths[i],
                true);

            foreach (string dep in dependencies)
            {
                referenced.Add(dep);
            }
        }

        return referenced;
    }

    // ----------------------------------------------------------------
    // Step 3: Addressables
    // ----------------------------------------------------------------

    private static HashSet<string> CollectAddressableAssets()
    {
        HashSet<string> addressable = new HashSet<string>();

        AddressableAssetSettings settings =
            AddressableAssetSettingsDefaultObject.Settings;

        if (settings == null)
        {
            return addressable;
        }

        foreach (AddressableAssetGroup group in settings.groups)
        {
            if (group == null)
            {
                continue;
            }

            foreach (AddressableAssetEntry entry in group.entries)
            {
                if (entry == null)
                {
                    continue;
                }

                string path = AssetDatabase.GUIDToAssetPath(entry.guid);

                if (!string.IsNullOrEmpty(path))
                {
                    addressable.Add(path);
                }
            }
        }

        return addressable;
    }

    // ----------------------------------------------------------------
    // Categorization
    // ----------------------------------------------------------------

    private static Dictionary<string, List<string>> CategorizeAssets(
        List<string> paths)
    {
        Dictionary<string, List<string>> categories =
            new Dictionary<string, List<string>>
            {
                { "Scripts", new List<string>() },
                { "Models", new List<string>() },
                { "Materials", new List<string>() },
                { "Prefabs", new List<string>() },
                { "ScriptableObjects", new List<string>() },
                { "Textures/Sprites", new List<string>() },
                { "Shaders", new List<string>() },
                { "Audio", new List<string>() },
                { "Animations", new List<string>() },
                { "Fonts", new List<string>() },
                { "Other", new List<string>() }
            };

        foreach (string path in paths)
        {
            string ext = Path.GetExtension(path).ToLower();
            string category = GetCategory(ext, path);
            categories[category].Add(path);
        }

        return categories;
    }

    private static string GetCategory(string extension, string path)
    {
        switch (extension)
        {
            case ".cs":
                return "Scripts";

            case ".fbx":
            case ".obj":
            case ".blend":
            case ".dae":
            case ".3ds":
            case ".max":
                return "Models";

            case ".mat":
                return "Materials";

            case ".prefab":
                return "Prefabs";

            case ".asset":
                return "ScriptableObjects";

            case ".png":
            case ".jpg":
            case ".jpeg":
            case ".tga":
            case ".psd":
            case ".exr":
            case ".hdr":
            case ".bmp":
            case ".tif":
            case ".tiff":
            case ".renderTexture":
                return "Textures/Sprites";

            case ".shader":
            case ".shadergraph":
            case ".shadersubgraph":
            case ".hlsl":
            case ".cginc":
                return "Shaders";

            case ".wav":
            case ".mp3":
            case ".ogg":
            case ".aiff":
            case ".bank":
                return "Audio";

            case ".anim":
            case ".controller":
            case ".overrideController":
                return "Animations";

            case ".ttf":
            case ".otf":
            case ".fontsettings":
                return "Fonts";

            default:
                return "Other";
        }
    }

    // ----------------------------------------------------------------
    // Console Output
    // ----------------------------------------------------------------

    private static void LogResults(
        Dictionary<string, List<string>> categorized,
        HashSet<string> resourcesAssets,
        HashSet<string> addressableAssets,
        int totalCandidates)
    {
        int unreferencedCount = categorized.Values
            .Sum(list => list.Count);

        Debug.Log(
            "<b>[Unreferenced Asset Detector]</b> Scan complete.\n"
            + $"  Total candidates scanned: {totalCandidates}\n"
            + $"  Unreferenced assets found: {unreferencedCount}\n"
            + $"  Resources/ assets (skipped): "
            + $"{resourcesAssets.Count}\n"
            + $"  Addressable entries (skipped): "
            + $"{addressableAssets.Count}");

        foreach (var kvp in categorized)
        {
            if (kvp.Value.Count == 0)
            {
                continue;
            }

            StringBuilder sb = new StringBuilder();
            sb.AppendLine(
                $"<b>[Unreferenced — {kvp.Key}]</b> "
                + $"({kvp.Value.Count}):");

            foreach (string path in kvp.Value)
            {
                sb.AppendLine($"  • {path}");
            }

            Debug.LogWarning(sb.ToString());
        }

        if (unreferencedCount == 0)
        {
            Debug.Log(
                "<b>[Unreferenced Asset Detector]</b> "
                + "No unreferenced assets found. Project is clean!");
        }
    }

    // ----------------------------------------------------------------
    // Report File
    // ----------------------------------------------------------------

    private static void SaveReport(
        Dictionary<string, List<string>> categorized,
        HashSet<string> resourcesAssets,
        HashSet<string> addressableAssets,
        int totalCandidates)
    {
        int unreferencedCount = categorized.Values
            .Sum(list => list.Count);

        StringBuilder report = new StringBuilder();
        report.AppendLine(
            "========================================");
        report.AppendLine(
            " UNREFERENCED ASSET DETECTOR — REPORT");
        report.AppendLine(
            $" Generated: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        report.AppendLine(
            "========================================");
        report.AppendLine();
        report.AppendLine(
            $"Total candidates scanned: {totalCandidates}");
        report.AppendLine(
            $"Unreferenced assets found: {unreferencedCount}");
        report.AppendLine(
            $"Resources/ assets (skipped): "
            + $"{resourcesAssets.Count}");
        report.AppendLine(
            $"Addressable entries (skipped): "
            + $"{addressableAssets.Count}");
        report.AppendLine();

        foreach (var kvp in categorized)
        {
            if (kvp.Value.Count == 0)
            {
                continue;
            }

            report.AppendLine(
                $"--- {kvp.Key} ({kvp.Value.Count}) ---");

            foreach (string path in kvp.Value)
            {
                report.AppendLine($"  {path}");
            }

            report.AppendLine();
        }

        if (resourcesAssets.Count > 0)
        {
            report.AppendLine(
                $"--- Resources/ (potentially referenced "
                + $"at runtime) ({resourcesAssets.Count} assets skipped) ---");
            report.AppendLine();
        }

        if (addressableAssets.Count > 0)
        {
            report.AppendLine(
                $"--- Addressable Entries (potentially "
                + $"referenced) ({addressableAssets.Count} assets skipped) ---");
            report.AppendLine();
        }

        EnsureDirectoryExists(ReportDirectory);

        string fullPath =
            Path.Combine(ReportDirectory, ReportFileName);

        File.WriteAllText(fullPath, report.ToString());
        AssetDatabase.Refresh();

        Debug.Log(
            $"<b>[Unreferenced Asset Detector]</b> "
            + $"Report saved to {fullPath}");

        EditorUtility.RevealInFinder(fullPath);
    }

    // ----------------------------------------------------------------
    // Move to _Unused
    // ----------------------------------------------------------------

    private static void MoveAssetsToUnused(List<string> unreferenced)
    {
        if (unreferenced.Count == 0)
        {
            Debug.Log(
                "<b>[Unreferenced Asset Detector]</b> "
                + "No assets to move.");
            return;
        }

        EnsureDirectoryExists(UnusedDirectory);

        int moved = 0;
        int failed = 0;

        for (int i = 0; i < unreferenced.Count; i++)
        {
            string source = unreferenced[i];

            if (i % 10 == 0)
            {
                float progress = (float)i / unreferenced.Count;

                EditorUtility.DisplayProgressBar(
                    "Moving Unreferenced Assets",
                    $"Moving ({i}/{unreferenced.Count})...",
                    progress);
            }

            string relativePath =
                source.Substring("Assets/".Length);

            string destination =
                $"{UnusedDirectory}/{relativePath}";

            string destinationDir =
                Path.GetDirectoryName(destination);

            if (!string.IsNullOrEmpty(destinationDir))
            {
                EnsureDirectoryExists(
                    destinationDir.Replace("\\", "/"));
            }

            string result =
                AssetDatabase.MoveAsset(source, destination);

            if (string.IsNullOrEmpty(result))
            {
                moved++;
            }
            else
            {
                Debug.LogWarning(
                    $"Failed to move {source}: {result}");
                failed++;
            }
        }

        AssetDatabase.Refresh();

        Debug.Log(
            $"<b>[Unreferenced Asset Detector]</b> "
            + $"Moved {moved} assets to {UnusedDirectory}/. "
            + $"Failed: {failed}.");
    }

    // ----------------------------------------------------------------
    // Utility
    // ----------------------------------------------------------------

    private static bool IsExcluded(string path)
    {
        foreach (string excluded in excludedDirectories)
        {
            if (path.StartsWith(
                excluded,
                StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsInsideResourcesFolder(string path)
    {
        return path.Contains("/Resources/")
            || path.StartsWith(
                "Assets/Resources/",
                StringComparison.OrdinalIgnoreCase);
    }

    private static void EnsureDirectoryExists(string assetPath)
    {
        string normalized = assetPath.Replace("\\", "/")
            .TrimEnd('/');

        if (AssetDatabase.IsValidFolder(normalized))
        {
            return;
        }

        string parent = Path.GetDirectoryName(normalized)?
            .Replace("\\", "/");

        string folderName = Path.GetFileName(normalized);

        if (string.IsNullOrEmpty(parent)
            || string.IsNullOrEmpty(folderName))
        {
            return;
        }

        if (!AssetDatabase.IsValidFolder(parent))
        {
            EnsureDirectoryExists(parent);
        }

        AssetDatabase.CreateFolder(parent, folderName);
    }
}
#endif
