// Generated by Antigravity (Claude Opus 4.6), for jjmil, on 2026-04-06.
// Balatro-style color-wash transition for board background
// material when entering Angel / Devil modifier rounds.
using System.Collections;
using UnityEngine;
using UnityEngine.Rendering;
using UnityEngine.SceneManagement;

[DisallowMultipleComponent]
public sealed class BoardBackgroundMaterialSwitcher : MonoBehaviour
{
    [Header("Target")]
    [Tooltip(
        "Renderer whose material will be swapped " +
        "(ex: the board background mesh).")]
    [SerializeField] private Renderer targetRenderer;

    [Tooltip("Which material slot to replace on the renderer.")]
    [SerializeField] private int materialSlotIndex = 0;

    [Header("Materials")]
    [SerializeField] private Material normalMaterial;
    [SerializeField] private Material devilMaterial;

    [Header("Transition Timing")]
    [Tooltip("Total duration of the wash transition in seconds.")]
    [SerializeField] private float transitionDuration = 0.9f;

    [Tooltip(
        "Fraction of the total duration spent fading IN " +
        "to the wash color (0-1).")]
    [Range(0.1f, 0.8f)]
    [SerializeField] private float fadeInFraction = 0.4f;

    [Tooltip(
        "Fraction of the total duration spent holding " +
        "solid wash color at the midpoint (0-0.5).")]
    [Range(0f, 0.5f)]
    [SerializeField] private float holdFraction = 0.08f;

    [Tooltip("Easing curve for the fade-in phase.")]
    [SerializeField] private AnimationCurve fadeInCurve =
        AnimationCurve.EaseInOut(0f, 0f, 1f, 1f);

    [Tooltip("Easing curve for the fade-out phase.")]
    [SerializeField] private AnimationCurve fadeOutCurve =
        AnimationCurve.EaseInOut(0f, 0f, 1f, 1f);

    [Header("Wash Colors")]
    [SerializeField] private Color devilWashColor =
        new Color(0.45f, 0.08f, 0.12f, 1f);

    [SerializeField] private Color normalWashColor =
        new Color(0.12f, 0.1f, 0.22f, 1f);

    [Header("Overlay Positioning")]
    [Tooltip(
        "Local-space offset that pushes the wash overlay " +
        "in front of the background mesh. Adjust the axis " +
        "that faces the camera.")]
    [SerializeField] private Vector3 overlayOffset =
        new Vector3(0f, 0f, -0.01f);

    private GameRulesManager _rules;
    private RoundType _lastAppliedType = (RoundType)(-1);
    private Coroutine _activeTransition;

    private GameObject _overlayObject;
    private MeshRenderer _overlayRenderer;
    private Material _overlayMaterial;

    private static readonly int colorPropertyId =
        Shader.PropertyToID("_Color");

    private void Awake()
    {
        if (targetRenderer == null)
        {
            targetRenderer = GetComponent<Renderer>();
        }
    }

    private void OnEnable()
    {
        EnsureOverlayCreated();
        ResolveRules();
        Hook();

        SceneManager.sceneLoaded += OnSceneLoaded;

        ApplyImmediate(GetCurrentRoundType());
    }

    private void OnDisable()
    {
        SceneManager.sceneLoaded -= OnSceneLoaded;
        Unhook();
        DestroyOverlay();
    }

    private void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        ResolveRules();
        Hook();

        ApplyImmediate(GetCurrentRoundType());
    }

    private void ResolveRules()
    {
        if (_rules != null) return;

        _rules = ServiceLocator.Get<GameRulesManager>();
    }

    private void Hook()
    {
        if (_rules == null) return;

        _rules.RoundStarted -= OnRoundStarted;
        _rules.RoundStarted += OnRoundStarted;

        _rules.LevelChanged -= OnLevelChanged;
        _rules.LevelChanged += OnLevelChanged;
    }

    private void Unhook()
    {
        if (_rules == null) return;

        _rules.RoundStarted -= OnRoundStarted;
        _rules.LevelChanged -= OnLevelChanged;
    }

    private void OnRoundStarted()
    {
        TransitionTo(GetCurrentRoundType());
    }

    private void OnLevelChanged()
    {
        TransitionTo(GetCurrentRoundType());
    }

    [ContextMenu("Refresh Background Material Now")]
    public void RefreshNow()
    {
        ApplyImmediate(GetCurrentRoundType());
    }

    private RoundType GetCurrentRoundType()
    {
        var controller =
            ServiceLocator.Get<RoundModifierController>();
        var roundData = controller?.CurrentRoundData;

        return roundData?.type ?? RoundType.Normal;
    }

    private Material ResolveMaterial(RoundType type)
    {
        switch (type)
        {
            case RoundType.Devil:
                // Prioritize the specific material on the active modifier if it exists
                var controller = ServiceLocator.Get<RoundModifierController>();
                if (controller != null && controller.ActiveModifier != null && controller.ActiveModifier.backgroundMaterial != null)
                {
                    return controller.ActiveModifier.backgroundMaterial;
                }
                return devilMaterial != null ? devilMaterial : normalMaterial;
            case RoundType.Normal:
            default:
                return normalMaterial;
        }
    }

    private Color ResolveWashColor(RoundType type)
    {
        switch (type)
        {
            case RoundType.Devil:  return devilWashColor;
            case RoundType.Normal:
            default:               return normalWashColor;
        }
    }

    /// <summary>
    /// Immediately sets the material with no transition.
    /// Used on first load and scene changes.
    /// </summary>
    private void ApplyImmediate(RoundType type)
    {
        if (targetRenderer == null) return;

        StopActiveTransition();
        HideOverlay();

        Material target = ResolveMaterial(type);
        if (target == null) return;

        SetMaterialSlot(target);
        _lastAppliedType = type;
    }

    /// <summary>
    /// Starts the Balatro-style wash transition to the
    /// material belonging to <paramref name="type"/>.
    /// </summary>
    private void TransitionTo(RoundType type)
    {
        if (targetRenderer == null) return;
        if (type == _lastAppliedType) return;

        Material target = ResolveMaterial(type);
        if (target == null)
        {
            ApplyImmediate(type);
            return;
        }

        float duration =
            Mathf.Max(0f, transitionDuration);

        if (duration <= 0f)
        {
            ApplyImmediate(type);
            return;
        }

        EnsureOverlayCreated();

        if (_overlayMaterial == null)
        {
            ApplyImmediate(type);
            return;
        }

        StopActiveTransition();
        _lastAppliedType = type;

        Color washColor = ResolveWashColor(type);

        _activeTransition = StartCoroutine(
            WashTransitionRoutine(
                target, washColor, duration));
    }

    /// <summary>
    /// Wash routine:
    ///  1. Fade overlay wash color in (alpha 0 → 1).
    ///  2. Hold at full opacity briefly.
    ///  3. Swap the base material underneath.
    ///  4. Fade overlay wash color out (alpha 1 → 0).
    /// </summary>
    private IEnumerator WashTransitionRoutine(
        Material targetMaterial,
        Color washColor,
        float totalDuration)
    {
        float fadeInTime =
            totalDuration * Mathf.Clamp01(fadeInFraction);
        float holdTime =
            totalDuration * Mathf.Clamp01(holdFraction);
        float fadeOutTime =
            totalDuration - fadeInTime - holdTime;

        fadeOutTime = Mathf.Max(0.05f, fadeOutTime);

        if (_overlayObject != null)
        {
            _overlayObject.SetActive(true);
        }

        // Phase 1: Fade wash IN
        float elapsed = 0f;

        while (elapsed < fadeInTime)
        {
            elapsed += Time.deltaTime;

            float raw =
                Mathf.Clamp01(elapsed / fadeInTime);
            float t = (fadeInCurve != null &&
                       fadeInCurve.length > 0)
                ? fadeInCurve.Evaluate(raw)
                : raw;

            Color c = washColor;
            c.a = t;
            _overlayMaterial.SetColor(colorPropertyId, c);

            yield return null;
        }

        // Peak: solid wash color
        Color solid = washColor;
        solid.a = 1f;
        _overlayMaterial.SetColor(colorPropertyId, solid);

        // Phase 2: Hold at full opacity
        if (holdTime > 0f)
        {
            yield return new WaitForSeconds(holdTime);
        }

        // Swap the actual base material underneath the wash
        SetMaterialSlot(targetMaterial);

        // Phase 3: Fade wash OUT
        elapsed = 0f;

        while (elapsed < fadeOutTime)
        {
            elapsed += Time.deltaTime;

            float raw =
                Mathf.Clamp01(elapsed / fadeOutTime);
            float t = (fadeOutCurve != null &&
                       fadeOutCurve.length > 0)
                ? fadeOutCurve.Evaluate(raw)
                : raw;

            Color c = washColor;
            c.a = 1f - t;
            _overlayMaterial.SetColor(colorPropertyId, c);

            yield return null;
        }

        HideOverlay();
        _activeTransition = null;
    }

    private void EnsureOverlayCreated()
    {
        if (_overlayObject != null) return;
        if (targetRenderer == null) return;

        MeshFilter sourceMeshFilter =
            targetRenderer.GetComponent<MeshFilter>();

        if (sourceMeshFilter == null ||
            sourceMeshFilter.sharedMesh == null)
        {
            return;
        }

        _overlayObject =
            new GameObject("BG_Wash_Overlay");

        _overlayObject.transform.SetParent(
            targetRenderer.transform, false);

        _overlayObject.transform.localPosition =
            overlayOffset;
        _overlayObject.transform.localRotation =
            Quaternion.identity;
        _overlayObject.transform.localScale =
            Vector3.one;

        MeshFilter overlayMesh =
            _overlayObject.AddComponent<MeshFilter>();
        overlayMesh.sharedMesh =
            sourceMeshFilter.sharedMesh;

        _overlayRenderer =
            _overlayObject.AddComponent<MeshRenderer>();

        Shader shader =
            Shader.Find("Sprites/Default");

        if (shader == null)
        {
            shader = Shader.Find("UI/Default");
        }

        if (shader == null)
        {
            Debug.LogWarning(
                "[BoardBackgroundMaterialSwitcher] " +
                "Could not find a transparent shader " +
                "for the wash overlay.");
            Destroy(_overlayObject);
            _overlayObject = null;
            return;
        }

        _overlayMaterial = new Material(shader);
        _overlayMaterial.name = "BG_Wash_Material";
        _overlayMaterial.renderQueue =
            (int)RenderQueue.Transparent;

        Color initialColor = Color.clear;
        _overlayMaterial.SetColor(
            colorPropertyId, initialColor);

        _overlayRenderer.sharedMaterial = _overlayMaterial;
        _overlayRenderer.shadowCastingMode =
            ShadowCastingMode.Off;
        _overlayRenderer.receiveShadows = false;

        _overlayObject.SetActive(false);
    }

    private void HideOverlay()
    {
        if (_overlayMaterial != null)
        {
            _overlayMaterial.SetColor(
                colorPropertyId, Color.clear);
        }

        if (_overlayObject != null)
        {
            _overlayObject.SetActive(false);
        }
    }

    private void DestroyOverlay()
    {
        StopActiveTransition();

        if (_overlayMaterial != null)
        {
            Destroy(_overlayMaterial);
            _overlayMaterial = null;
        }

        if (_overlayObject != null)
        {
            Destroy(_overlayObject);
            _overlayObject = null;
        }

        _overlayRenderer = null;
    }

    private void StopActiveTransition()
    {
        if (_activeTransition != null)
        {
            StopCoroutine(_activeTransition);
            _activeTransition = null;
        }
    }

    private void SetMaterialSlot(Material material)
    {
        if (targetRenderer == null) return;
        if (material == null) return;

        Material[] mats =
            targetRenderer.sharedMaterials;

        if (mats == null || materialSlotIndex < 0 ||
            materialSlotIndex >= mats.Length)
        {
            return;
        }

        if (mats[materialSlotIndex] == material) return;

        mats[materialSlotIndex] = material;
        targetRenderer.sharedMaterials = mats;
    }
}
