// Generated by Cursor AI for jjmil on 2026-03-09.

using UnityEngine;

/// <summary>
/// Shared helper methods for working with BoardComponentDefinitions and their prefabs.
/// Mirrors BallDefinitionUtilities for consistency.
/// </summary>
public static class BoardComponentDefinitionUtilities
{
    public static Sprite TryGetPrefabSpriteIcon(GameObject prefab)
    {
        if (prefab == null)
        {
            return null;
        }

        SpriteRenderer spriteRenderer = prefab.GetComponentInChildren<SpriteRenderer>(includeInactive: true);
        if (spriteRenderer != null)
        {
            return spriteRenderer.sprite;
        }

        return null;
    }

    public static BoardComponentDefinition TryGetDefinitionFromPrefab(GameObject prefab)
    {
        if (prefab == null)
        {
            return null;
        }

        BoardComponentDefinitionLink link =
            prefab.GetComponentInChildren<BoardComponentDefinitionLink>(includeInactive: true);
        if (link != null && link.Definition != null)
        {
            return link.Definition;
        }

        return null;
    }
}
