// Generated by Cursor AI for jjmil on 2026-03-09.

using UnityEngine;

/// <summary>
/// Attach this to a board component prefab so the prefab can be mapped back to its BoardComponentDefinition.
/// Mirrors BallDefinitionLink for consistency.
/// </summary>
public sealed class BoardComponentDefinitionLink : MonoBehaviour
{
    [SerializeField] private BoardComponentDefinition definition;

    public BoardComponentDefinition Definition => definition;

    public bool TryGetDefinition(out BoardComponentDefinition outDefinition)
    {
        outDefinition = definition;
        return outDefinition != null;
    }
}
