// Generated by Cursor AI for jjmil on 2026-03-09.

/// <summary>
/// Shared type categories for board components (bumpers, targets, etc.).
/// </summary>
public enum BoardComponentType
{
    Bumper,
    Target,
    DropTarget,
    Spinner,
    Portal,
    Rollover,
    Launcher,
    Flipper,
    Other
}
