// Generated by Cursor AI for jjmil on 2026-03-09.
// Updated by Antigravity (claude-4.6-opus) on 2026-04-06:
// added ElementType field.

using UnityEngine;

/// <summary>
/// Central source of truth for a board component's metadata (bumpers, targets, etc.).
/// Mirrors the BallDefinition pattern for consistency.
/// </summary>
[CreateAssetMenu(menuName = "Pinball/Board Component Definition", fileName = "BoardComponentDefinition_")]
public sealed class BoardComponentDefinition : ScriptableObject
{
    [Header("Identity")]
    [Tooltip("Stable unique id for this component (used for references and future persistence).")]
    [SerializeField] private string id = "";

    [Header("Presentation")]
    [SerializeField] private string displayName = "Component";
    [TextArea]
    [SerializeField] private string description = "";
    [SerializeField] private BoardComponentType componentType = BoardComponentType.Bumper;
    [SerializeField] private BallRarity rarity = BallRarity.Common;
    [SerializeField] private ElementType elementType = ElementType.None;
    [SerializeField] private Sprite icon;

    [Header("Gameplay")]
    [Tooltip("Prefab that will be spawned/placed for this component.")]
    [SerializeField] private GameObject prefab;
    [Tooltip("Amount of coins this component upgrade will cost")]
    [Min(0)]
    [SerializeField] private int price = 10;

    /// <summary>
    /// Stable id used for progression unlocks; falls back to the asset name, the
    /// same way <see cref="PlayerShipDefinition.Id"/> does.
    ///
    /// The fallback is load-bearing, not cosmetic. Every unlock check —
    /// <see cref="ProgressionService.IsComponentUnlocked"/>,
    /// <see cref="ProgressionConfig.IsStarterComponent"/> — early-returns false on
    /// an empty id, so a newly authored definition with this field left blank is
    /// silently dropped from every shop and draw pool no matter which starter list
    /// or ship / mission allow-list it was added to.
    /// </summary>
    public string Id => string.IsNullOrEmpty(id) ? name : id;

    public string DisplayName => LocalizedContent.Get("component", name, "name", displayName);
    public string Description => LocalizedContent.Get("component", name, "desc", description);
    public BoardComponentType ComponentType => componentType;
    public BallRarity Rarity => rarity;
    public ElementType ElementType => elementType;
    public Sprite Icon => icon;
    public GameObject Prefab => prefab;
    public float Price => price;

    public static BoardComponentDefinition CreateRuntime(
        string runtimeId,
        string runtimeDisplayName,
        string runtimeDescription,
        BoardComponentType runtimeType,
        BallRarity runtimeRarity,
        ElementType runtimeElementType,
        Sprite runtimeIcon,
        GameObject runtimePrefab,
        int runtimePrice)
    {
        var def =
            CreateInstance<BoardComponentDefinition>();
        def.id = runtimeId ?? "";
        def.displayName =
            string.IsNullOrWhiteSpace(runtimeDisplayName)
                ? "Component"
                : runtimeDisplayName;
        def.description = runtimeDescription ?? "";
        def.componentType = runtimeType;
        def.rarity = runtimeRarity;
        def.elementType = runtimeElementType;
        def.icon = runtimeIcon;
        def.prefab = runtimePrefab;
        def.price = runtimePrice;
        return def;
    }

    public bool IsValid()
    {
        return prefab != null;
    }

    public string GetSafeDisplayName()
    {
        var localized = DisplayName;
        return string.IsNullOrWhiteSpace(localized) ? "Component" : localized;
    }

    private void OnValidate()
    {
        if (string.IsNullOrWhiteSpace(displayName))
        {
            displayName = "Component";
        }

        price = price;
    }
}
