// Generated by Cursor AI for jjmil on 2026-03-09.

using UnityEngine;

/// <summary>
/// Central source of truth for a board component's metadata (bumpers, targets, etc.).
/// Mirrors the BallDefinition pattern for consistency.
/// </summary>
[CreateAssetMenu(menuName = "Pinball/Board Component Definition", fileName = "BoardComponentDefinition_")]
public sealed class BoardComponentDefinition : ScriptableObject
{
    [Header("Identity")]
    [Tooltip("Stable unique id for this component (used for references and future persistence).")]
    [SerializeField] private string id = "";

    [Header("Presentation")]
    [SerializeField] private string displayName = "Component";
    [TextArea]
    [SerializeField] private string description = "";
    [SerializeField] private BoardComponentType componentType = BoardComponentType.Bumper;
    [SerializeField] private Sprite icon;

    [Header("Gameplay")]
    [Tooltip("Prefab that will be spawned/placed for this component.")]
    [SerializeField] private GameObject prefab;
    [Tooltip("Default base score amount (points) for this component type.")]
    [Min(0)]
    [SerializeField] private float baseScore = 5f;

    public string Id => id;
    public string DisplayName => displayName;
    public string Description => description;
    public BoardComponentType ComponentType => componentType;
    public Sprite Icon => icon;
    public GameObject Prefab => prefab;
    public float BaseScore => baseScore;

    public static BoardComponentDefinition CreateRuntime(
        string runtimeId,
        string runtimeDisplayName,
        string runtimeDescription,
        BoardComponentType runtimeType,
        Sprite runtimeIcon,
        GameObject runtimePrefab,
        float runtimeBaseScore)
    {
        var def = CreateInstance<BoardComponentDefinition>();
        def.id = runtimeId ?? "";
        def.displayName = string.IsNullOrWhiteSpace(runtimeDisplayName) ? "Component" : runtimeDisplayName;
        def.description = runtimeDescription ?? "";
        def.componentType = runtimeType;
        def.icon = runtimeIcon;
        def.prefab = runtimePrefab;
        def.baseScore = Mathf.Max(0f, runtimeBaseScore);
        return def;
    }

    public bool IsValid()
    {
        return prefab != null;
    }

    public string GetSafeDisplayName()
    {
        return string.IsNullOrWhiteSpace(displayName) ? "Component" : displayName;
    }

    private void OnValidate()
    {
        if (string.IsNullOrWhiteSpace(displayName))
        {
            displayName = "Component";
        }

        baseScore = Mathf.Max(0f, baseScore);
    }
}
