// Generated by Claude Code (claude-opus-4-8) for jjmil on 2026-07-29.

using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Per-type, non-sound metadata for board components, kept in one editable asset so
/// adding a new <see cref="BoardComponentType"/> is a declare-once change instead of
/// editing the scattered switch / if-else sites that each fail silently when a type
/// is missing (no particles, invisible to status effects, unplaceable). Loaded once
/// from Resources, mirroring <see cref="RunItemCatalog"/> and
/// <see cref="StatusBadgeLibrary"/>.
///
/// Hit sounds deliberately live on the AudioManager GameObject (assignable in its
/// inspector), not here — see AudioManager's componentHitSounds list.
///
/// Every static accessor falls back to the historical hardcoded behaviour when the
/// asset is missing or a type hasn't been added to it yet, so an absent or
/// incomplete catalog can never silently flip an existing component's behaviour.
/// </summary>
[CreateAssetMenu(menuName = "Pinball/Component Type Catalog", fileName = "ComponentTypeCatalog")]
public sealed class ComponentTypeCatalog : ScriptableObject
{
    private const string resourcePath = "ComponentTypeCatalog";

    [Serializable]
    public struct Descriptor
    {
        public BoardComponentType type;
        [Tooltip("Player-facing name for this type.")]
        public string displayName;
        [Tooltip("Ball spark particles burst when the ball strikes this type.")]
        public bool emitsBallParticles;
        [Tooltip("Status effects (Fire, Charge, Detonate) may act on this type.")]
        public bool statusTargetable;
        [Tooltip("Can be bought/placed in the shop " +
            "(a matching definition asset must also exist).")]
        public bool shopPlaceable;
    }

    [SerializeField] private List<Descriptor> descriptors = new List<Descriptor>();

    private static ComponentTypeCatalog _instance;
    private static bool _loadAttempted;
    private Dictionary<BoardComponentType, Descriptor> _lookup;

    public static ComponentTypeCatalog Instance
    {
        get
        {
            if (_instance == null && !_loadAttempted)
            {
                _loadAttempted = true;
                _instance = Resources.Load<ComponentTypeCatalog>(resourcePath);
            }

            return _instance;
        }
    }

    private Dictionary<BoardComponentType, Descriptor> Lookup
    {
        get
        {
            if (_lookup == null)
            {
                _lookup = new Dictionary<BoardComponentType, Descriptor>();
                if (descriptors != null)
                {
                    foreach (Descriptor d in descriptors)
                    {
                        _lookup[d.type] = d;
                    }
                }
            }

            return _lookup;
        }
    }

    public bool TryGet(BoardComponentType type, out Descriptor descriptor)
    {
        return Lookup.TryGetValue(type, out descriptor);
    }

    // ── Static convenience accessors ──────────────────────────

    public static bool EmitsBallParticles(BoardComponentType type)
    {
        if (Instance != null && Instance.TryGet(type, out Descriptor d))
        {
            return d.emitsBallParticles;
        }

        return DefaultEmitsBallParticles(type);
    }

    public static bool StatusTargetable(BoardComponentType type)
    {
        if (Instance != null && Instance.TryGet(type, out Descriptor d))
        {
            return d.statusTargetable;
        }

        return DefaultStatusTargetable(type);
    }

    public static bool ShopPlaceable(BoardComponentType type)
    {
        if (Instance != null && Instance.TryGet(type, out Descriptor d))
        {
            return d.shopPlaceable;
        }

        return DefaultShopPlaceable(type);
    }

    /// <summary>
    /// Player-facing name for a type, from the catalog when present, else the enum
    /// name. Used where an instance's type must be named directly rather than
    /// through its definition (e.g. an instance re-typed away from its prefab).
    /// </summary>
    public static string DisplayName(BoardComponentType type)
    {
        if (Instance != null && Instance.TryGet(type, out Descriptor d)
            && !string.IsNullOrWhiteSpace(d.displayName))
        {
            return d.displayName;
        }

        return type.ToString();
    }

    // ── Historical defaults (safety net when the asset is absent) ──

    private static bool DefaultEmitsBallParticles(BoardComponentType type)
    {
        switch (type)
        {
            case BoardComponentType.Flipper:
            case BoardComponentType.Spinner:
            case BoardComponentType.Rollover:
            case BoardComponentType.Launcher:
            case BoardComponentType.Portal:
                return false;
            default:
                return true;
        }
    }

    private static bool DefaultStatusTargetable(BoardComponentType type)
    {
        return type != BoardComponentType.Flipper
            && type != BoardComponentType.Portal;
    }

    private static bool DefaultShopPlaceable(BoardComponentType type)
    {
        switch (type)
        {
            case BoardComponentType.Bumper:
            case BoardComponentType.Target:
            case BoardComponentType.Sling:
            case BoardComponentType.Rollover:
            case BoardComponentType.Flipper:
                return true;
            default:
                return false;
        }
    }
}
