// Generated by Cursor AI assistant, 2025-03-15.
// Updated with Cursor (Composer) by assistant, for jjmil, on 2026-04-01 (BoardLight; all-down color only).
using UnityEngine;

/// <summary>
/// Connects a <see cref="DropTarget"/> to a <see cref="BoardLight"/>. Off/on colors come from
/// <see cref="BoardLight"/> in the Inspector; this component only supplies the lit color when all
/// three targets are down (Carolina blue by default).
/// </summary>
[DefaultExecutionOrder(50)]
public class DropTargetLightBulb : MonoBehaviour
{
    [Header("References")]
    [SerializeField] private DropTarget dropTarget;

    [Tooltip("Board light for bulb mesh + optional point light. Defaults to GetComponent.")]
    [SerializeField] private BoardLight boardLight;

    [Header("All targets down")]
    [Tooltip("Lit color when all 3 drop targets are down. Normal lit/unlit uses BoardLight.")]
    [SerializeField] private Color allTargetsDownLitColor = new Color(0.337f, 0.627f, 0.827f, 1f);

    [Tooltip("Assign the DropTargetsScoringMode on the board.")]
    [SerializeField] private DropTargetsScoringMode scoringMode;


    private void Awake()
    {
        if (boardLight == null)
        {
            boardLight = GetComponent<BoardLight>();
        }

        if (dropTarget == null)
        {
            dropTarget = GetComponentInParent<DropTarget>();
        }
    }

    private void OnEnable()
    {
        if (dropTarget != null)
        {
            dropTarget.OnFullyDown += HandleTargetStateChanged;
            dropTarget.OnReturnedUp += HandleTargetStateChanged;
        }

        if (scoringMode != null)
        {
            scoringMode.OnAllTargetsDown += HandleAllDownStateChanged;
            scoringMode.OnAnyTargetReturned += HandleAllDownStateChanged;
        }

        RefreshLightState();
    }

    private void Start()
    {
        RefreshLightState();
    }

    private void OnDisable()
    {
        if (dropTarget != null)
        {
            dropTarget.OnFullyDown -= HandleTargetStateChanged;
            dropTarget.OnReturnedUp -= HandleTargetStateChanged;
        }

        if (scoringMode != null)
        {
            scoringMode.OnAllTargetsDown -= HandleAllDownStateChanged;
            scoringMode.OnAnyTargetReturned -= HandleAllDownStateChanged;
        }
    }

    private void HandleTargetStateChanged()
    {
        RefreshLightState();
    }

    private void HandleAllDownStateChanged()
    {
        RefreshLightState();
    }

    private void RefreshLightState()
    {
        if (boardLight == null)
        {
            return;
        }

        if (dropTarget == null || !dropTarget.IsDown)
        {
            boardLight.ClearLitAppearanceOverride();
            boardLight.SetLit(false);
            return;
        }

        boardLight.SetLit(true);
        bool allDown = scoringMode != null && scoringMode.AllTargetsDownNow;
        if (allDown)
        {
            boardLight.SetLitAppearanceOverride(allTargetsDownLitColor);
        }
        else
        {
            boardLight.ClearLitAppearanceOverride();
        }
    }
}
