// Generated by Cursor AI assistant, 2025-03-15.
// Updated with Cursor (Composer) by assistant, for jjmil, on 2026-04-01 (BoardLight; all-down color only).
// Updated with Antigravity by jjmil on 2026-04-09 (blue only on Power Surge, not all-down).
using UnityEngine;
using UnityEngine.Serialization;

/// <summary>
/// Connects a <see cref="Dropper"/> to a <see cref="BoardLight"/>.
/// Off/on colors come from <see cref="BoardLight"/> in the Inspector;
/// this component supplies the Power Surge lit color (Carolina blue by
/// default) only when Power Surge is active (ball entered the portal),
/// not merely when all three targets are down.
/// </summary>
[DefaultExecutionOrder(50)]
public class DropTargetLightBulb : MonoBehaviour
{
    [Header("References")]
    [SerializeField] private Dropper dropTarget;
    [FormerlySerializedAs("frenzyManager")]
    [SerializeField] private PowerSurgeManager powerSurgeManager;

    [Tooltip("Board light for bulb mesh + optional point light. Defaults to GetComponent.")]
    [SerializeField] private BoardLight boardLight;

    [Header("Power Surge")]
    [Tooltip("Lit color when Power Surge is active (portal entered). Normal lit/unlit uses BoardLight.")]
    [FormerlySerializedAs("frenzyLitColor")]
    [SerializeField] private Color powerSurgeLitColor = new Color(0.337f, 0.627f, 0.827f, 1f);


    private void Awake()
    {
        if (powerSurgeManager == null)
        {
            powerSurgeManager = ServiceLocator.Get<PowerSurgeManager>();
        }

        if (boardLight == null)
        {
            boardLight = GetComponent<BoardLight>();
        }

        if (dropTarget == null)
        {
            dropTarget = GetComponentInParent<Dropper>();
        }
    }

    private void OnEnable()
    {
        if (dropTarget != null)
        {
            dropTarget.OnFullyDown += HandleTargetStateChanged;
            dropTarget.OnReturnedUp += HandleTargetStateChanged;
        }

        powerSurgeManager.OnPowerSurgeActivated += HandlePowerSurgeStateChanged;
        powerSurgeManager.OnPowerSurgeDeactivated += HandlePowerSurgeStateChanged;

        RefreshLightState();
    }

    private void Start()
    {
        RefreshLightState();
    }

    private void OnDisable()
    {
        if (dropTarget != null)
        {
            dropTarget.OnFullyDown -= HandleTargetStateChanged;
            dropTarget.OnReturnedUp -= HandleTargetStateChanged;
        }

        powerSurgeManager.OnPowerSurgeActivated -= HandlePowerSurgeStateChanged;
        powerSurgeManager.OnPowerSurgeDeactivated -= HandlePowerSurgeStateChanged;
    }

    private void HandleTargetStateChanged()
    {
        RefreshLightState();
    }

    private void HandlePowerSurgeStateChanged()
    {
        RefreshLightState();
    }

    private void RefreshLightState()
    {
        if (boardLight == null)
        {
            return;
        }

        if (dropTarget == null || !dropTarget.IsDown)
        {
            boardLight.ClearLitAppearanceOverride();
            boardLight.SetLit(false);
        } else
        {
            boardLight.ClearLitAppearanceOverride();
            boardLight.SetLit(true);
        }

        bool powerSurgeOn = powerSurgeManager.isPowerSurgeActive;

        if (powerSurgeOn)
        {
            boardLight.SetLitAppearanceOverride(powerSurgeLitColor);
        }
        else
        {
            boardLight.ClearLitAppearanceOverride();
        }
    }
}
