// Generated by Cursor AI assistant, 2025-03-15.
// Updated with Cursor (Composer) by assistant, for jjmil, on 2026-04-01 (optional BoardLight refresh).
using System;
using System.Collections;
using TMPro;
using UnityEngine;
using UnityEngine.SceneManagement;

/// <summary>
/// Scoring mode tied to 3 drop targets. When all 3 are down, awards a bonus,
/// increases all scoring by 50%, and bulbs turn Carolina blue via <see cref="DropTargetLightBulb"/> /
/// <see cref="BoardLight"/>. Assign <see cref="dropTargetBulbLights"/> to those <see cref="BoardLight"/>
/// components so this mode can re-apply visuals after all-down transitions.
/// </summary>
public class DropTargetsScoringMode : MonoBehaviour
{
    private const string GameplayCoreSceneName = "GameplayCore";
    /// <summary>Fired when all 3 drop targets become down. Lights use this to turn Carolina blue.</summary>
    public event Action OnAllTargetsDown;

    /// <summary>Fired when any target returns up (no longer all down).</summary>
    public event Action OnAnyTargetReturned;
    [Header("Drop Targets")]
    [SerializeField] private DropTarget[] dropTargets = new DropTarget[3];

    [Header("Board lights")]
    [Tooltip("The three drop-target bulb BoardLights (same targets as dropTargets). Refreshes visuals " +
             "when all-down state changes.")]
    [SerializeField] private BoardLight[] dropTargetBulbLights = new BoardLight[3];

    [Header("Bonus (when all down)")]
    [Tooltip("Points awarded when all 3 drop targets are down. 0 = no bonus.")]
    [SerializeField] private float allDownBonusPoints = 500f;
    [Tooltip("Score multiplier when all 3 are down (1.5 = +50%).")]
    [SerializeField] private float allDownScoreMultiplier = 1.5f;
    [Tooltip("Transform used for floating text spawn position (e.g. center of targets).")]
    [SerializeField] private Transform bonusSpawnPosition;
    [Tooltip("Canvas offset for bonus popups (0, -100) = 100 pixels down.")]
    [SerializeField] private Vector2 popupOffset = new Vector2(0f, -100f);

    [Header("References")]
    [SerializeField] private ScoreManager scoreManager;
    [SerializeField] private FloatingTextSpawner floatingTextSpawner;
    [Tooltip("Font for the +50% score popup. If null, uses spawner's points font (Jersey 10).")]
    [SerializeField] private TMP_FontAsset popupFontAsset;

    private bool _allDownBonusAwardedThisCycle;
    private bool _wasAllDown;
    private Coroutine _deferredCheckRoutine;

    private void Awake()
    {
        EnsureRefs();
    }

    private void OnEnable()
    {
        if (dropTargets == null) return;

        foreach (DropTarget dt in dropTargets)
        {
            if (dt != null)
            {
                dt.OnFullyDown += OnTargetFullyDown;
                dt.OnReturnedUp += OnTargetReturnedUp;
            }
        }

        _allDownBonusAwardedThisCycle = false;

        RefreshDropTargetBulbVisuals();
    }

    private void OnDisable()
    {
        if (_deferredCheckRoutine != null)
        {
            StopCoroutine(_deferredCheckRoutine);
            _deferredCheckRoutine = null;
        }

        if (dropTargets != null)
        {
            foreach (DropTarget dt in dropTargets)
            {
                if (dt != null)
                {
                    dt.OnFullyDown -= OnTargetFullyDown;
                    dt.OnReturnedUp -= OnTargetReturnedUp;
                }
            }
        }

        if (_wasAllDown && scoreManager != null)
        {
            scoreManager.SetExternalScoreAwardMultiplier(1f);
        }
    }

    private void OnTargetFullyDown()
    {
        if (_deferredCheckRoutine != null)
        {
            StopCoroutine(_deferredCheckRoutine);
        }

        _deferredCheckRoutine = StartCoroutine(DeferredCheckAllDown());
    }

    private void OnTargetReturnedUp()
    {
        if (_deferredCheckRoutine != null)
        {
            StopCoroutine(_deferredCheckRoutine);
            _deferredCheckRoutine = null;
        }

        if (_wasAllDown)
        {
            _wasAllDown = false;
            ApplyAllDownState(false);
            OnAnyTargetReturned?.Invoke();
        }

        _allDownBonusAwardedThisCycle = false;
    }

    private IEnumerator DeferredCheckAllDown()
    {
        yield return null;

        _deferredCheckRoutine = null;

        bool allDown = AllTargetsDown();

        if (allDown)
        {
            if (!_wasAllDown)
            {
                _wasAllDown = true;
                ApplyAllDownState(true);
                OnAllTargetsDown?.Invoke();
            }

            if (!_allDownBonusAwardedThisCycle)
            {
                AwardAllDownBonus();
            }
        }
        else
        {
            if (_wasAllDown)
            {
                _wasAllDown = false;
                ApplyAllDownState(false);
                OnAnyTargetReturned?.Invoke();
            }

            _allDownBonusAwardedThisCycle = false;
        }

        RefreshDropTargetBulbVisuals();
    }

    private void RefreshDropTargetBulbVisuals()
    {
        if (dropTargetBulbLights == null)
        {
            return;
        }

        for (int i = 0; i < dropTargetBulbLights.Length; i++)
        {
            if (dropTargetBulbLights[i] != null)
            {
                dropTargetBulbLights[i].ReapplyVisuals();
            }
        }
    }

    private void ApplyAllDownState(bool active)
    {
        EnsureRefs();
        if (scoreManager != null)
        {
            scoreManager.SetExternalScoreAwardMultiplier(active ? allDownScoreMultiplier : 1f);
        }
    }

    private bool AllTargetsDown()
    {
        if (dropTargets == null || dropTargets.Length == 0) return false;

        foreach (DropTarget dt in dropTargets)
        {
            if (dt == null || !dt.IsDown) return false;
        }

        return true;
    }

    /// <summary>True when all 3 drop targets are down.</summary>
    public bool AllTargetsDownNow => AllTargetsDown();

    private void AwardAllDownBonus()
    {
        if (allDownBonusPoints <= 0f) return;

        EnsureRefs();
        if (scoreManager == null) return;

        Transform pos = bonusSpawnPosition != null ? bonusSpawnPosition : transform;
        scoreManager.AddScore(allDownBonusPoints, TypeOfScore.points, pos, popupOffset);
        _allDownBonusAwardedThisCycle = true;

        if (floatingTextSpawner != null)
        {
            floatingTextSpawner.SpawnText(pos.position, "+50% score!", popupFontAsset, 0.9f, popupOffset);
        }
    }

    private void EnsureRefs()
    {
        if (scoreManager != null && floatingTextSpawner != null) return;

        if (scoreManager == null)
        {
            scoreManager = FindScoreManagerInGameplayCore();
        }

        if (floatingTextSpawner == null)
        {
            floatingTextSpawner = ServiceLocator.Get<FloatingTextSpawner>();
        }
    }

    private static ScoreManager FindScoreManagerInGameplayCore()
    {
        ScoreManager[] all = FindObjectsByType<ScoreManager>(FindObjectsSortMode.None);
        for (int i = 0; i < all.Length; i++)
        {
            ScoreManager sm = all[i];
            if (sm == null) continue;
            if (!sm.gameObject.scene.IsValid()) continue;
            if (!string.Equals(sm.gameObject.scene.name, GameplayCoreSceneName, StringComparison.OrdinalIgnoreCase))
                continue;

            return sm;
        }

        Scene scene = SceneManager.GetSceneByName(GameplayCoreSceneName);
        if (scene.IsValid() && scene.isLoaded)
        {
            var roots = scene.GetRootGameObjects();
            for (int i = 0; i < roots.Length; i++)
            {
                var sm = roots[i].GetComponentInChildren<ScoreManager>(includeInactive: true);
                if (sm != null) return sm;
            }
        }

        return ServiceLocator.Get<ScoreManager>();
    }
}
