// Generated by Cursor AI assistant, 2025-03-15.
using UnityEngine;

/// <summary>
/// Connects a drop target to a light bulb (Renderer). When the drop target is down,
/// the light turns on by changing the material's base color. When up, the light turns off.
/// Assign the drop target and the renderer (or a child with a Renderer) in the Inspector.
/// </summary>
public class DropTargetLightBulb : MonoBehaviour
{
    private static readonly int BaseColorId = Shader.PropertyToID("_BaseColor");
    private static readonly int ColorId = Shader.PropertyToID("_Color");

    [Header("References")]
    [SerializeField] private DropTarget dropTarget;
    [Tooltip("Renderer whose material base color will be changed. If null, uses GetComponent on this GameObject.")]
    [SerializeField] private Renderer lightRenderer;

    [Header("Colors")]
    [Tooltip("Color when the drop target is down (light on).")]
    [SerializeField] private Color colorOn = new Color(1f, 0.9f, 0.4f, 1f);
    [Tooltip("Color when all 3 drop targets are down (Carolina blue).")]
    [SerializeField] private Color colorAllDown = new Color(0.337f, 0.627f, 0.827f, 1f);
    [Tooltip("Color when the drop target is up (light off).")]
    [SerializeField] private Color colorOff = new Color(0.15f, 0.15f, 0.15f, 1f);

    [Header("All-Down Mode (optional)")]
    [Tooltip("When set, uses colorAllDown when all 3 targets are down. Assign the DropTargetsScoringMode.")]
    [SerializeField] private DropTargetsScoringMode scoringMode;

    private MaterialPropertyBlock _mpb;
    private Material _materialInstance;

    private void Awake()
    {
        if (lightRenderer == null)
        {
            lightRenderer = GetComponent<Renderer>();
        }

        if (dropTarget == null)
        {
            dropTarget = GetComponentInParent<DropTarget>();
        }

        _mpb = new MaterialPropertyBlock();
    }

    private void OnEnable()
    {
        if (dropTarget != null)
        {
            dropTarget.OnFullyDown += HandleTargetStateChanged;
            dropTarget.OnReturnedUp += HandleTargetStateChanged;
        }

        if (scoringMode != null)
        {
            scoringMode.OnAllTargetsDown += HandleAllDownStateChanged;
            scoringMode.OnAnyTargetReturned += HandleAllDownStateChanged;
        }

        RefreshLightState();
    }

    private void OnDisable()
    {
        if (dropTarget != null)
        {
            dropTarget.OnFullyDown -= HandleTargetStateChanged;
            dropTarget.OnReturnedUp -= HandleTargetStateChanged;
        }

        if (scoringMode != null)
        {
            scoringMode.OnAllTargetsDown -= HandleAllDownStateChanged;
            scoringMode.OnAnyTargetReturned -= HandleAllDownStateChanged;
        }
    }

    private void HandleTargetStateChanged()
    {
        RefreshLightState();
    }

    private void HandleAllDownStateChanged()
    {
        RefreshLightState();
    }

    private void RefreshLightState()
    {
        if (dropTarget != null)
        {
            SetLightOn(dropTarget.IsDown);
        }
    }

    private void SetLightOn(bool on)
    {
        if (lightRenderer == null) return;

        bool useAllDownColor = on && scoringMode != null && scoringMode.AllTargetsDownNow;
        Color c = on ? (useAllDownColor ? colorAllDown : colorOn) : colorOff;

        lightRenderer.GetPropertyBlock(_mpb);
        if (lightRenderer.sharedMaterial.HasProperty(BaseColorId))
        {
            _mpb.SetColor(BaseColorId, c);
        }
        else if (lightRenderer.sharedMaterial.HasProperty(ColorId))
        {
            _mpb.SetColor(ColorId, c);
        }
        else
        {
            if (_materialInstance == null)
            {
                _materialInstance = lightRenderer.material;
            }

            if (_materialInstance.HasProperty(BaseColorId))
            {
                _materialInstance.SetColor(BaseColorId, c);
            }
            else if (_materialInstance.HasProperty(ColorId))
            {
                _materialInstance.SetColor(ColorId, c);
            }

            return;
        }

        lightRenderer.SetPropertyBlock(_mpb);
    }
}
