// Generated by Cursor (jjmil) on 2026-03-12.
using UnityEngine;

/// <summary>
/// Implement this interface to be notified when a ball is teleported through a portal.
/// Called after the ball has been moved to the portal exit (play field).
/// </summary>
public interface IPortalTeleportListener
{
    void OnTeleportedThroughPortal();
}
