// Generated by GPT-5.2 (Cursor), JJ Mil, 2026-02-15
using System.Collections;
using UnityEngine;

public class ParentToCamera : MonoBehaviour
{
    [SerializeField] private Transform cameraTransform;
    [SerializeField] private bool worldPositionStays = true;
    [SerializeField] private bool snapToCameraLocalTransform;
    [SerializeField] private float retrySeconds = 0.1f;

    private Coroutine parentRoutine;

    private void OnEnable()
    {
        if (parentRoutine != null)
        {
            StopCoroutine(parentRoutine);
        }

        parentRoutine = StartCoroutine(ParentWhenCameraAvailable());
    }

    private void OnDisable()
    {
        if (parentRoutine != null)
        {
            StopCoroutine(parentRoutine);
            parentRoutine = null;
        }
    }

    private IEnumerator ParentWhenCameraAvailable()
    {
        while (cameraTransform == null)
        {
            cameraTransform = TryResolveCameraTransform();

            if (cameraTransform == null)
            {
                yield return new WaitForSeconds(retrySeconds);
            }
        }

        if (transform.parent == cameraTransform)
        {
            yield break;
        }

        transform.SetParent(cameraTransform, worldPositionStays);

        if (snapToCameraLocalTransform)
        {
            transform.localPosition = Vector3.zero;
            transform.localRotation = Quaternion.identity;
            transform.localScale = Vector3.one;
        }
    }

    private Transform TryResolveCameraTransform()
    {
        Camera mainCamera = Camera.main;

        if (mainCamera != null)
        {
            return mainCamera.transform;
        }

#if UNITY_2022_2_OR_NEWER
        Camera anyCamera = FindFirstObjectByType<Camera>();
#else
        Camera anyCamera = FindObjectOfType<Camera>();
#endif

        return anyCamera != null ? anyCamera.transform : null;
    }
}
