// Generated by Claude Code (Opus 4.7) for jjmil on 2026-05-13.

using System;
using Unity.Services.Analytics;
using Unity.Services.Core;
using UnityEngine;

/// <summary>
/// Thin wrapper around <see cref="AnalyticsService"/> for shop-item telemetry.
/// Fire-and-forget initialization runs once before the first scene loads.
/// All public log methods are no-ops until the service is ready and never
/// throw into gameplay code.
///
/// Mystery balls: "shown" is logged with the mystery placeholder id (what the
/// player actually sees on the shelf); "purchased" is logged with the resolved
/// concrete ball id (what the player actually got).
///
/// Dashboard side — these custom events must be defined in the Unity Cloud
/// Dashboard before any data flows:
///   shopItemShown      params: itemId(string), itemName(string),
///                              itemType(string), price(int)
///   shopItemPurchased  params: itemId(string), itemName(string),
///                              itemType(string), price(int)
/// Per-item counters come from grouping by itemId in the dashboard query.
/// </summary>
public static class PinballAnalytics
{
    private const string shopItemShownEvent = "shopItemShown";
    private const string shopItemPurchasedEvent = "shopItemPurchased";

    private static bool _ready;

    [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]
    private static async void Initialize()
    {
        try
        {
            if (UnityServices.State != ServicesInitializationState.Initialized)
            {
                await UnityServices.InitializeAsync();
            }

            AnalyticsService.Instance.StartDataCollection();
            _ready = true;
        }
        catch (Exception e)
        {
            Debug.LogWarning($"[PinballAnalytics] init failed: {e.Message}");
        }
    }

    public static void LogShopItemShown(ShopOffer offer)
    {
        if (offer == null || !offer.IsValid) return;

        LogShopItem(
            shopItemShownEvent,
            GetOfferId(offer),
            offer.DisplayName,
            GetOfferType(offer),
            offer.Price);
    }

    public static void LogShopItemPurchased(ShopOffer offer)
    {
        if (offer == null || !offer.IsValid) return;

        LogShopItem(
            shopItemPurchasedEvent,
            GetOfferId(offer),
            offer.DisplayName,
            GetOfferType(offer),
            offer.Price);
    }

    /// <summary>
    /// Overload for ball purchases where a mystery offer was resolved to a
    /// concrete ball -- pass the resolved <paramref name="resolvedBall"/> so
    /// the purchased event references the ball the player actually got.
    /// </summary>
    public static void LogShopItemPurchased(ShopOffer offer, BallDefinition resolvedBall, int pricePaid)
    {
        if (offer == null) return;

        string id = resolvedBall != null && !string.IsNullOrEmpty(resolvedBall.Id)
            ? resolvedBall.Id
            : GetOfferId(offer);

        string name = resolvedBall != null
            ? resolvedBall.GetSafeDisplayName()
            : offer.DisplayName;

        LogShopItem(
            shopItemPurchasedEvent,
            id,
            name,
            "Ball",
            pricePaid);
    }

    private static void LogShopItem(string eventName, string itemId, string itemName, string itemType, int price)
    {
        if (!_ready) return;

        try
        {
            CustomEvent evt = new CustomEvent(eventName)
            {
                { "itemId", itemId ?? string.Empty },
                { "itemName", itemName ?? string.Empty },
                { "itemType", itemType ?? string.Empty },
                { "price", price }
            };

            AnalyticsService.Instance.RecordEvent(evt);
        }
        catch (Exception e)
        {
            Debug.LogWarning($"[PinballAnalytics] {eventName} failed: {e.Message}");
        }
    }

    private static string GetOfferId(ShopOffer offer)
    {
        if (offer.Type == ShopOffer.OfferType.Ball)
        {
            return offer.BallDef != null ? offer.BallDef.Id : string.Empty;
        }

        return offer.ComponentDef != null ? offer.ComponentDef.Id : string.Empty;
    }

    private static string GetOfferType(ShopOffer offer)
    {
        return offer.Type == ShopOffer.OfferType.Ball ? "Ball" : "BoardComponent";
    }
}
