// Generated by Claude Code (claude-opus-4-8) for jjmil on 2026-07-29.

using UnityEngine;

/// <summary>
/// Shared Charge VFX for statuses attached at runtime (a ball's <see cref="ChargeStatus"/>
/// can never have prefab fields wired in the inspector). Loaded once from Resources,
/// mirroring <see cref="FireVfxLibrary"/>. Holds the placeholder chain-lightning line
/// drawn between components on a discharge.
/// </summary>
[CreateAssetMenu(menuName = "Pinball/Charge VFX Library", fileName = "ChargeVfxLibrary")]
public sealed class ChargeVfxLibrary : ScriptableObject
{
    private const string resourcePath = "ChargeVfxLibrary";

    private static ChargeVfxLibrary _instance;
    private static bool _loadAttempted;

    [Header("Chain Lightning")]
    [Tooltip("Placeholder line prefab (carries a LightningBolt component) drawn from "
        + "the struck point to each component the discharge activates. Swap for real "
        + "tech-art VFX later.")]
    [SerializeField] private GameObject chainLightningPrefab;

    public static ChargeVfxLibrary Instance
    {
        get
        {
            if (_instance == null && !_loadAttempted)
            {
                _loadAttempted = true;
                _instance = Resources.Load<ChargeVfxLibrary>(resourcePath);
            }

            return _instance;
        }
    }

    /// <summary>
    /// Spawns a procedural bolt spanning <paramref name="from"/> to <paramref name="to"/>.
    /// The bolt pins itself to both points and self-destructs. Returns the instance, or
    /// null if no prefab is set.
    /// </summary>
    public GameObject SpawnChainLightning(Vector3 from, Vector3 to)
    {
        if (chainLightningPrefab == null)
        {
            return null;
        }

        GameObject fx = Instantiate(chainLightningPrefab);

        LightningBolt bolt = fx.GetComponent<LightningBolt>();
        if (bolt != null)
        {
            bolt.Initialize(from, to);
        }
        else
        {
            fx.transform.position = from;
        }

        return fx;
    }
}
