// Generated by Claude Code (claude-opus-5) for jjmil on 2026-07-28.
// Rewrite: single ChargeStatus type; consumers declare their requirement here.

using UnityEngine;

/// <summary>
/// Entry points for granting and moving Charge. Consumers register their
/// requirement through <see cref="GetOrAddConsumerStatus"/> so the threshold lives
/// on the status rather than being duplicated on every consuming component.
/// </summary>
public static class ChargeStatusUtility
{

    /// <summary>
    /// Status for a component that banks Charge toward an ability. The requirement
    /// is what marks it as a consumer, so balls deposit into it instead of proccing.
    /// </summary>
    public static ChargeStatus GetOrAddConsumerStatus(
        BoardComponent component, int chargeRequired)
    {
        if (component == null)
        {
            return null;
        }

        ChargeStatus status = component.GetComponent<ChargeStatus>();
        if (status == null)
        {
            status = component.gameObject.AddComponent<ChargeStatus>();
        }

        status.SetChargeRequired(chargeRequired);
        return status;
    }

    /// <summary>
    /// Status for a consumer that is not a BoardComponent, such as the flipper
    /// upgrade Moore's Launcher.
    /// </summary>
    public static ChargeStatus GetOrAddConsumerStatus(
        GameObject host, int chargeRequired)
    {
        if (host == null)
        {
            return null;
        }

        ChargeStatus status = host.GetComponent<ChargeStatus>();
        if (status == null)
        {
            status = host.AddComponent<ChargeStatus>();
        }

        status.SetChargeRequired(chargeRequired);
        return status;
    }

    public static ChargeStatus GetOrAddBallStatus(Ball ball)
    {
        if (ball == null)
        {
            return null;
        }

        ChargeStatus status = ball.GetComponent<ChargeStatus>();
        if (status == null)
        {
            status = ball.gameObject.AddComponent<ChargeStatus>();
        }

        return status;
    }

    public static void GiveCharge(Ball ball, int amount)
    {
        GetOrAddBallStatus(ball)?.AddCharge(amount);
    }

    /// <summary>
    /// Moves every Charge the carrier holds into the receiver. Returns how much
    /// was moved.
    /// </summary>
    public static int DrainInto(ChargeStatus carrier, ChargeStatus receiver)
    {
        if (carrier == null || receiver == null || !carrier.HasCharge)
        {
            return 0;
        }

        int moved = carrier.TakeAllCharge();
        ChargeDebug.Log($"{carrier.name} deposits {moved} Charge into {receiver.name}");
        receiver.AddCharge(moved);
        return moved;
    }

    /// <summary>
    /// Convenience for consumers that resolve a ball on collision themselves.
    /// </summary>
    public static int DrainBallInto(Ball ball, ChargeStatus receiver)
    {
        ChargeStatus carrier = ball != null ? ball.GetComponent<ChargeStatus>() : null;
        return DrainInto(carrier, receiver);
    }
}
