// Generated by Claude Code (claude-opus-5) for jjmil on 2026-07-28.
// Rewrite: one status for balls and components; decay removed; carriers now proc.

using System;
using UnityEngine;

/// <summary>
/// The Charge status, for balls and board components alike. Charge is a stacking
/// resource, and the amount held is how far its effect reaches.
///
/// A ball carrying N Charge rolls a chance on every collision to activate the N
/// nearest components; the proc does not spend the Charge. Charge is spent by
/// transferring into a component that requires it, which happens on contact — and
/// a hit on such a component is a deposit only, never a proc, so the two uses of
/// Charge never fire at once. Only components that require Charge hold it;
/// everything else is a pass-through.
/// </summary>
public class ChargeStatus : MonoBehaviour, IStatusBadgeSource
{
    private const int chargeBadgeSortOrder = 10;

    [Header("Requirement")]
    [Tooltip("Charge needed before FullyCharged fires. 0 marks a carrier "
        + "(a ball) rather than a consumer.")]
    [SerializeField] private int chargeRequired = 0;

    [Header("Carrier proc")]
    [Tooltip("Chance a carrier activates its nearest components on collision.")]
    [SerializeField, Range(0f, 1f)] private float chanceToActivateNearest = 0.5f;
    [Tooltip("How far a carrier looks when activating its nearest components.")]
    [SerializeField] private float nearestSearchRadius = 10f;

    [Header("Runtime")]
    [SerializeField] private int charge;

    private Ball _ball;

    /// <summary>
    /// Number of active Chain Lightning modules. With none, a discharge chains to a
    /// single nearby component; with one (or more), it chains to as many as the
    /// carrier's stacks, capped at 3.
    /// </summary>
    public static int ChainLightningModules;

    private const int ChainLightningStackCap = 3;

    // How many nearby components a discharge activates: 1 by default, or up to the
    // stack count (capped) once Chain Lightning is owned.
    private int ChainTargetCount => ChainLightningModules > 0
        ? Mathf.Clamp(charge, 1, ChainLightningStackCap)
        : 1;

    public event Action ChargeChanged;
    public event Action FullyCharged;

    public int Charge => charge;
    public bool HasCharge => charge > 0;
    public int ChargeRequired => chargeRequired;
    public bool IsConsumer => chargeRequired > 0;

    protected virtual void Awake()
    {
        _ball = GetComponent<Ball>();

        // Owned here rather than in ChargeStatusUtility so a status placed on a
        // prefab in the inspector gets its readout too, not just ones granted at
        // runtime.
        StatusBadgeDisplay.EnsureOn(gameObject);
    }

    public void SetChargeRequired(int value)
    {
        chargeRequired = Mathf.Max(0, value);
    }

    /// <summary>
    /// A consumer shows its bank against its requirement from the moment it exists,
    /// empty included, so the player can read what a component wants before ever
    /// feeding it. A carrier — a ball — has no target to show against, so it only
    /// appears once it is actually holding something.
    /// </summary>
    public bool TryGetStatusBadge(out StatusBadgeInfo info)
    {
        if (!IsConsumer && charge <= 0)
        {
            info = default;
            return false;
        }

        StatusBadgeLibrary library = StatusBadgeLibrary.Instance;
        info = new StatusBadgeInfo(
            library != null ? library.ChargeIcon : null,
            IsConsumer ? $"{charge}/{chargeRequired}" : charge.ToString(),
            library != null ? library.ChargeTint : Color.white,
            chargeBadgeSortOrder);
        return true;
    }

    public void AddCharge(int amount = 1)
    {
        if (amount <= 0)
        {
            return;
        }

        charge += amount;
        ChargeDebug.Log($"{name} gains {amount} Charge, now {charge}");
        ChargeChanged?.Invoke();

        if (IsConsumer && charge >= chargeRequired)
        {
            FullyCharged?.Invoke();
        }
    }

    /// <summary>
    /// Empties this object and returns how much Charge it held. Used both for the
    /// ball-to-component transfer on contact and by consumers spending their bank
    /// when their ability fires.
    /// </summary>
    public int TakeAllCharge()
    {
        int taken = charge;
        if (taken == 0)
        {
            return 0;
        }

        charge = 0;
        ChargeChanged?.Invoke();
        return taken;
    }

    private void OnCollisionEnter(Collision collision)
    {
        HandleCarrierContact(collision);
    }

    /// <summary>
    /// Only balls carry Charge around, so only they resolve contact: deposit into a
    /// consumer if that is what was struck, otherwise roll the activate-nearest proc.
    /// Never both — a hit on a consumer is unambiguously a deposit.
    /// </summary>
    private void HandleCarrierContact(Collision collision)
    {
        if (_ball == null || IsConsumer || charge <= 0)
        {
            return;
        }

        if (TryDeposit(collision.collider))
        {
            return;
        }

        // Chain lightning only fires when the ball actually struck a scoring component
        // — not a wall, and not a flipper (a charged ball can still deposit into a
        // flipper consumer like Moore's Launcher above; that just won't reach here).
        if (!StruckScoringComponent(collision.collider))
        {
            return;
        }

        // The struck point is where the bolt fans out from — "the collided-with
        // component" — falling back to the ball if the contact set is empty.
        Vector3 source = collision.contactCount > 0
            ? collision.GetContact(0).point
            : transform.position;
        TryActivateNearest(source);
    }

    private static bool StruckScoringComponent(Collider other)
    {
        foreach (BoardComponent component in Ball.GetBoardComponentsForScoring(other))
        {
            if (StatusTargeting.CanBeTargeted(component))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Walks up from the struck collider first, so consumers that are not themselves
    /// BoardComponents are found too — Moore's Launcher lives on a PinballFlipper,
    /// which derives from MonoBehaviour and is invisible to the component lookup.
    /// </summary>
    private bool TryDeposit(Collider other)
    {
        ChargeStatus consumer = other.GetComponentInParent<ChargeStatus>();
        if (consumer != null && consumer.IsConsumer)
        {
            ChargeStatusUtility.DrainInto(this, consumer);
            return true;
        }

        foreach (BoardComponent component in Ball.GetBoardComponentsForScoring(other))
        {
            consumer = component != null ? component.GetComponent<ChargeStatus>() : null;
            if (consumer != null && consumer.IsConsumer)
            {
                ChargeStatusUtility.DrainInto(this, consumer);
                return true;
            }
        }

        return false;
    }

    private void TryActivateNearest(Vector3 source)
    {
        if (UnityEngine.Random.value > chanceToActivateNearest)
        {
            return;
        }

        var nearest = BoardComponentRegistry.GetNearest(
            transform.position, ChainTargetCount, nearestSearchRadius);
        if (nearest.Count == 0)
        {
            return;
        }

        ChargeDebug.Log(
            $"{name} discharges: {charge} Charge activates {nearest.Count} nearby");

        ChargeVfxLibrary vfx = ChargeVfxLibrary.Instance;
        ScoreManager scoreManager = ServiceLocator.Get<ScoreManager>();

        foreach (BoardComponent component in nearest)
        {
            // Only score-able components are activated — never flippers/portals, so a
            // discharge can't fire a launcher or teleport a ball.
            if (!StatusTargeting.CanBeTargeted(component))
            {
                continue;
            }

            // Chain lightning arcs from the struck point to each component the
            // discharge activates.
            if (vfx != null)
            {
                vfx.SpawnChainLightning(source, component.transform.position);
            }

            BoardComponent target = component;
            if (scoreManager != null)
            {
                scoreManager.WithActivationStyle(
                    ScoreManager.ScoreActivationStyle.Charge,
                    () => target.ActivateAsBurnTick());
            }
            else
            {
                target.ActivateAsBurnTick();
            }
        }
    }
}
