// Generated by Claude Code (Opus 4.8) for jjmil on 2026-07-20.
// Updated 2026-07-20: scale / emission knobs so the shared VFX can be toned down.
// Updated by Claude Code (claude-opus-5) on 2026-07-28: the Fueled smoke half is
// gone with the Fuel keyword.

using UnityEngine;

/// <summary>
/// Shared fire VFX prefab for statuses that are added at runtime and so can never
/// have their prefab fields wired in the inspector (every runtime-attached
/// <see cref="FireStatus"/>). Loaded once from Resources on demand. The prefab
/// carries its own scale and emission trim, applied on spawn.
/// </summary>
[CreateAssetMenu(menuName = "Pinball/Fire VFX Library", fileName = "FireVfxLibrary")]
public sealed class FireVfxLibrary : ScriptableObject
{
    private const string resourcePath = "FireVfxLibrary";

    private static FireVfxLibrary _instance;
    private static bool _loadAttempted;

    [Header("On Fire (flames)")]
    [Tooltip("Looping flames played while an object is On Fire.")]
    [SerializeField] private GameObject onFireVfxPrefab;
    [SerializeField, Range(0.05f, 2f)] private float onFireVfxScale = 0.5f;
    [SerializeField, Range(0f, 1f)] private float onFireVfxEmissionMultiplier = 1f;

    public static FireVfxLibrary Instance
    {
        get
        {
            if (_instance == null && !_loadAttempted)
            {
                _loadAttempted = true;
                _instance = Resources.Load<FireVfxLibrary>(resourcePath);
            }

            return _instance;
        }
    }

    public GameObject InstantiateOnFireVfx(Transform parent)
    {
        return Spawn(
            onFireVfxPrefab, parent, onFireVfxScale, onFireVfxEmissionMultiplier);
    }

    private static GameObject Spawn(
        GameObject prefab, Transform parent, float scale, float emissionMultiplier)
    {
        if (prefab == null)
        {
            return null;
        }

        GameObject instance = Instantiate(prefab, parent);
        instance.transform.localScale *= scale;

        foreach (ParticleSystem system in
            instance.GetComponentsInChildren<ParticleSystem>(true))
        {
            ParticleSystem.EmissionModule emission = system.emission;
            emission.rateOverTimeMultiplier *= emissionMultiplier;
        }

        return instance;
    }
}
