// Generated by Claude Code (claude-opus-5) for jjmil on 2026-07-28.
// Rewrite: Flammable / Fuel helpers removed; lighting is now the only verb.

using UnityEngine;

/// <summary>
/// Entry points for lighting things on Fire. Every fire source in the game goes
/// through here, so the Flipper / Portal exclusion and the runtime attachment of
/// <see cref="FireStatus"/> live in one place.
/// </summary>
public static class FireStatusUtility
{

    /// <summary>
    /// Lights a board component. Returns false when the component cannot be
    /// targeted, which lets callers skip their own feedback.
    /// </summary>
    public static bool LightComponent(BoardComponent component)
    {
        FireStatus status = GetOrAddComponentStatus(component);
        if (status == null)
        {
            return false;
        }

        status.Ignite();
        return true;
    }

    public static bool LightBall(Ball ball)
    {
        FireStatus status = GetOrAddBallStatus(ball);
        if (status == null)
        {
            return false;
        }

        status.Ignite();
        return true;
    }

    /// <summary>
    /// Lights <paramref name="count"/> random components anywhere on the board.
    /// Returns how many actually caught.
    /// </summary>
    public static int LightRandomComponents(int count, BoardComponent exclude = null)
    {
        int lit = 0;
        foreach (BoardComponent component in BoardComponentRegistry.GetRandom(count, exclude))
        {
            if (LightComponent(component))
            {
                lit++;
            }
        }

        return lit;
    }

    public static FireStatus GetOrAddComponentStatus(BoardComponent component)
    {
        if (!StatusTargeting.CanBeTargeted(component))
        {
            return null;
        }

        FireStatus status = component.GetComponent<FireStatus>();
        if (status == null)
        {
            status = component.gameObject.AddComponent<FireStatus>();
        }

        return status;
    }

    public static FireStatus GetOrAddBallStatus(Ball ball)
    {
        if (ball == null)
        {
            return null;
        }

        FireStatus status = ball.GetComponent<FireStatus>();
        if (status == null)
        {
            status = ball.gameObject.AddComponent<FireStatus>();
        }

        return status;
    }

    /// <summary>
    /// The burn ramp currently on an object, or 1 when it is not alight. Used by
    /// the ball-hit scoring path so real hits on a burning component are scaled
    /// by the same step its own activations are.
    /// </summary>
    public static float GetScoreMultiplier(Component target)
    {
        if (target == null)
        {
            return 1f;
        }

        FireStatus status = target.GetComponent<FireStatus>();
        return status != null ? status.ScoreMultiplier : 1f;
    }

    public static bool IsOnFire(Component target)
    {
        if (target == null)
        {
            return false;
        }

        FireStatus status = target.GetComponent<FireStatus>();
        return status != null && status.IsOnFire;
    }

    /// <summary>
    /// Number of balls and components currently On Fire. Statuses only exist on
    /// objects that have been lit at least once, so scene-wide lookup stays cheap.
    /// </summary>
    public static int CountObjectsOnFire()
    {
        FireStatus[] statuses = Object.FindObjectsByType<FireStatus>(
            FindObjectsSortMode.None);

        int count = 0;
        foreach (FireStatus status in statuses)
        {
            if (status.IsOnFire)
            {
                count++;
            }
        }

        return count;
    }
}
