// Generated by Claude Code (claude-opus-5) for jjmil on 2026-07-28.
// Rewrite: replaces the Flammable / Fuel / stacks model with a flat timed burn.

using System;
using UnityEngine;

/// <summary>
/// The On Fire status, for balls and board components alike. Lighting an object
/// starts a fixed burn; while it burns the object re-activates as if collided with
/// several times a second, and each activation raises its scoring by a compounding
/// step. The ramp resets when the fire goes out.
///
/// There is no Flammable rating and no Fuel: anything can be lit, and only things
/// that say they light objects do so. Re-lighting an object that is already burning
/// <em>adds</em> another full burn onto the end of the remaining time and keeps the
/// ramp where it is, so stacking fire sources onto one component is the payoff.
/// </summary>
public class FireStatus : MonoBehaviour, IStatusBadgeSource
{
    private const int fireBadgeSortOrder = 0;

    /// <summary>
    /// Global multiplier on every fire's tick rate. Modules push this — e.g. Nitro
    /// sets it to 2 so fire ticks twice as often. Reset by the module on removal.
    /// </summary>
    public static float TickRateMultiplier = 1f;

    [Header("Burn")]
    [Tooltip("Seconds a fire lasts before it goes out.")]
    [SerializeField] private float burnSeconds = 4f;
    [Tooltip("Activations per second while burning. Design range is 1 to 4.")]
    [SerializeField] private float activationsPerSecond = 2f;
    [Tooltip("Compounding score increase applied per activation within one burn.")]
    [SerializeField] private float scoreRampPerActivation = 0.1f;
    [Tooltip("Ceiling on the burn ramp. A burn that is never refreshed tops out near "
        + "1.9x on its own; this bounds objects that are re-lit indefinitely.")]
    [SerializeField] private float maxScoreMultiplier = 10f;

    [Header("VFX")]
    [Tooltip("Overrides the flame prefab from FireVfxLibrary for this object. Only "
        + "settable on objects whose prefab already carries a FireStatus; anything "
        + "lit at runtime falls back to the library.")]
    [SerializeField] private GameObject fireVfxPrefab;
    [Tooltip("Where the flames sit. Leave empty to use this object's origin, which "
        + "is wrong for components whose mesh is on a child or whose pivot is off "
        + "the visual centre — assign the visual there instead.")]
    [SerializeField] private Transform vfxAnchor;

    [Header("Runtime")]
    [SerializeField] private bool isOnFire;
    [SerializeField] private float burnSecondsRemaining;
    [SerializeField] private float scoreMultiplier = 1f;

    private float _tickAccumulator;
    private GameObject _fireVfxInstance;
    private BoardComponent[] _components;
    private Ball _ball;

    public event Action Ignited;
    public event Action Extinguished;

    public bool IsOnFire => isOnFire;

    public float BurnSecondsRemaining => isOnFire ? burnSecondsRemaining : 0f;

    public float BurnSeconds => burnSeconds;

    /// <summary>
    /// Remaining burn expressed in whole 4-second stacks, which is what the status
    /// badge shows. A component lit three times reads 3 and steps down to 2 as the
    /// first stack's worth of time burns off.
    /// </summary>
    public int StackCount
    {
        get
        {
            if (!isOnFire || burnSeconds <= 0f)
            {
                return isOnFire ? 1 : 0;
            }

            return Mathf.Max(1, Mathf.CeilToInt(burnSecondsRemaining / burnSeconds));
        }
    }

    /// <summary>
    /// The burn's current scoring step. Real ball hits on a burning object read this
    /// too, so a well-fed component is worth aiming at; only the fire's own
    /// activations advance it.
    /// </summary>
    public float ScoreMultiplier => isOnFire ? scoreMultiplier : 1f;

    public bool TryGetStatusBadge(out StatusBadgeInfo info)
    {
        // Unlike a Charge requirement, Fire has nothing to advertise when it is not
        // burning — everything on the board is flammable, so a permanent zero here
        // would put an icon under every component at once.
        if (!isOnFire)
        {
            info = default;
            return false;
        }

        StatusBadgeLibrary library = StatusBadgeLibrary.Instance;
        info = new StatusBadgeInfo(
            library != null ? library.FireIcon : null,
            StackCount.ToString(),
            library != null ? library.FireTint : Color.white,
            fireBadgeSortOrder);
        return true;
    }

    protected virtual void Awake()
    {
        _components = GetComponents<BoardComponent>();
        _ball = GetComponent<Ball>();

        // Attached here rather than in FireStatusUtility because Ignite() is public
        // and reachable through BoardComponent.FireStatus — Engine and Matchbox both
        // light themselves that way, and prefabs that pre-carry a status never touch
        // the utility at all. Owning it here means no path can light something and
        // leave it without a readout.
        StatusBadgeDisplay.EnsureOn(gameObject);
    }

    protected virtual void Update()
    {
        if (!isOnFire || !StatusTickGate.CanTickNow())
        {
            return;
        }

        burnSecondsRemaining -= Time.deltaTime;
        if (burnSecondsRemaining <= 0f)
        {
            Extinguish();
            return;
        }

        float effectiveRate = activationsPerSecond * Mathf.Max(0.01f, TickRateMultiplier);
        if (effectiveRate <= 0f)
        {
            return;
        }

        float tickInterval = 1f / effectiveRate;
        _tickAccumulator += Time.deltaTime;
        while (_tickAccumulator >= tickInterval)
        {
            _tickAccumulator -= tickInterval;
            ActivateTick();
        }
    }

    protected virtual void OnDestroy()
    {
        if (isOnFire)
        {
            ServiceLocator.Get<AudioManager>()?.StopBurningSound(gameObject);
        }
    }

    /// <summary>
    /// Lights the object. On something already burning this stacks: another full
    /// burn is added to the end of whatever time is left, and the ramp keeps
    /// climbing. There is no ceiling on stacked time by design, so a component fed
    /// by several sources can burn for a very long while.
    /// </summary>
    public void Ignite()
    {
        if (isOnFire)
        {
            // Deliberately does not touch _tickAccumulator. Zeroing it here would
            // mean anything re-lit faster than one tick interval never reached the
            // interval at all, and so never ticked.
            burnSecondsRemaining += burnSeconds;
            FireDebug.Log($"{name} re-lit, burn extended to "
                + $"{burnSecondsRemaining:0.0}s ({StackCount} stacks, "
                + $"ramp holds at {scoreMultiplier:0.00}x)");
            return;
        }

        burnSecondsRemaining = burnSeconds;
        _tickAccumulator = 0f;
        isOnFire = true;
        scoreMultiplier = 1f;
        FireDebug.Log($"{name} lit, burning for {burnSeconds}s");
        StartFireFeedback();
        Ignited?.Invoke();
    }

    public void Extinguish()
    {
        if (!isOnFire)
        {
            return;
        }

        FireDebug.Log($"{name} burned out at {scoreMultiplier:0.00}x");
        isOnFire = false;
        burnSecondsRemaining = 0f;
        _tickAccumulator = 0f;
        scoreMultiplier = 1f;
        StopFireFeedback();
        Extinguished?.Invoke();
    }

    /// <summary>
    /// One burn activation, then the ramp steps up.
    /// </summary>
    private void ActivateTick()
    {
        ScoreManager scoreManager = ServiceLocator.Get<ScoreManager>();
        if (scoreManager != null)
        {
            scoreManager.WithActivationStyle(
                ScoreManager.ScoreActivationStyle.Fire,
                () =>
                {
                    ActivateOwnComponents();
                    ActivateLastComponentHitByBall();
                });
        }
        else
        {
            ActivateOwnComponents();
            ActivateLastComponentHitByBall();
        }

        // Re-lighting refreshes the timer and keeps the ramp, so anything that can
        // light itself repeatedly (Molotov, a ball living on a Lighter kicker) would
        // otherwise compound without ever burning out.
        scoreMultiplier = Mathf.Min(
            scoreMultiplier * (1f + scoreRampPerActivation), maxScoreMultiplier);
    }

    /// <summary>
    /// A burning component re-activates itself. Its scoring path reads this same
    /// status for the ramp (see <see cref="BoardComponent.FireScoreMultiplier"/>),
    /// so no extra scope is needed here.
    /// </summary>
    private void ActivateOwnComponents()
    {
        foreach (BoardComponent component in _components)
        {
            if (StatusTargeting.CanBeTargeted(component))
            {
                component.ActivateAsBurnTick();
            }
        }
    }

    /// <summary>
    /// A burning ball re-activates the last component it touched. That component is
    /// usually not itself alight, so the ball's own ramp has to be applied as a
    /// scope rather than read off the target.
    /// </summary>
    private void ActivateLastComponentHitByBall()
    {
        GameObject lastHit = _ball != null ? _ball.LastObjectHit : null;
        if (lastHit == null)
        {
            return;
        }

        BoardComponent[] hitComponents = lastHit.GetComponents<BoardComponent>();
        if (hitComponents.Length == 0)
        {
            hitComponents = lastHit.GetComponentsInParent<BoardComponent>();
        }

        ScoreManager scoreManager = ServiceLocator.Get<ScoreManager>();
        foreach (BoardComponent component in hitComponents)
        {
            if (!StatusTargeting.CanBeTargeted(component))
            {
                continue;
            }

            BoardComponent target = component;
            if (scoreManager != null)
            {
                scoreManager.WithScoreMultiplier(
                    scoreMultiplier, () => target.ActivateAsBurnTick());
            }
            else
            {
                target.ActivateAsBurnTick();
            }
        }
    }

    /// <summary>
    /// Where flames are parented. Deliberately has no automatic fallback: the VFX is
    /// <em>parented</em> here and <see cref="FireVfxLibrary"/> then applies its scale
    /// trim as a local scale, so anchoring to a child that carries a non-unit scale
    /// would silently resize the flames. Picking a child by search would do that to
    /// every existing fire-capable component at once. Assign it explicitly where the
    /// origin is wrong.
    /// </summary>
    private Transform ResolveVfxAnchor()
    {
        return vfxAnchor != null ? vfxAnchor : transform;
    }

    private void StartFireFeedback()
    {
        if (_fireVfxInstance == null)
        {
            Transform anchor = ResolveVfxAnchor();
            _fireVfxInstance = fireVfxPrefab != null
                ? Instantiate(fireVfxPrefab, anchor)
                : FireVfxLibrary.Instance?.InstantiateOnFireVfx(anchor);
        }

        ServiceLocator.Get<AudioManager>()?.StartBurningSound(gameObject);
    }

    private void StopFireFeedback()
    {
        if (_fireVfxInstance != null)
        {
            Destroy(_fireVfxInstance);
            _fireVfxInstance = null;
        }

        ServiceLocator.Get<AudioManager>()?.StopBurningSound(gameObject);
    }
}
