// Generated by Claude Code (claude-opus-5) for jjmil on 2026-07-28.
// Rewrite: replaces the Flammable / Fuel / stacks model with a flat timed burn.

using System;
using UnityEngine;

/// <summary>
/// The On Fire status, for balls and board components alike. Lighting an object
/// starts a fixed burn; while it burns the object re-activates as if collided with
/// several times a second, and each activation raises its scoring by a compounding
/// step. The ramp resets when the fire goes out.
///
/// There is no Flammable rating and no Fuel: anything can be lit, and only things
/// that say they light objects do so. Re-lighting an object that is already burning
/// refreshes the timer and keeps the ramp where it is, which is what makes stacking
/// fire sources onto one component the payoff.
/// </summary>
public class FireStatus : MonoBehaviour
{
    [Header("Burn")]
    [Tooltip("Seconds a fire lasts before it goes out.")]
    [SerializeField] private float burnSeconds = 4f;
    [Tooltip("Activations per second while burning. Design range is 1 to 4.")]
    [SerializeField] private float activationsPerSecond = 2f;
    [Tooltip("Compounding score increase applied per activation within one burn.")]
    [SerializeField] private float scoreRampPerActivation = 0.25f;
    [Tooltip("Ceiling on the burn ramp. A burn that is never refreshed tops out near "
        + "4.8x on its own; this bounds objects that are re-lit indefinitely.")]
    [SerializeField] private float maxScoreMultiplier = 10f;

    [Header("VFX")]
    [Tooltip("Overrides the flame prefab from FireVfxLibrary for this object.")]
    [SerializeField] private GameObject fireVfxPrefab;

    [Header("Runtime")]
    [SerializeField] private bool isOnFire;
    [SerializeField] private float burnSecondsRemaining;
    [SerializeField] private float scoreMultiplier = 1f;

    private float _tickAccumulator;
    private GameObject _fireVfxInstance;
    private BoardComponent[] _components;
    private Ball _ball;

    public event Action Ignited;
    public event Action Extinguished;

    public bool IsOnFire => isOnFire;

    /// <summary>
    /// The burn's current scoring step. Real ball hits on a burning object read this
    /// too, so a well-fed component is worth aiming at; only the fire's own
    /// activations advance it.
    /// </summary>
    public float ScoreMultiplier => isOnFire ? scoreMultiplier : 1f;

    protected virtual void Awake()
    {
        _components = GetComponents<BoardComponent>();
        _ball = GetComponent<Ball>();
    }

    protected virtual void Update()
    {
        if (!isOnFire || !StatusTickGate.CanTickNow())
        {
            return;
        }

        burnSecondsRemaining -= Time.deltaTime;
        if (burnSecondsRemaining <= 0f)
        {
            Extinguish();
            return;
        }

        if (activationsPerSecond <= 0f)
        {
            return;
        }

        float tickInterval = 1f / activationsPerSecond;
        _tickAccumulator += Time.deltaTime;
        while (_tickAccumulator >= tickInterval)
        {
            _tickAccumulator -= tickInterval;
            ActivateTick();
        }
    }

    protected virtual void OnDestroy()
    {
        if (isOnFire)
        {
            ServiceLocator.Get<AudioManager>()?.StopBurningSound(gameObject);
        }
    }

    /// <summary>
    /// Lights the object. On something already burning this refreshes the timer and
    /// leaves the ramp climbing rather than doing nothing.
    /// </summary>
    public void Ignite()
    {
        burnSecondsRemaining = burnSeconds;
        _tickAccumulator = 0f;

        if (isOnFire)
        {
            FireDebug.Log($"{name} re-lit, burn refreshed to {burnSeconds}s "
                + $"(ramp holds at {scoreMultiplier:0.00}x)");
            return;
        }

        isOnFire = true;
        scoreMultiplier = 1f;
        FireDebug.Log($"{name} lit, burning for {burnSeconds}s");
        StartFireFeedback();
        Ignited?.Invoke();
    }

    public void Extinguish()
    {
        if (!isOnFire)
        {
            return;
        }

        FireDebug.Log($"{name} burned out at {scoreMultiplier:0.00}x");
        isOnFire = false;
        burnSecondsRemaining = 0f;
        _tickAccumulator = 0f;
        scoreMultiplier = 1f;
        StopFireFeedback();
        Extinguished?.Invoke();
    }

    /// <summary>
    /// One burn activation, then the ramp steps up.
    /// </summary>
    private void ActivateTick()
    {
        ActivateOwnComponents();
        ActivateLastComponentHitByBall();

        // Re-lighting refreshes the timer and keeps the ramp, so anything that can
        // light itself repeatedly (Molotov, a ball living on a Lighter kicker) would
        // otherwise compound without ever burning out.
        scoreMultiplier = Mathf.Min(
            scoreMultiplier * (1f + scoreRampPerActivation), maxScoreMultiplier);
    }

    /// <summary>
    /// A burning component re-activates itself. Its scoring path reads this same
    /// status for the ramp (see <see cref="BoardComponent.FireScoreMultiplier"/>),
    /// so no extra scope is needed here.
    /// </summary>
    private void ActivateOwnComponents()
    {
        foreach (BoardComponent component in _components)
        {
            if (StatusTargeting.CanBeTargeted(component))
            {
                component.ActivateAsBurnTick();
            }
        }
    }

    /// <summary>
    /// A burning ball re-activates the last component it touched. That component is
    /// usually not itself alight, so the ball's own ramp has to be applied as a
    /// scope rather than read off the target.
    /// </summary>
    private void ActivateLastComponentHitByBall()
    {
        GameObject lastHit = _ball != null ? _ball.LastObjectHit : null;
        if (lastHit == null)
        {
            return;
        }

        BoardComponent[] hitComponents = lastHit.GetComponents<BoardComponent>();
        if (hitComponents.Length == 0)
        {
            hitComponents = lastHit.GetComponentsInParent<BoardComponent>();
        }

        ScoreManager scoreManager = ServiceLocator.Get<ScoreManager>();
        foreach (BoardComponent component in hitComponents)
        {
            if (!StatusTargeting.CanBeTargeted(component))
            {
                continue;
            }

            BoardComponent target = component;
            if (scoreManager != null)
            {
                scoreManager.WithScoreMultiplier(
                    scoreMultiplier, () => target.ActivateAsBurnTick());
            }
            else
            {
                target.ActivateAsBurnTick();
            }
        }
    }

    private void StartFireFeedback()
    {
        if (_fireVfxInstance == null)
        {
            _fireVfxInstance = fireVfxPrefab != null
                ? Instantiate(fireVfxPrefab, transform)
                : FireVfxLibrary.Instance?.InstantiateOnFireVfx(transform);
        }

        ServiceLocator.Get<AudioManager>()?.StartBurningSound(gameObject);
    }

    private void StopFireFeedback()
    {
        if (_fireVfxInstance != null)
        {
            Destroy(_fireVfxInstance);
            _fireVfxInstance = null;
        }

        ServiceLocator.Get<AudioManager>()?.StopBurningSound(gameObject);
    }
}
