// Generated by Claude Code (claude-opus-5) for jjmil on 2026-07-28.

/// <summary>
/// Which board components status effects are allowed to act on. Flippers and
/// Portals are never valid targets: the player needs them to stay readable, and
/// re-activating them on their own would fire flips and teleports without input.
/// Components sitting on the shop shelf are excluded too — they are display copies
/// of things the player has not bought yet, and effects that reach for "a random
/// component" would otherwise be able to set the merchandise alight.
///
/// Fire, Charge's activate-nearest, and Detonate's blast radius all share this
/// filter so the rule cannot drift between them.
/// </summary>
public static class StatusTargeting
{
    public static bool CanBeTargeted(BoardComponent component)
    {
        if (component == null)
        {
            return false;
        }

        // Flippers and Portals are marked non-targetable in the catalog; the
        // shop-shelf exclusion stays here since it is about the individual instance
        // (a display copy), not the type.
        if (!ComponentTypeCatalog.StatusTargetable(component.componentType))
        {
            return false;
        }

        return component.GetComponent<ShopOffer3DEntry>() == null;
    }
}
