// Generated by Claude Code (claude-opus-5) for jjmil on 2026-07-28.

/// <summary>
/// Shared gate for status effects that advance on their own clock. Statuses only
/// tick during live play: countdowns and activation ticks freeze while no run is
/// active, the shop is open, or a drain tally is in progress.
/// </summary>
public static class StatusTickGate
{

    public static bool CanTickNow()
    {
        GameRulesManager rules = ServiceLocator.Get<GameRulesManager>();
        if (rules == null || !rules.RunActive || rules.IsShopOpen)
        {
            return false;
        }

        DrainHandler drainHandler = ServiceLocator.Get<DrainHandler>();
        return drainHandler == null || !drainHandler.IsDrainProcessing;
    }
}
