// Generated by Claude Code (claude-opus-5) for jjmil on 2026-07-28.

using UnityEngine;

/// <summary>
/// Entropy bumper: purely a spreader. It never lights itself — something else has
/// to set it going — but once it is burning, every activation has a chance to throw
/// fire at two random components anywhere on the board.
///
/// Because a burning component activates itself twice a second, a lit Fireworks is
/// a continuous source, not a one-off. That is the point of it, and it is the
/// fastest way a board goes fully alight.
/// </summary>
public class FireworksComponent : Bumper
{
    [Header("Fireworks")]
    [SerializeField, Range(0f, 1f)] private float chanceToScatter = 0.5f;
    [SerializeField] private int componentsToLight = 2;

    protected override void OnCollisionEnter(Collision collision)
    {
        base.OnCollisionEnter(collision);

        if (collision.collider.GetComponent<Ball>() != null)
        {
            TryScatter();
        }
    }

    public override void ActivateAsIfHit()
    {
        base.ActivateAsIfHit();
        TryScatter();
    }

    private void TryScatter()
    {
        if (!IsOnFire || Random.value > chanceToScatter)
        {
            return;
        }

        int lit = FireStatusUtility.LightRandomComponents(componentsToLight, this);
        if (lit > 0)
        {
            FireDebug.Log($"{name} scatters, lighting {lit} components");
        }
    }
}
