// Generated by Claude Code (claude-opus-5) for jjmil on 2026-07-28.

using UnityEngine;

/// <summary>
/// Entropy sling: every activation has a chance to set the matchbox itself alight,
/// making it a board's self-starting fire source — it needs nothing else to get
/// going. "Activation" covers real ball collisions and programmatic ones (a
/// Capacitor discharge, a detonation) alike.
///
/// The roll is skipped while it is already burning. Taken literally, "light on
/// Fire" has nothing to do to something already lit — and since a burning
/// component activates itself twice a second, rolling there would re-light it on
/// its own ticks and it would never go out.
/// </summary>
public class MatchboxComponent : Bumper
{
    [Header("Matchbox")]
    [SerializeField, Range(0f, 1f)] private float chanceToLightSelf = 0.4f;

    protected override void Awake()
    {
        base.Awake();

        // Attach up front: the Matchbox is its own fire source, and pre-attaching
        // also puts its burn knobs on the prefab.
        FireStatusUtility.GetOrAddComponentStatus(this);
    }

    protected override void OnCollisionEnter(Collision collision)
    {
        base.OnCollisionEnter(collision);

        if (collision.collider.GetComponent<Ball>() != null)
        {
            TryLightSelf();
        }
    }

    public override void ActivateAsIfHit()
    {
        base.ActivateAsIfHit();
        TryLightSelf();
    }

    private void TryLightSelf()
    {
        if (FireStatus == null || FireStatus.IsOnFire)
        {
            return;
        }

        if (Random.value > chanceToLightSelf)
        {
            return;
        }

        FireDebug.Log($"{name} strikes and catches");
        FireStatus.Ignite();
    }
}
