// Generated by Claude Code (claude-opus-5) for jjmil on 2026-07-28.

using UnityEngine;

/// <summary>
/// Tech/Entropy bumper: every activation has a chance to arc fire onto a random
/// component somewhere on the board. Unlike Fireworks it does not need to be
/// burning itself, so it is the reliable way to get fire started somewhere other
/// than where the ball is.
///
/// It excludes itself from the draw. Lighting itself would put it on the same
/// self-sustaining loop a burning component's twice-a-second activations create.
/// </summary>
public class ShortCircuitComponent : Bumper
{
    [Header("Short Circuit")]
    [SerializeField, Range(0f, 1f)] private float chanceToArc = 0.3f;
    [SerializeField] private int componentsToLight = 1;

    protected override void OnCollisionEnter(Collision collision)
    {
        base.OnCollisionEnter(collision);

        if (collision.collider.GetComponent<Ball>() != null)
        {
            TryArc();
        }
    }

    public override void ActivateAsIfHit()
    {
        base.ActivateAsIfHit();
        TryArc();
    }

    private void TryArc()
    {
        if (Random.value > chanceToArc)
        {
            return;
        }

        int lit = FireStatusUtility.LightRandomComponents(componentsToLight, this);
        if (lit > 0)
        {
            FireDebug.Log($"{name} arcs, lighting {lit} component(s)");
        }
    }
}
