// Generated by Claude Code (claude-opus-4-8) for jjmil on 2026-07-29.

using UnityEngine;

/// <summary>
/// Astral Projection: doubles how long Holoballs persist — whether they expire on a
/// number of activations or on a timer.
/// </summary>
public sealed class AstralProjectionModule : MonoBehaviour
{
    [SerializeField] private float lifetimeMultiplier = 2f;

    private void Awake() => Holoball.LifetimeMultiplier *= lifetimeMultiplier;
    private void OnDestroy() => Holoball.LifetimeMultiplier /= lifetimeMultiplier;
}
