// Generated by Claude Code (claude-opus-4-8) for jjmil on 2026-07-29.

using UnityEngine;

/// <summary>
/// Fission: a ball that splits produces one extra ball — splitting into three
/// instead of two. Applied to each ball as it activates.
/// </summary>
public sealed class FissionModule : MonoBehaviour
{
    private BallSpawner _ballSpawner;

    private void Awake()
    {
        _ballSpawner = ServiceLocator.Get<BallSpawner>();
        if (_ballSpawner != null) _ballSpawner.ActivateBall += AddSplitBall;
    }

    private void OnDestroy()
    {
        if (_ballSpawner != null) _ballSpawner.ActivateBall -= AddSplitBall;
    }

    private void AddSplitBall(GameObject ball)
    {
        ISplitter splitter = ball.GetComponent<ISplitter>();
        if (splitter != null) splitter.BallsOnSplit++;
    }
}
