// Generated by Claude Code (claude-opus-4-8) for jjmil on 2026-07-29.

using UnityEngine;

/// <summary>
/// Fission: a ball that splits into copies of itself produces one extra — splitting
/// into three instead of two. Only affects true splitters (Scatter, Matryoshka), not
/// projector balls (Confetti, Eye on the Prize) that spawn other balls. Applied to
/// each ball as it activates.
/// </summary>
public sealed class FissionModule : MonoBehaviour
{
    private BallSpawner _ballSpawner;

    private void Awake()
    {
        _ballSpawner = ServiceLocator.Get<BallSpawner>();
        if (_ballSpawner != null) _ballSpawner.ActivateBall += AddSplitBall;
    }

    private void OnDestroy()
    {
        if (_ballSpawner != null) _ballSpawner.ActivateBall -= AddSplitBall;
    }

    private void AddSplitBall(GameObject ball)
    {
        IFissionable splitter = ball.GetComponent<IFissionable>();
        if (splitter != null) splitter.BallsOnSplit++;
    }
}
