// Generated by Claude Code (claude-opus-4-8) for jjmil on 2026-07-29.

using UnityEngine;

/// <summary>
/// Hustle: every credit gain grants one extra credit.
/// </summary>
public sealed class HustleModule : MonoBehaviour
{
    [SerializeField] private int bonusPerGain = 1;

    private CoinController _coinController;

    private void Awake()
    {
        _coinController = ServiceLocator.Get<CoinController>();
        if (_coinController != null) _coinController.ModuleFlatCoinBonus += bonusPerGain;
    }

    private void OnDestroy()
    {
        if (_coinController != null) _coinController.ModuleFlatCoinBonus -= bonusPerGain;
    }
}
