// Generated by Claude Code (claude-opus-4-8) for jjmil on 2026-07-29.

using UnityEngine;

/// <summary>
/// Last Chance: if the hand/queue is empty when you level up, the level-up rewards
/// are doubled. GameRulesManager checks <see cref="ActiveCount"/> at level-up time.
/// </summary>
public sealed class LastChanceModule : MonoBehaviour
{
    public static int ActiveCount;

    private void Awake() => ActiveCount++;
    private void OnDestroy() => ActiveCount--;
}
