// Generated by Claude Code (claude-opus-4-8) for jjmil on 2026-07-29.

using UnityEngine;

/// <summary>
/// Nitro: fire ticks twice as often (doubles every fire's activation frequency).
/// </summary>
public sealed class NitroModule : MonoBehaviour
{
    [SerializeField] private float tickRateMultiplier = 2f;

    private void Awake() => FireStatus.TickRateMultiplier *= tickRateMultiplier;
    private void OnDestroy() => FireStatus.TickRateMultiplier /= tickRateMultiplier;
}
