// Generated by Claude Code (claude-opus-4-8) for jjmil on 2026-07-29.

using UnityEngine;

/// <summary>
/// Punch Card: every Nth shop purchase (counted cumulatively across the run) is free.
/// The shop calls <see cref="PeekNextPurchaseFree"/> / <see cref="RegisterPurchase"/>
/// through its pay path.
/// </summary>
public sealed class PunchCardModule : MonoBehaviour
{
    [SerializeField] private int freeEvery = 4;

    private static int _activeCount;
    private static int _freeEvery = 4;
    private static int _purchaseCount;

    private void Awake()
    {
        _activeCount++;
        _freeEvery = Mathf.Max(1, freeEvery);
    }

    private void OnDestroy()
    {
        _activeCount = Mathf.Max(0, _activeCount - 1);
        // The run's purchase tally only matters while the card is owned.
        if (_activeCount == 0) _purchaseCount = 0;
    }

    /// <summary>
    /// True if the next committed purchase would be free — checked before charging,
    /// without advancing the counter.
    /// </summary>
    public static bool PeekNextPurchaseFree()
    {
        return _activeCount > 0 && (_purchaseCount + 1) % _freeEvery == 0;
    }

    /// <summary>Advances the run purchase tally for one committed purchase.</summary>
    public static void RegisterPurchase()
    {
        if (_activeCount > 0) _purchaseCount++;
    }
}
