using UnityEngine;

// Generated by Cursor AI (GPT-5.2) for jjmil on 2026-02-16.

/// <summary>
/// Attach this to a drone prefab so the prefab can be mapped back to its DroneDefinition.
/// </summary>
public sealed class DroneDefinitionLink : MonoBehaviour
{
    [SerializeField] private DroneDefinition definition;

    public DroneDefinition Definition => definition;

    public bool TryGetDefinition(out DroneDefinition outDefinition)
    {
        outDefinition = definition;
        return outDefinition != null;
    }
}