// Generated by Cursor (jjmil) on 2026-02-26. Updated 2026-03-12: suspense only activates after portal.
// Updated 2026-03-16: use InputSystem flipper actions so reset works for keyboard, gamepad, and mouse.
using UnityEngine;

#if ENABLE_INPUT_SYSTEM
using UnityEngine.InputSystem;
#endif

public class SuspenseBall : Ball, IPortalTeleportListener
{
    [SerializeField] private float baseGrowth = 1.1f;
    [SerializeField] private Color lightPurple = new Color(0.76f, 0.56f, 1f);
    [SerializeField] private Color darkPurple = new Color(0.2f, 0f, 0.35f);
    [SerializeField] private float maxColorTime = 10f;
    private float timeSinceReset;
    private Renderer ballRenderer;
    private bool suspenseActive;

    [SerializeField] private InputActionReference leftFlipAction;
    [SerializeField] private InputActionReference rightFlipAction;

    void Awake()
    {
        ballRenderer = GetComponent<Renderer>();

        if (ballRenderer != null)
        {
            ballRenderer.material.color = lightPurple;
        }

    }

    public void OnTeleportedThroughPortal()
    {
        suspenseActive = true;
    }

    void Update()
    {
        if (!suspenseActive)
        {
            return;
        }

        if (WasFlipperPressedThisFrame())
        {
            timeSinceReset = 0f;
        }

        timeSinceReset += Time.deltaTime;
        UpdateColor();
    }

    private bool WasFlipperPressedThisFrame()
    {
        if (leftFlipAction.action.WasPressedThisFrame())
        {
            return true;
        }
            
        if (rightFlipAction.action.WasPressedThisFrame())
        {
            return true;
        }

        return false;
    }

    private void UpdateColor()
    {
        if (ballRenderer == null)
        {
            return;
        }

        float t = Mathf.Clamp01(timeSinceReset / maxColorTime);
        ballRenderer.material.color = Color.Lerp(lightPurple, darkPurple, t);
    }

    new void OnCollisionEnter(Collision collision)
    {
        base.OnCollisionEnter(collision);
    }

    override protected void AddScore(float amount, TypeOfScore typeOfScore, Transform pos)
    {
        float scale = Mathf.Pow(baseGrowth, timeSinceReset);
        base.AddScore(amount * scale, typeOfScore, pos);
    }
}
