// Generated by Cursor (jjmil) on 2026-02-26. Updated 2026-03-12: suspense only activates after portal.
using UnityEngine;

public class SuspenseBall : Ball, IPortalTeleportListener
{
    [SerializeField] private float baseGrowth = 1.1f;
    [SerializeField] private Color lightPurple = new Color(0.76f, 0.56f, 1f);
    [SerializeField] private Color darkPurple = new Color(0.2f, 0f, 0.35f);
    [SerializeField] private float maxColorTime = 10f;
    private float timeSinceReset;
    private Renderer ballRenderer;
    private bool suspenseActive;

    new void Awake()
    {
        base.Awake();
        ballRenderer = GetComponent<Renderer>();

        if (ballRenderer != null)
        {
            ballRenderer.material.color = lightPurple;
        }
    }

    public void OnTeleportedThroughPortal()
    {
        suspenseActive = true;
    }

    void Update()
    {
        if (!suspenseActive)
        {
            return;
        }

        if (ControlsBindingsService.WasPressedThisFrame(ControlAction.LeftFlipper) ||
            ControlsBindingsService.WasPressedThisFrame(ControlAction.RightFlipper))
        {
            timeSinceReset = 0f;
        }

        timeSinceReset += Time.deltaTime;
        UpdateColor();
    }

    private void UpdateColor()
    {
        if (ballRenderer == null)
        {
            return;
        }

        float t = Mathf.Clamp01(timeSinceReset / maxColorTime);
        ballRenderer.material.color = Color.Lerp(lightPurple, darkPurple, t);
    }

    new void OnCollisionEnter(Collision collision)
    {
        base.OnCollisionEnter(collision);
    }

    override protected void AddScore(float amount, TypeOfScore typeOfScore, Transform pos)
    {
        float scale = Mathf.Pow(baseGrowth, timeSinceReset);
        base.AddScore(amount * scale, typeOfScore, pos);
    }
}
