// Generated by Claude Code (claude-opus-4-8) for jjmil on 2026-07-29.

using UnityEngine;

/// <summary>
/// Marks — and tunes — a board component's ball-hit particles. Put this on a child
/// of the component and position that child where the sparks should originate;
/// <see cref="BallParticleHandler"/> emits at this transform using the size and
/// amount below.
///
/// Because it lives on the prefab, every variant tunes independently: editing the
/// BombBumper prefab's marker sets every BombBumper, without touching other bumpers.
/// A component with no marker falls back to emitting from its own origin at the
/// ball's default size and amount.
/// </summary>
public sealed class HitParticleOrigin : MonoBehaviour
{
    [Tooltip("Particle start-size multiplier for hits on this component. " +
        "1 = the emitter prefab's default size.")]
    public float size = 1f;

    [Tooltip("Base particle burst amount, before ball-speed scaling. " +
        "0 = use the ball's default emit amount.")]
    public int emitAmount = 0;
}
