// Generated by Claude Code (claude-opus-4-8) for jjmil on 2026-07-29.

using UnityEngine;

/// <summary>
/// Placeholder chain-lightning visual: a straight <see cref="LineRenderer"/> drawn
/// between two world points that fades out and destroys itself. Deliberately plain —
/// the real bolt is tech-art to be authored by a human; this just marks the link
/// from a struck component to an activated one.
/// </summary>
public sealed class LightningBolt : MonoBehaviour
{
    [SerializeField] private float width = 0.1f;
    [SerializeField] private Color color = new Color(0.45f, 0.72f, 1f, 1f);
    [Tooltip("Seconds the line lives before destroying itself (fading as it goes).")]
    [SerializeField] private float lifetime = 0.25f;
    [Tooltip("Optional line material. Leave empty for a runtime vertex-colour unlit material.")]
    [SerializeField] private Material material;

    private LineRenderer _line;
    private float _age;

    private static Material _fallbackMaterial;

    private void Awake()
    {
        _line = GetComponent<LineRenderer>();
        if (_line == null)
        {
            _line = gameObject.AddComponent<LineRenderer>();
        }

        _line.useWorldSpace = true;
        _line.alignment = LineAlignment.View;
        _line.numCapVertices = 2;
        _line.shadowCastingMode = UnityEngine.Rendering.ShadowCastingMode.Off;
        _line.receiveShadows = false;
        _line.widthMultiplier = width;
        _line.startColor = _line.endColor = color;
        _line.material = material != null ? material : GetFallbackMaterial();
        _line.positionCount = 2;
    }

    /// <summary>Draws the line between two world points.</summary>
    public void Initialize(Vector3 from, Vector3 to)
    {
        _age = 0f;
        _line.SetPosition(0, from);
        _line.SetPosition(1, to);
    }

    private void Update()
    {
        _age += Time.deltaTime;
        if (_age >= lifetime)
        {
            Destroy(gameObject);
        }
    }

    private static Material GetFallbackMaterial()
    {
        if (_fallbackMaterial == null)
        {
            Shader shader = Shader.Find("Sprites/Default");
            if (shader == null) shader = Shader.Find("Universal Render Pipeline/Unlit");
            if (shader == null) shader = Shader.Find("Unlit/Color");
            _fallbackMaterial = new Material(shader);
        }

        return _fallbackMaterial;
    }
}
